# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/0r363f5ibydwfkw57g8s2gc4d7alfy5x-hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases
    alias cat bat
    alias d docker
    alias ducks 'du -cks * | sort -rn | head'
    alias ez-flash 'wally-cli $(eza --online --sort=oldest ~/Downloads/ergodox*.hex | head -1)'
    alias fix-interpreter 'patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)"'
    alias g git
    alias j jj
    alias lngc 'find . -xtype l -delete'
    alias ls 'eza --time-style=long-iso --git'
    alias machine-hash 'nix-hash --type sha256 --base32 --flat /etc/machine-id'
    alias nix nix-nom
    alias nixbuild '/nix/store/cj68rzfi0nxyagg86p5r0yivcgvkp161-rlwrap-0.46.1/bin/rlwrap ssh nixbuild.net'
    alias poison '. <(nix print-dev-env)'
    alias sshfp 'ssh-keygen -r $(hostname) > sshfp.txt'
    alias tungz 'tar xvzf'
    alias update-known-hosts 'curl --silent '\''https://ca.mpi-klsb.mpg.de/ssh_known_hosts'\'' -o "/home/runner/.ssh/known_hosts_mpi-klsb"'
    alias wolgrep 'ngrep -t -W single '\''\xff{6}(.{6})\1{15}'\'' '\''port 9'\'''
    alias wsl-open /nix/store/xf2hnaf1p5n4c0qjbcrs1b7nz8i6lnzq-explorer/bin/explorer
    alias x-www-browser /nix/store/xf2hnaf1p5n4c0qjbcrs1b7nz8i6lnzq-explorer/bin/explorer

    # Interactive shell initialisation
    /nix/store/xc1nx9ww5pcy7mzkqy6ry1ikm1cn6q9d-fzf-0.62.0/bin/fzf --fish | source

    fish_vi_key_bindings

    set -gx GPG_TTY (tty)
    /nix/store/wfsqj2kiqsnrp24gjfrw2bprrmzca31i-gnupg-2.4.7/bin/gpg-connect-agent --quiet updatestartuptty /bye >/dev/null

    function __fish_command_not_found_handler --on-event fish_command_not_found
        /nix/store/9q92k91jbjq1g7fp75g00inxaq8q9wdq-command-not-found $argv
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/runner/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/sjnpc62pq28xyjniykxdgh2yi56ymgpq-atuin-18.5.0/bin/atuin init fish | source

    /nix/store/rjnigckx9rmga58562hxw9kr5hynavcd-direnv-2.36.0/bin/direnv hook fish | source

end
