# a2ping
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/a2ping.1
complete -c a2ping -s h -l help -d 'Show a summary of the usage'
complete -c a2ping -l doc -d 'Show the man page'
complete -c a2ping -s v -d 'Show progress and debug messages (default: no) '
complete -c a2ping -l bboxfrom -d 'Method for determining the BoundingBox  (default: guess)'
complete -c a2ping -l papersize -d '(default: default) (bp)'
complete -c a2ping -l threshold -d 'min color for 1 in 8->1 bit conv  (default: 128) '
complete -c a2ping -l gs-cmd -d 'path to Ghostscript program (default: gs or gswin32c)'
complete -c a2ping -l gs-ccmd -d 'path to Ghostscript for BoundingBox calculation (default: gs or gswin32c)'
complete -c a2ping -l gsextra -d 'Pass extra arguments to gs'

