# accessdb
# Autogenerated from man page /nix/store/6y6ijw6avikf17cyks2k07vc9q1wq31v-man-db-2.13.0/share/man/man8/accessdb.8.gz
complete -c accessdb -s d -l debug -d 'Print debugging information'
complete -c accessdb -s '?' -l help -d 'Print a help message and exit'
complete -c accessdb -l usage -d 'Print a short usage message and exit'
complete -c accessdb -s V -l version -d 'Display version information.  AUTHOR'

