# afm2afm
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/afm2afm.1
complete -c afm2afm -o help
complete -c afm2afm -o version
complete -c afm2afm -o encoding
complete -c afm2afm -o kpx
complete -c afm2afm -o output

