# alacritty
# Autogenerated from man page /nix/store/qlrg9m9r8asyhwsgwhnza7kd3b07j3xw-alacritty-0.15.1/share/man/man1/alacritty.1.gz
complete -c alacritty -s e -l command -d PP
complete -c alacritty -l config-file -d PP
complete -c alacritty -s o -l option -d PP
complete -c alacritty -l socket -d PP
complete -c alacritty -s T -l title -d PP

