# albatross
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/albatross.1
complete -c albatross -l show-styles -d 'Show available font styles'
complete -c albatross -l detailed -d 'Show a detailed font list'
complete -c albatross -l ansi-level -d 'Set the default ANSI level'
complete -c albatross -l border-style -d 'Set the border style'
complete -c albatross -l or -d 'Look for each glyph separately'
complete -c albatross -l version -d 'Show the version and exit'
complete -c albatross -l help -d 'Show a help message and exit'

