# arara
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/arara.1
complete -c arara -l log -d 'Generate a log output'
complete -c arara -l verbose -l silent -d 'Print or suppress command output'
complete -c arara -l dry-run -d 'Go through all the motions of running a command but with no actual calls'
complete -c arara -l safe-run -d 'Run in safe mode and disable potentially harmful features'
complete -c arara -l whole-file -d 'Extract directives in the file, not only in the header'
complete -c arara -l preamble -d 'Set the file preamble as named based on the configuration file'
complete -c arara -l timeout -d 'Sets an execution timeout for spawned processes'
complete -c arara -l language -d 'Set the localization to the language specified by code'
complete -c arara -l max-loops -d 'Set the number > 0 of loops for looping directives'
complete -c arara -l working-directory -d 'Set the working directory for the whole execution'
complete -c arara -l call-property -d 'Pass a property as \\fCkey=value parameter into the application to be used wit…'
complete -c arara -l generate-completion -d 'Generate a completion script for arara'
complete -c arara -l version -d 'Show the version and exit'
complete -c arara -l help -d 'Show a help message and exit'

