# arlatex
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/arlatex.1
complete -c arlatex -l version -d 'X Item "--version" Output the arlatex script\'s version number'
complete -c arlatex -l help -d 'X Item "--help" Output brief arlatex usage information'
complete -c arlatex -l document -d 'X Item "--document=. tex file" Specify the master document'
complete -c arlatex -l outfile

