# autosp
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/autosp.1
complete -c autosp -s l -d '( --log ) option is used, a very detailed log  infile . alog is generated'
complete -c autosp -s d -d '( --dotted ) option is used,  dotted  beam notes of the form \\qb{n}{'

