# autoinst
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/autoinst.1
complete -c autoinst -o help
complete -c autoinst -o dryrun
complete -c autoinst -o verbose
complete -c autoinst -o version
complete -c autoinst -o encoding
complete -c autoinst -o ts1/-nots1
complete -c autoinst -o nots1
complete -c autoinst -o lining/-nolining
complete -c autoinst -o lining
complete -c autoinst -o oldstyle/-nooldstyle
complete -c autoinst -o oldstyle
complete -c autoinst -o proportional/-noproportional
complete -c autoinst -o proportional
complete -c autoinst -o tabular/-notabular
complete -c autoinst -o tabular
complete -c autoinst -o smallcaps/-nosmallcaps
complete -c autoinst -o smallcaps
complete -c autoinst -o swash/-noswash
complete -c autoinst -o titling/-notitling
complete -c autoinst -o superiors/-nosuperiors
complete -c autoinst -o inferiors
complete -c autoinst -o noinferiors -d 'The OpenType standard defines several kinds of digits that might be used as i…'
complete -c autoinst -o fractions/-nofractions
complete -c autoinst -o ligatures/-noligatures
complete -c autoinst -o ornaments/-noornaments
complete -c autoinst -o serif/-sanserif/-typewriter
complete -c autoinst -o math
complete -c autoinst -o mathspacing
complete -c autoinst -o t1suffix
complete -c autoinst -o target
complete -c autoinst -o vendor
complete -c autoinst -o typeface -d 'These options are equivalent to otftotfm\'s  --vendor and  --typeface options:…'
complete -c autoinst -o logfile
complete -c autoinst -o defaultlining/-defaultoldstyle
complete -c autoinst -o defaulttabular/-defaultproportional -d 'Tell autoinst which figure style is the current font family\'s default (i. e'
complete -c autoinst -o nfssweight
complete -c autoinst -o nfsswidth -d 'Map the NFSS code code to the given weight or width, overriding the built-in …'
complete -c autoinst -o extra
complete -c autoinst -o manual
complete -c autoinst -o nofigurekern

