# axohelp
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/axohelp.1
complete -c axohelp -s h -l help -d 'Gives usage information'
complete -c axohelp -s v -l version -d 'Gives version information'
complete -c axohelp -s V -d 'NOT CURRENTLY IMPLEMENTED: Give information on each function used'

