# bat
# Autogenerated from man page /nix/store/7m2i1qi7mm3fdrw38kp8yv2vbvcwjk0g-bat-0.25.0/share/man/man1/bat.1.gz
complete -c bat -l highlight-line -d 'highlights line 40'
complete -c bat -l line-range -d 'prints lines 30 to 40'

