# bbl2bib
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bbl2bib.1
complete -c bbl2bib -s o -d 'X Item "-o output" Output file'
complete -c bbl2bib -s u

