# bbox
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bbox.1
complete -c bbox -s h -l help -d 'Show summary of options'
complete -c bbox -s V -d 'Show version of program'
complete -c bbox -s r -d 'resolution of picture in dpi'

