# bibcop
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bibcop.1
complete -c bibcop -l version -d 'Print the version of the tool'
complete -c bibcop -l help -d 'Print the introduction screen'
complete -c bibcop -l fix -d 'Autho-fix all issues and print a new content to the console'
complete -c bibcop -l latex -d 'Print everything in LaTeX format'
complete -c bibcop -l verbose -d 'Print debugging information too AUTHOR Yegor Bugayenko (yegor256@gmail. com)'

