# bibdoiadd
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bibdoiadd.1
complete -c bibdoiadd -s c -d 'X Item "-c config_file" Configuration file'
complete -c bibdoiadd -s C -d 'X Item "-C 1|0" Whether to canonicalize names in the output (1) or not (0)'
complete -c bibdoiadd -s e -d 'X Item "-e" If 1 (default), add empty doi if a doi cannot be found'
complete -c bibdoiadd -s f -d 'X Item "-f" Force checking doi number even if one is present'
complete -c bibdoiadd -s o

