# bibmradd
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bibmradd.1
complete -c bibmradd -s d -d 'X Item "-d" Debug mode'
complete -c bibmradd -s e -d 'X Item "-e" If 1 (default), add an empty mrnumber if a mr cannot be found'
complete -c bibmradd -s f -d 'X Item "-f" Force searching for MR numbers even if the entry already has one'
complete -c bibmradd -s o

