# bibtex
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bibtex.1
complete -c bibtex -o min-crossrefs -d 'option defines the minimum number of crossref required for automatic inclusio…'
complete -c bibtex -o terse -d 'option,  operates silently'

