# biburl2doi
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/biburl2doi.1
complete -c biburl2doi -s D -d 'X Item "-D" Do not delete URLs converted to DOIs'
complete -c biburl2doi -s o

