# bibzbladd
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bibzbladd.1
complete -c bibzbladd -s d -d 'X Item "-d" Debug mode'
complete -c bibzbladd -s e -d 'X Item "-e" If 1 (default), add an empty zblnumber if a zbl cannot be found'
complete -c bibzbladd -s f -d 'X Item "-f" Force searching for Zbl numbers even if the entry already has one'
complete -c bibzbladd -s o

