# bookshelf-mkfontsel
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bookshelf-mkfontsel.1
complete -c bookshelf-mkfontsel -s v -d 'X Item "-v" Print version information'
complete -c bookshelf-mkfontsel -s h -d 'X Item "-h" Print usage information'
complete -c bookshelf-mkfontsel -s m

