# bookshelf-listallfonts
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bookshelf-listallfonts.1
complete -c bookshelf-listallfonts -s d -d 'X Item "-d" Print debug information on the standard output'
complete -c bookshelf-listallfonts -s f -d 'X Item "-f FEATURES_FILE" Use patterns in the FEATURES file instead of the de…'
complete -c bookshelf-listallfonts -s x -d 'X Item "-x EXCLUDED_PATTERNS_FILE" Exclude patterns (font paths and features …'
complete -c bookshelf-listallfonts -s v -d 'X Item "-v" Print version information'
complete -c bookshelf-listallfonts -s h -d 'X Item "-h" Print usage information'
complete -c bookshelf-listallfonts -s m

