# brightnessctl
# Autogenerated from man page /nix/store/f39yrpxrf7g70xnf5a36clbi73d3vjli-brightnessctl-0.5.1/share/man/man1/brightnessctl.1.gz
complete -c brightnessctl -s h -l help
complete -c brightnessctl -s l -l list
complete -c brightnessctl -s q -l quiet
complete -c brightnessctl -s p -l pretend
complete -c brightnessctl -s m -l machine-readable
complete -c brightnessctl -s n -l min-value
complete -c brightnessctl -s e -l exponent
complete -c brightnessctl -s s -l save
complete -c brightnessctl -s r -l restore
complete -c brightnessctl -s d -l device
complete -c brightnessctl -s c -l class
complete -c brightnessctl -s v -l version

