# bundledoc
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/bundledoc.1
complete -c bundledoc -l version -d 'X Item "--version" Output the bundledoc script\'s version number'
complete -c bundledoc -l help -d 'X Item "--help" Give a brief usage message'
complete -c bundledoc -l verbose -d el
complete -c bundledoc -l texfile -d 'X Item "--texfile=main . tex file (default: somefile'
complete -c bundledoc -l directory -d 'X Item "--directory=archive directory (default: somefile)" When bundledoc cre…'
complete -c bundledoc -l localonly -d el
complete -c bundledoc -l exclude -d 'X Item "--exclude=string (default: none)" While \\f(CW\\*(C`--localonly\\*(C\' ca…'
complete -c bundledoc -l include -d 'X Item "--include=filespec (default: none)" The \\f(CW\\*(C`--include\\*(C\' opti…'
complete -c bundledoc -l manifest -d 'X Item "--manifest=manifest file (default: MANIFEST)" In addition to the depe…'
complete -c bundledoc -l listdeps -d el
complete -c bundledoc -l keepdirs -d el
complete -c bundledoc -l config

