# ccache
# Autogenerated from man page /nix/store/mn1mpssgjlip218gvxx8w4fhgxpmm6l5-ccache-4.11.3-man/share/man/man1/ccache.1.gz
complete -c ccache -s c -l cleanup
complete -c ccache -s C -l clear
complete -c ccache -l config-path
complete -c ccache -s d -l dir
complete -c ccache -l evict-namespace
complete -c ccache -l evict-older-than
complete -c ccache -s h -l help
complete -c ccache -s F -l max-files
complete -c ccache -s M -l max-size
complete -c ccache -s X -l recompress
complete -c ccache -l recompress-threads
complete -c ccache -s o -l set-config
complete -c ccache -s x -l show-compression
complete -c ccache -s p -l show-config
complete -c ccache -l show-log-stats
complete -c ccache -s s -l show-stats
complete -c ccache -s v -l verbose
complete -c ccache -s V -l version
complete -c ccache -s z -l zero-stats
complete -c ccache -l trim-dir
complete -c ccache -l trim-max-size
complete -c ccache -l trim-method
complete -c ccache -l trim-recompress
complete -c ccache -l trim-recompress-threads
complete -c ccache -l checksum-file
complete -c ccache -l extract-result
complete -c ccache -l format
complete -c ccache -s k -l get-config
complete -c ccache -l hash-file
complete -c ccache -l inspect
complete -c ccache -l print-log-stats
complete -c ccache -l print-stats
complete -c ccache -l print-version
complete -c ccache -l ccache-skip -d 'the next option in any way and to pass it along to the compiler as-is.  Note'
complete -c ccache -s 5 -d '0 (default)'
complete -c ccache -o Wdocumentation -d 'log_file (CCACHE_LOGFILE)'
complete -c ccache -l coverage -o fprofile-arcs -d 'included in the input hash.  incbin'
complete -c ccache -o s/--show-stats -d 'limits (in addition to other various statistics)'
complete -c ccache -l 'show-stats”' -d 'oc “Compressed data” refers to result and manifest files stored in the cache'
complete -c ccache -o v/--verbose -d 'T{'
complete -c ccache -o include -s D -d 'change the preprocessor output if they have any effect at all) oc any standar…'
complete -c ccache -o Wp -o 'D<macro' -o Wp -o 'U<macro>' -d 'oc most uses of -Xpreprocessor oc the string __TIME__ is present in the sourc…'
complete -c ccache -o fdebug-compilation-dir -d 'debug info to a common prefix (e. g.  -fdebug-prefix-map=$PWD=.  or'
complete -c ccache -o MMD -o 'D<define>' -d 'oc This was the first compilation with a new value of the base directory'

