# cfftot1
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/cfftot1.1
complete -c cfftot1 -s a -l pfa -d 'Output font in ASCII PFA format.  \' . Sp'
complete -c cfftot1 -s b -l pfb -d 'Output font in binary PFB format.  This is the default.  \' . Sp'
complete -c cfftot1 -s n -l name -d 'Output the CFF\'s component font named R name '
complete -c cfftot1 -s o -l output -d 'Write output font to R file instead of the standard output.  \' . Sp'
complete -c cfftot1 -s q -l quiet -d 'Do not generate any error messages.  \' . Sp'
complete -c cfftot1 -s h -l help -d 'Print usage information and exit.  \' . Sp'
complete -c cfftot1 -s v -l version -d 'Print the version number and some short non-warranty information and exit'

