# chklref
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/chklref.1
complete -c chklref -l tex -s t -d 'Specify the TeX compiler to be used.  Default is `pdflatex`'
complete -c chklref -l tex-options -d 'List of options to pass to the TeX compiler'
complete -c chklref -l debug -s d -d 'Run in debug mode.  Do not clean the generated `. chk` file'
complete -c chklref -l quiet -s q -d 'Run in quiet mode.  Do not print the output of the TeX compiler'
complete -c chklref -l parse-only -d 'Do not run the LaTeX compiler but use the already existing `. chk` file'
complete -c chklref -l version -s v -d 'Print the version of this script'
complete -c chklref -l help -d 'Print this help.  AUTHOR Written by Jerome Lelong <jerome. lelong@gmail'

