# chronic
# Autogenerated from man page /nix/store/8231k60pm54p9inml853jlyxr22g94z0-moreutils-0.70/share/man/man1/chronic.1.gz
complete -c chronic -s v -d 'X Item "-v" Verbose output (distinguishes between STDOUT and STDERR, also rep…'
complete -c chronic -s e

