# citeproc-lua
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/citeproc-lua.1
complete -c citeproc-lua -s h -l help -d 'Prints the usage and exits'
complete -c citeproc-lua -s V -l version -d 'Prints the version number and exits.  AUTHOR Zeping Lee <zepinglee@gmail'

