# cluster
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/cluster.1.gz
complete -c cluster -s C -d 'specifies a targeted number of clusters that should be generated'
complete -c cluster -s c -d 'specifies clustering method'
complete -c cluster -s o -d 'Specifies that output should go into the file outfile'
complete -c cluster -s v -d 'Verbose mode'
complete -c cluster -s '?' -d 'Prints the usage and exits.  EXAMPLES'

