# csvclean
# Autogenerated from man page /nix/store/bj0frlqmi3hb7bmkacaxvd22rcwcdxas-csvkit-2.1.0/share/man/man1/csvclean.1.gz
complete -c csvclean -l header-normalize-space -d 'NOTE: Every csvkit tool does the following:'

