# ctags-lang-i18nrubygem
# Autogenerated from man page /nix/store/0pwh9m33s0qx1a0d5w335lgyr4zavxa9-universal-ctags-6.1.0/share/man/man7/ctags-lang-i18nrubygem.7.gz
complete -c ctags-lang-i18nrubygem -l - -d 'ja:   msg:     error: ã¨ã©ã¼     function: é¢æ° "output'
complete -c ctags-lang-i18nrubygem -l extras-I18nRubyGem
complete -c ctags-lang-i18nrubygem -l kinds-I18nRubyGem

