# ctags-lang-asm
# Autogenerated from man page /nix/store/0pwh9m33s0qx1a0d5w335lgyr4zavxa9-universal-ctags-6.1.0/share/man/man7/ctags-lang-asm.7.gz
complete -c ctags-lang-asm -l list-params -d 'Asm parser.  runCPreProcessor: running C preprocessor'
complete -c ctags-lang-asm -l 'param-Asm.runCPreProcessor'
complete -c ctags-lang-asm -l fields
complete -c ctags-lang-asm -l fields-CPreProcessor -d 'With the above options, the parser expands macros defined in command line wit…'
complete -c ctags-lang-asm -l 'param-Asm.extraLinesepChars' -d 'Known limitations'

