# ctags-incompatibilities
# Autogenerated from man page /nix/store/0pwh9m33s0qx1a0d5w335lgyr4zavxa9-universal-ctags-6.1.0/share/man/man7/ctags-incompatibilities.7.gz
complete -c ctags-incompatibilities -l list-map-extensions -l list-map-patterns -d 'options are helpful to verify and the file extensions and the file name patte…'
complete -c ctags-incompatibilities -l extras -l extras
complete -c ctags-incompatibilities -s f
complete -c ctags-incompatibilities -l file-scope
complete -c ctags-incompatibilities -s F -d 'Incompatibilities in language and kind definitions Language name defined with…'
complete -c ctags-incompatibilities -l 'foo-<LANG>' -l '<LANG>-foo' -d 'options in Exuberant Ctags have the former form, --foo-<LANG>='
complete -c ctags-incompatibilities -l 'regex-<LANG>' -d 'Disallowing to define a kind with \'F\' as letter'
complete -c ctags-incompatibilities -l regex-Foo -d 'Universal Ctags rejects this because the kind name, abstract class, includes …'

