# ctags-client-tools
# Autogenerated from man page /nix/store/0pwh9m33s0qx1a0d5w335lgyr4zavxa9-universal-ctags-6.1.0/share/man/man7/ctags-client-tools.7.gz
complete -c ctags-client-tools -l extras -l extras -d 'Forces writing pseudo-tags'
complete -c ctags-client-tools -l list-pseudo-tags -d 'Lists available types of pseudo-tags and shows whether they are enabled or di…'
complete -c ctags-client-tools -l pseudo-tags
complete -c ctags-client-tools -o ']names' -d 'Specifies a list of pseudo-tag types to include in the output'
complete -c ctags-client-tools -l fields -l fields -d 'Attach "extras:pseudo" field to pseudo-tags'
complete -c ctags-client-tools -l output-format -d 'the tags output format.  See ctags(1) about the option'
complete -c ctags-client-tools -l use-slash-as-filename-separator

