# ctags-faq
# Autogenerated from man page /nix/store/0pwh9m33s0qx1a0d5w335lgyr4zavxa9-universal-ctags-6.1.0/share/man/man7/ctags-faq.7.gz
complete -c ctags-faq -l ---misccomp -d '|       '
complete -c ctags-faq -l ---sysint -d '        -----client         |       -----hdrs         |       -----lib       …'

