# ctags-lang-verilog
# Autogenerated from man page /nix/store/0pwh9m33s0qx1a0d5w335lgyr4zavxa9-universal-ctags-6.1.0/share/man/man7/ctags-lang-verilog.7.gz
complete -c ctags-lang-verilog -l b -d '$ ctags --list-fields=SystemVerilog #LETTER NAME      ENABLED LANGUAGE      J…'
complete -c ctags-lang-verilog -l langmap -d 'KNOWN ISSUES'

