# ctags-optlib
# Autogenerated from man page /nix/store/0pwh9m33s0qx1a0d5w335lgyr4zavxa9-universal-ctags-6.1.0/share/man/man7/ctags-optlib.7.gz
complete -c ctags-optlib -l langdef -d 'Defines a new user-defined language, <name>, to be parsed with regular expres…'
complete -c ctags-optlib -l 'kinddef-<LANG>' -d 'Define a kind for <LANG>.  Be not confused this with --kinds-<LANG>'
complete -c ctags-optlib -l 'regex-<LANG>' -d 'Define a single-line regular expression'
complete -c ctags-optlib -l list-regex-flags -d 'Lists the flags that can be used in --regex-<LANG> option'
complete -c ctags-optlib -l list-mline-regex-flags -d 'Lists the flags that can be used in --mline-regex-<LANG> option'
complete -c ctags-optlib -l 'mline-regex-<LANG>' -d 'Define a multi-line regular expression'
complete -c ctags-optlib -l _echo -d 'Print <message> to the standard error stream'
complete -c ctags-optlib -l _force-quit -d 'Exits immediately when this option is processed'
complete -c ctags-optlib -l 'map-<LANG>' -o ']<extension>' -d 'o 2'
complete -c ctags-optlib -l options -d 'o 2'
complete -c ctags-optlib -l options-maybe -d 'o 2'
complete -c ctags-optlib -l optlib-dir -d 'The design of options and notations for defining a parser in Exuberant Ctags …'
complete -c ctags-optlib -l 'kind-<LANG>' -d 'is used as value in the "kind" extension field in tags output'
complete -c ctags-optlib -l list-kinds-full -d '<description>.  They will be used meta characters in the future'
complete -c ctags-optlib -l list-features -d 'built-with pcre2 or not'
complete -c ctags-optlib -l '_mtable-regex-<LANG>' -d '{postrun} flag because the main part always applies the patterns specified wi…'
complete -c ctags-optlib -l map-pod
complete -c ctags-optlib -l kinddef-pod
complete -c ctags-optlib -l regex-pod
complete -c ctags-optlib -l map-subRuby
complete -c ctags-optlib -l kinddef-subRuby
complete -c ctags-optlib -l regex-subRuby
complete -c ctags-optlib -s o -d 'Example input. srb       /^class Example$/;"     class   end:8 methodA input'
complete -c ctags-optlib -l kinddef-C
complete -c ctags-optlib -l regex-C -d 'With kthread-v1'

