# ctags-lang-julia
# Autogenerated from man page /nix/store/0pwh9m33s0qx1a0d5w335lgyr4zavxa9-universal-ctags-6.1.0/share/man/man7/ctags-lang-julia.7.gz
complete -c ctags-lang-julia -l extras -l extras -d 'since it\'s a reference tag.  This is because module X is not defined here'

