# ctanbib
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ctanbib.1
complete -c ctanbib -s c -l ctan -d 'Always use CTAN /pkg/ url instead of the package homepage'
complete -c ctanbib -s C -l CTAN -d 'Use the package\'s CTAN path as url (e. g. : /support/ctanbib)'
complete -c ctanbib -s e -l entrytype -d '(default manual)  Change entry type'
complete -c ctanbib -s h -l help -d 'print the help message'
complete -c ctanbib -s p -l pkgname -d 'Wrap the package name in a \\ctanbibpkgname command This command can be redefi…'
complete -c ctanbib -s v -l version -d 'print the version info.  EXAMPLES'

