# ctie
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ctie.1
complete -c ctie -s c -d 'Create a single change file from the given R changefile s'
complete -c ctie -s m -d 'Create a new master file by applying the given changefile s'

