# ctwill
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ctwill.1
complete -c ctwill -l version -s i
complete -c ctwill -s o -d '[bu] 2 Option +lX is accompanied by example wrapper files for ctwimac'
complete -c ctwill -l verbose -d '[bu] 2 File lookup with the environment variable CWEBINPUTS is extended to pe…'
complete -c ctwill -l quiet -d '[bu] 2 +v/-v: shortcut for +bhp; also'
complete -c ctwill -s e -d '[rs]PB{. } [bu] 2'
complete -c ctwill -s f -d 'output [bu] 2'
complete -c ctwill -s F -d '[bu] 2'
complete -c ctwill -s x -d '[bu] 2 +P: [rs]input ctproofmac. tex instead of ctwimac'
complete -c ctwill -l help -d '[bu] 2'

