# cweb
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/cweb.1
complete -c cweb -l version -s i
complete -c cweb -s o -d 'TeX Live'
complete -c cweb -l verbose -d '[bu] 2 File lookup with the environment variable CWEBINPUTS is extended to pe…'
complete -c cweb -l quiet -d '[bu] 2 +v/-v: shortcut for +bhp; also'
complete -c cweb -l help -d '[bu] 2'
complete -c cweb -s e -d '[rs]PB{. } [bu] 2'
complete -c cweb -s f -d 'output [bu] 2'
complete -c cweb -s F -d '[bu] 2'
complete -c cweb -s x -d '[bu] 2 +lX/-lX: use macros for language X as of Xcwebmac'

