# debuginfod_find_debuginfo
# Autogenerated from man page /nix/store/wgmzshr7sndlnplqh1a5mgfmqa2nc1vp-elfutils-0.192-man/share/man/man3/debuginfod_find_debuginfo.3.gz
complete -c debuginfod_find_debuginfo -o EINVAL

