# debuginfod-find
# Autogenerated from man page /nix/store/wgmzshr7sndlnplqh1a5mgfmqa2nc1vp-elfutils-0.192-man/share/man/man1/debuginfod-find.1.gz
complete -c debuginfod-find -s v -d 'Increase verbosity, including printing frequent download-progress messages an…'

