# desktop-file-validate
# Autogenerated from man page /nix/store/ifwfpfz7859qpszrw94vg7v1cm7x3i57-desktop-file-utils-0.28/share/man/man1/desktop-file-validate.1.gz
complete -c desktop-file-validate -l no-hints -d 'Do not output hints about things that might be improved in the desktop file'
complete -c desktop-file-validate -l no-warn-deprecated -d 'Do not warn about usage of deprecated items that were defined in previous ver…'
complete -c desktop-file-validate -l warn-kde -d 'Warn about usage of KDE extensions to the specification'

