# devnag
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/devnag.1
complete -c devnag -s v -d 'report devnag version AUTHORS devnag was written by Frans J'

