# disdvi
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/disdvi.1
complete -c disdvi -s p -d 'Handle ASCII pTeX dvi file'
complete -c disdvi -s u -d 'Handle upTeX dvi file'
complete -c disdvi -o Eenc -d 'Set output multibyte encoding'
complete -c disdvi -s x -d 'Handle XeTeX xdv file'
complete -c disdvi -s h -d 'Show a help massage and exit successfully'

