# dot2gxl
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/dot2gxl.1.gz
complete -c dot2gxl -s g -d 'The command name and input file extensions are ignored, the input is taken as…'
complete -c dot2gxl -s d -d 'The command name and input file extensions are ignored, the input is taken as…'
complete -c dot2gxl -s '?' -d 'Prints usage information and exits'
complete -c dot2gxl -s o -d 'If specified, the output will be written into the file outfile'

