# dot_sandbox
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/dot_sandbox.1.gz
complete -c dot_sandbox -s O -d 'stdout and pipe the output to their desired file'

