# dt2dv
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dt2dv.1
complete -c dt2dv -o group -d 'Expect each DTL command to be in parentheses'
complete -c dt2dv -o si -d 'Read all DTL commands from standard input'
complete -c dt2dv -o debug -d 'Turn on detailed debugging output'
complete -c dt2dv -o so -d 'Write all DVI commands to standard output'

