# dvi2fax
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dvi2fax.1
complete -c dvi2fax -o hi -d 'use high fax resolution (204x196 dpi) (default)'
complete -c dvi2fax -o lo -d 'use low fax resolution (204x98)'

