# dviasm
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dviasm.1
complete -c dviasm -l version -d 'Show program\'s version number and exit'
complete -c dviasm -s h -l help -d 'Show this help message and exit'
complete -c dviasm -s u -l unit -d 'Set unit [default: `pt\']'
complete -c dviasm -s o -l output -d 'Set filename for output instead of stdout'
complete -c dviasm -s e -l encoding -d 'Set encoding for input/output of dumped text [default: `utf8\']'
complete -c dviasm -s x -l xxx-encoding -d 'Set encoding for interpreting `xxx:\' strings [default: `none\']'
complete -c dviasm -s t -l tabsize -d 'Set tab size for push/pop [default: 2]'
complete -c dviasm -s p -l ptex -d 'Dump and compile ISO-2022-JP-encoded DVI for Japanese pTeX'
complete -c dviasm -s s -l subfont -d 'Specify the list of fonts with UCS2 subfont scheme in the comma-separated for…'

