# dvibook
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dvibook.1
complete -c dvibook -s s -d 'option selects the size of signature which will be used'
complete -c dvibook -s r -d 'option switches to right-hand side binding signatures'
complete -c dvibook -s q -d 'option suppresses this'

