# dvicopy
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dvicopy.1
complete -c dvicopy -o magnification -d 'Override existing magnification with R NUMBER . PP'
complete -c dvicopy -o max-pages -d 'Process  NUMBER pages; default one million. PP'
complete -c dvicopy -o page-start -d 'Start at PAGE-SPEC , for example `2\' or `5. *. -2\''

