# dvidvi
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dvidvi.1
complete -c dvidvi -s f
complete -c dvidvi -s l
complete -c dvidvi -s n -d 'selected, independently of the number of pages actually contained in a sheet'
complete -c dvidvi -s i
complete -c dvidvi -s x
complete -c dvidvi -s q -d 'messages of how the work is being done'
complete -c dvidvi -s r
complete -c dvidvi -s m -d 'page number are defaulted'

