# dvired
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dvired.1
complete -c dvired -s o
complete -c dvired -s P
complete -c dvired -s f

