# dvitomp
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dvitomp.1
complete -c dvitomp -o help -d 'write usage summary and exit'
complete -c dvitomp -o version -d 'output version information and exit'

