# dvitodvi
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/dvitodvi.1
complete -c dvitodvi -s w -d 'option gives the width which is used by the w dimension specifier, and the'
complete -c dvitodvi -s h -d 'option gives the height which is used by the h dimension specifier'
complete -c dvitodvi -s q -d 'option suppresses this'

