# edtx2dtx
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/edtx2dtx.1
complete -c edtx2dtx -l 'comment\\f' -d 'The input comment character; the default is \\f[CR]%\\f[R]'
complete -c edtx2dtx -l 'end-macrocode\\f' -d 'Use these options to change the default \\f[I]input\\f[R] \\f[CR]\\[rs]begin{macr…'
complete -c edtx2dtx -l 'End-macrocode\\f' -d 'As \\f[CR]-b\\f[R] and \\f[CR]-e\\f[R], but the input markers are kept in the out…'
complete -c edtx2dtx -l 'strip-empty\\f' -d 'If this option is given, empty lines are not included in the output'
complete -c edtx2dtx -l 'help\\f' -d 'Show help and exit'
complete -c edtx2dtx -s c -l comment -d 'The input comment character; the default is %'
complete -c edtx2dtx -s b -l begin-macrocode
complete -c edtx2dtx -s e -l end-macrocode -d 'Use these options to change the default input [rs]begin{macrocode} and [rs]en…'
complete -c edtx2dtx -s B -l Begin-macrocode
complete -c edtx2dtx -s E -l End-macrocode -d 'As -b and -e, but the input markers are kept in the output'
complete -c edtx2dtx -s s -l strip-empty -d 'If this option is given, empty lines are not included in the output'
complete -c edtx2dtx -s h -l help -d 'Show help and exit'
complete -c edtx2dtx -s V -l version -d 'Show the version number and exit.  EXAMPLES If input'

