# eolang
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/eolang.1
complete -c eolang -l version -d 'Print the version of the tool'
complete -c eolang -l help -d 'Print the introduction screen'
complete -c eolang -l verbose -d 'Print debugging information too AUTHOR Yegor Bugayenko (yegor256@gmail. com)'

