# epsffit
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/epsffit.1
complete -c epsffit -s c -d 'Center the image in the given bounding box'
complete -c epsffit -s r -d 'Rotate the image by 90 degrees counter-clockwise'
complete -c epsffit -s a -d 'Adjust the aspect ratio to fit the bounding box'
complete -c epsffit -s m -d 'Rotates the image to maximise the size if it would fit the specified bounding…'
complete -c epsffit -s s -d 'Add a showpage at the end of the file to force the image to print'

