# extractbb
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/extractbb.1
complete -c extractbb -s v -d 'Be verbose'
complete -c extractbb -s q -d 'Be quiet'
complete -c extractbb -s O -d 'Write output to standard output'
complete -c extractbb -s m -d 'Write output in dvipdfm\'s ``bb\'\' format'

