# extractres
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/extractres.1
complete -c extractres -s m -d 'option combines the resources of the same name into one file; this must be us…'

