# fatrace
# Autogenerated from man page /nix/store/qhrk6g9m3rk7jda8wfgkbg2lkcfw9yzj-fatrace-0.18.0/share/man/man8/fatrace.8.gz
complete -c fatrace -s c -l current-mount -d 'Only record events on partition/mount of current directory'
complete -c fatrace -s o -l output -d 'Write events to given file instead of standard output'
complete -c fatrace -s s -l seconds -d 'Stop after the given number of seconds'
complete -c fatrace -s t -l timestamp -d 'Add timestamp to events'
complete -c fatrace -s u -l user -d 'Add process user information to events, formatted as "[uid:gid]"'
complete -c fatrace -s p -l ignore-pid -d 'Ignore events for this process ID.  Can be specified multiple times'
complete -c fatrace -s f -l filter -d 'Show only the given event types'
complete -c fatrace -s C -l command -d 'Show only events for this command'
complete -c fatrace -s h -l help -d 'Print help and exit'

