# fc-cat
# Autogenerated from man page /nix/store/2c93al6lm3p5xhnc5dy9jjlz3rwv07p2-fontconfig-2.16.0-bin/share/man/man1/fc-cat.1.gz
complete -c fc-cat -s r -d 'Recurse into subdirectories'
complete -c fc-cat -s v -d 'Be verbose'
complete -c fc-cat -s h -d 'Show summary of options'

