# fc-list
# Autogenerated from man page /nix/store/2c93al6lm3p5xhnc5dy9jjlz3rwv07p2-fontconfig-2.16.0-bin/share/man/man1/fc-list.1.gz
complete -c fc-list -s v -d 'Print verbose output of the whole font pattern for each match, or elements if…'
complete -c fc-list -s f -d 'Format output according to the format specifier format'
complete -c fc-list -s q -d 'Suppress all normal output.  returns 1 as the error code if no fonts matched'
complete -c fc-list -s V -d 'Show version of the program and exit'
complete -c fc-list -s h -d 'Show summary of options'

