# fc-match
# Autogenerated from man page /nix/store/2c93al6lm3p5xhnc5dy9jjlz3rwv07p2-fontconfig-2.16.0-bin/share/man/man1/fc-match.1.gz
complete -c fc-match -s a -d 'Displays sorted list of best matching fonts, but do not do any pruning on the…'
complete -c fc-match -s s -d 'Displays sorted list of best matching fonts'
complete -c fc-match -s v -d 'Print verbose output of the whole font pattern for each match, or elements if…'
complete -c fc-match -s f -d 'Format output according to the format specifier format'
complete -c fc-match -s V -d 'Show version of the program and exit'
complete -c fc-match -s h -d 'Show summary of options'

