# fc-pattern
# Autogenerated from man page /nix/store/2c93al6lm3p5xhnc5dy9jjlz3rwv07p2-fontconfig-2.16.0-bin/share/man/man1/fc-pattern.1.gz
complete -c fc-pattern -s c -d 'Perform config substitution on pattern'
complete -c fc-pattern -s d -d 'Perform default substitution on pattern'
complete -c fc-pattern -s f -d 'Format output according to the format specifier format'
complete -c fc-pattern -s V -d 'Show version of the program and exit'
complete -c fc-pattern -s h -d 'Show summary of options'

