# fc-scan
# Autogenerated from man page /nix/store/2c93al6lm3p5xhnc5dy9jjlz3rwv07p2-fontconfig-2.16.0-bin/share/man/man1/fc-scan.1.gz
complete -c fc-scan -s f -d 'Format output according to the format specifier format'
complete -c fc-scan -s V -d 'Show version of the program and exit'
complete -c fc-scan -s h -d 'Show summary of options'

