# findhyph
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/findhyph.1
complete -c findhyph -s c -d 'display hyphenated words in context'
complete -c findhyph -s f -d 'display font selectors and other strings starting with a backslash character'
complete -c findhyph -s v -d 'display program version'
complete -c findhyph -s p -d 'generate file containing information about one-letter prepositions and  conju…'

