# fmtutil.cnf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man5/fmtutil.cnf.5
complete -c 'fmtutil.cnf' -l showhyphen -l byhyphen -d 'If the format has no way to customize hyphenation, a ``-\'\' can be used to ind…'

