# fonts-conf
# Autogenerated from man page /nix/store/2c93al6lm3p5xhnc5dy9jjlz3rwv07p2-fontconfig-2.16.0-bin/share/man/man5/fonts-conf.5.gz
complete -c fonts-conf -l ------------------------------------------------------------ -d 'family          String  Font family names familylang      String  Languages c…'
complete -c fonts-conf -l -------------------------------------------------------- -d 'Times-12                        12 point Times Roman Times-12:bold           …'
complete -c fonts-conf -l ------------------------------------------------------- -d 'MATCH            1    Brief information about font matching MATCHV           …'
complete -c fonts-conf -l ------------------------------------------------------------------- -d '"assign"                Replace matching value  Replace all values "assign_re…'
complete -c fonts-conf -l ----------------------------------- -d 'thin            weight          0 extralight      weight          40 ultralig…'
complete -c fonts-conf -l '>' -d '<fontconfig>'

