# fusermount
# Autogenerated from man page /nix/store/7jd09nsj0jp9lh8zsnfb2jj9fzkh8nfg-fuse-2.9.9-man/share/man/man1/fusermount.1.gz
complete -c fusermount -s h -d 'print help'
complete -c fusermount -s V -d 'print version'
complete -c fusermount -s o -d 'mount options'
complete -c fusermount -s u -d unmount
complete -c fusermount -s q -d quiet
complete -c fusermount -s z -d 'lazy unmount'

