# gcore
# Autogenerated from man page /nix/store/v2gw1fvvp3fpsvdj04s363zb36hs411k-gdb-16.2/share/man/man1/gcore.1.gz
complete -c gcore -s a -d 'X Item "-a" Dump all memory mappings'
complete -c gcore -s o -d 'X Item "-o prefix" The optional argument prefix specifies the prefix to be us…'
complete -c gcore -s d

