# gdb-add-index
# Autogenerated from man page /nix/store/v2gw1fvvp3fpsvdj04s363zb36hs411k-gdb-16.2/share/man/man1/gdb-add-index.1.gz
complete -c gdb-add-index -s f -s n -d OPTIONS
complete -c gdb-add-index -o dwarf-5

