# gdbserver
# Autogenerated from man page /nix/store/v2gw1fvvp3fpsvdj04s363zb36hs411k-gdb-16.2/share/man/man1/gdbserver.1.gz
complete -c gdbserver -l help -d 'X Item "--help" List all options, with brief explanations'
complete -c gdbserver -l version -d 'X Item "--version" This option causes gdbserver to print its version number a…'
complete -c gdbserver -l attach -d 'X Item "--attach" gdbserver will attach to a running program'
complete -c gdbserver -l multi -d 'X Item "--multi" To start \\f(CW\\*(C`gdbserver\\*(C\' without supplying an initi…'
complete -c gdbserver -l debug -d 'X Item "--debug[=option1,option2,'
complete -c gdbserver -l debug-file -d 'X Item "--debug-file=filename" Instruct \\f(CW\\*(C`gdbserver\\*(C\' to send any …'
complete -c gdbserver -l debug-format -d 'X Item "--debug-format=option1[,option2,'
complete -c gdbserver -l wrapper -d 'X Item "--wrapper" Specify a wrapper to launch programs for debugging'
complete -c gdbserver -l baud -d 'That is gdb TARGET-PROG\\fR, or gdb --baud BAUD TARGET-PROG\\fR'
complete -c gdbserver -s f -s n -d 'In such case use the extended-remote\\fR GDB command variant:         (gdb) ta…'
complete -c gdbserver -l once

