# gftopk
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/gftopk.1
complete -c gftopk -s v -d 'switch is given, gftopk operates silently.   With'

