# gftodvi
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/gftodvi.1
complete -c gftodvi -o overflow-label-offset -d 'specifies the distance from the right edge of the character bounding box at w…'
complete -c gftodvi -o verbose -d 'option, gftodvi operates silently'

