# gftype
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/gftype.1
complete -c gftype -s i -d 'is given on the command line, and a symbolic listing of the gf commands, if'
complete -c gftype -s m -d 'is specified'

