# gh-auth-switch
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-auth-switch.1.gz
complete -c gh-auth-switch -s h -l hostname -d 'The hostname of the GitHub instance to switch account for'
complete -c gh-auth-switch -s u -l user -d 'The account to switch to EXIT CODES 0: Successful execution 1: Error 2: Comma…'

