# gh-attestation-trusted-root
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-attestation-trusted-root.1.gz
complete -c gh-attestation-trusted-root -l hostname -d 'Configure host to use'
complete -c gh-attestation-trusted-root -l tuf-root -d 'Path to the TUF root. json file on disk'
complete -c gh-attestation-trusted-root -l tuf-url -d 'URL to the TUF repository mirror'
complete -c gh-attestation-trusted-root -l verify-only -d 'Don\'t output trusted_root'

