# gh-attestation-download
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-attestation-download.1.gz
complete -c gh-attestation-download -s d -l digest-alg -d 'The algorithm used to compute a digest of the artifact: {sha256|sha512}'
complete -c gh-attestation-download -l hostname -d 'Configure host to use'
complete -c gh-attestation-download -s L -l limit -d 'Maximum number of attestations to fetch'
complete -c gh-attestation-download -s o -l owner -d 'GitHub organization to scope attestation lookup by'
complete -c gh-attestation-download -l predicate-type -d 'Filter attestations by provided predicate type'
complete -c gh-attestation-download -s R -l repo -d 'Repository name in the format / EXIT CODES 0: Successful execution 1: Error 2…'

