# gh-auth-status
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-auth-status.1.gz
complete -c gh-auth-status -s a -l active -d 'Display the active account only'
complete -c gh-auth-status -s h -l hostname -d 'Check only a specific hostname\'s auth status'
complete -c gh-auth-status -s t -l show-token -d 'Display the auth token EXIT CODES 0: Successful execution 1: Error 2: Command…'

