# gh-auth-token
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-auth-token.1.gz
complete -c gh-auth-token -s h -l hostname -d 'The hostname of the GitHub instance authenticated with'
complete -c gh-auth-token -s u -l user -d 'The account to output the token for EXIT CODES 0: Successful execution 1: Err…'

