# gh-auth-setup-git
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-auth-setup-git.1.gz
complete -c gh-auth-setup-git -s f -l force -d 'Force setup even if the host is not known'
complete -c gh-auth-setup-git -s h -l hostname -d 'The hostname to configure git for EXIT CODES 0: Successful execution 1: Error…'

