# gh-alias-set
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-alias-set.1.gz
complete -c gh-alias-set -l clobber -d 'Overwrite existing aliases of the same name'
complete -c gh-alias-set -s s -l shell -d 'Declare an alias to be passed through a shell interpreter EXIT CODES 0: Succe…'

