# gh-alias-import
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-alias-import.1.gz
complete -c gh-alias-import -l clobber -d 'Overwrite existing aliases of the same name EXIT CODES 0: Successful executio…'

