# gh-cache-delete
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-cache-delete.1.gz
complete -c gh-cache-delete -s a -l all -d 'Delete all caches'
complete -c gh-cache-delete -l succeed-on-no-caches -d 'Return exit code 0 if no caches found'
complete -c gh-cache-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

