# gh-completion
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-completion.1.gz
complete -c gh-completion -s s -l shell -d 'Shell type: {bash|zsh|fish|powershell} EXIT CODES 0: Successful execution 1: …'

