# gh-config-list
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-config-list.1.gz
complete -c gh-config-list -s h -l host -d 'Get per-host configuration ALIASES gh config ls EXIT CODES 0: Successful exec…'

