# gh-config-get
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-config-get.1.gz
complete -c gh-config-get -s h -l host -d 'Get per-host setting EXIT CODES 0: Successful execution 1: Error 2: Command c…'

