# gh-codespace-logs
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-codespace-logs.1.gz
complete -c gh-codespace-logs -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-logs -s f -l follow -d 'Tail and follow the logs'
complete -c gh-codespace-logs -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-logs -l repo-owner -d 'Filter codespace selection by repository owner (username or org) EXIT CODES 0…'

