# gh-codespace-view
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-codespace-view.1.gz
complete -c gh-codespace-view -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-view -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-codespace-view -l json -d 'Output JSON with the specified fields'
complete -c gh-codespace-view -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-view -l repo-owner -d 'Filter codespace selection by repository owner (username or org)'
complete -c gh-codespace-view -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" JSON FIELDS …'

