# gh-extension-upgrade
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-extension-upgrade.1.gz
complete -c gh-extension-upgrade -l all -d 'Upgrade all extensions'
complete -c gh-extension-upgrade -l dry-run -d 'Only display upgrades'
complete -c gh-extension-upgrade -l force -d 'Force upgrade extension EXIT CODES 0: Successful execution 1: Error 2: Comman…'

