# gh-extension-install
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-extension-install.1.gz
complete -c gh-extension-install -l force -d 'Force upgrade extension, or ignore if latest already installed'
complete -c gh-extension-install -l pin -d 'Pin extension to a release tag or commit ref EXIT CODES 0: Successful executi…'

