# gh-extension-browse
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-extension-browse.1.gz
complete -c gh-extension-browse -l debug -d 'Log to /tmp/extBrowse-*'
complete -c gh-extension-browse -s s -l single-column -d 'Render TUI with only one column of text EXIT CODES 0: Successful execution 1:…'

