# gh-extension-create
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-extension-create.1.gz
complete -c gh-extension-create -l precompiled -d 'Create a precompiled extension'

