# gh-gist-edit
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-gist-edit.1.gz
complete -c gh-gist-edit -s a -l add -d 'Add a new file to the gist'
complete -c gh-gist-edit -s d -l desc -d 'New description for the gist'
complete -c gh-gist-edit -s f -l filename -d 'Select a file to edit'
complete -c gh-gist-edit -s r -l remove -d 'Remove a file from the gist EXIT CODES 0: Successful execution 1: Error 2: Co…'

