# gh-gist-delete
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-gist-delete.1.gz
complete -c gh-gist-delete -l yes -d 'Confirm deletion without prompting EXIT CODES 0: Successful execution 1: Erro…'

