# gh-gpg-key-add
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-gpg-key-add.1.gz
complete -c gh-gpg-key-add -s t -l title -d 'Title for the new key EXIT CODES 0: Successful execution 1: Error 2: Command …'

