# gh-gist-list
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-gist-list.1.gz
complete -c gh-gist-list -l filter -d 'Filter gists using a regular expression'
complete -c gh-gist-list -l include-content -d 'Include gists\' file content when filtering'
complete -c gh-gist-list -s L -l limit -d 'Maximum number of gists to fetch'
complete -c gh-gist-list -l public -d 'Show only public gists'
complete -c gh-gist-list -l secret -d 'Show only secret gists ALIASES gh gist ls EXIT CODES 0: Successful execution …'

