# gh-gpg-key-delete
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-gpg-key-delete.1.gz
complete -c gh-gpg-key-delete -s y -l yes -d 'Skip the confirmation prompt EXIT CODES 0: Successful execution 1: Error 2: C…'

