# gh-gist-create
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-gist-create.1.gz
complete -c gh-gist-create -s d -l desc -d 'A description for this gist'
complete -c gh-gist-create -s f -l filename -d 'Provide a filename to be used when reading from standard input'
complete -c gh-gist-create -s p -l public -d 'List the gist publicly (default "secret")'
complete -c gh-gist-create -s w -l web -d 'Open the web browser with created gist ALIASES gh gist new EXIT CODES 0: Succ…'

