# gh-gist-view
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-gist-view.1.gz
complete -c gh-gist-view -s f -l filename -d 'Display a single file from the gist'
complete -c gh-gist-view -l files -d 'List file names from the gist'
complete -c gh-gist-view -s r -l raw -d 'Print raw instead of rendered gist contents'
complete -c gh-gist-view -s w -l web -d 'Open gist in the browser EXIT CODES 0: Successful execution 1: Error 2: Comma…'

