# gh-issue-view
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-issue-view.1.gz
complete -c gh-issue-view -s c -l comments -d 'View issue comments'
complete -c gh-issue-view -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-issue-view -l json -d 'Output JSON with the specified fields'
complete -c gh-issue-view -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-issue-view -s w -l web -d 'Open an issue in the browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-view -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format JSON FIELDS assi…'

