# gh-issue-develop
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-issue-develop.1.gz
complete -c gh-issue-develop -s b -l base -d 'Name of the remote branch you want to make your new branch from'
complete -c gh-issue-develop -l branch-repo -d 'Name or URL of the repository where you want to create your new branch'
complete -c gh-issue-develop -s c -l checkout -d 'Checkout the branch after creating it'
complete -c gh-issue-develop -s l -l list -d 'List linked branches for the issue'
complete -c gh-issue-develop -s n -l name -d 'Name of the branch to create OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-develop -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

