# gh-issue-close
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-issue-close.1.gz
complete -c gh-issue-close -s c -l comment -d 'Leave a closing comment'
complete -c gh-issue-close -s r -l reason -d 'Reason for closing: {completed|not planned} OPTIONS INHERITED FROM PARENT COM…'
complete -c gh-issue-close -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

