# gh-label-delete
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-label-delete.1.gz
complete -c gh-label-delete -l yes -d 'Confirm deletion without prompting OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-label-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

