# gh-label-clone
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-label-clone.1.gz
complete -c gh-label-clone -s f -l force -d 'Overwrite labels in the destination repository OPTIONS INHERITED FROM PARENT …'
complete -c gh-label-clone -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

