# gh-org-list
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-org-list.1.gz
complete -c gh-org-list -s L -l limit -d 'Maximum number of organizations to list ALIASES gh org ls EXIT CODES 0: Succe…'

