# gh-pr-ready
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-pr-ready.1.gz
complete -c gh-pr-ready -l undo -d 'Convert a pull request to "draft" OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-ready -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

