# gh-project-item-add
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-project-item-add.1.gz
complete -c gh-project-item-add -l format -d 'Output format: {json}'
complete -c gh-project-item-add -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-item-add -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-item-add -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-item-add -l url -d 'URL of the issue or pull request to add to the project EXIT CODES 0: Successf…'

