# gh-project-link
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-project-link.1.gz
complete -c gh-project-link -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-link -s R -l repo -d 'The repository to be linked to this project'
complete -c gh-project-link -s T -l team -d 'The team to be linked to this project EXIT CODES 0: Successful execution 1: E…'

