# gh-pr-reopen
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-pr-reopen.1.gz
complete -c gh-pr-reopen -s c -l comment -d 'Add a reopening comment OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-reopen -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

