# gh-pr-update-branch
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-pr-update-branch.1.gz
complete -c gh-pr-update-branch -l rebase -d 'Update PR branch by rebasing on top of latest base branch OPTIONS INHERITED F…'
complete -c gh-pr-update-branch -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

