# gh-pr-checkout
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-pr-checkout.1.gz
complete -c gh-pr-checkout -s b -l branch -d 'Local branch name to use (default [the name of the head branch])'
complete -c gh-pr-checkout -l detach -d 'Checkout PR with a detached HEAD'
complete -c gh-pr-checkout -s f -l force -d 'Reset the existing local branch to the latest state of the pull request'
complete -c gh-pr-checkout -l recurse-submodules -d 'Update all submodules after checkout OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-checkout -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

