# gh-project-view
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-project-view.1.gz
complete -c gh-project-view -l format -d 'Output format: {json}'
complete -c gh-project-view -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-view -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-view -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-view -s w -l web -d 'Open a project in the browser EXIT CODES 0: Successful execution 1: Error 2: …'

