# gh-project-unlink
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-project-unlink.1.gz
complete -c gh-project-unlink -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-unlink -s R -l repo -d 'The repository to be unlinked from this project'
complete -c gh-project-unlink -s T -l team -d 'The team to be unlinked from this project EXIT CODES 0: Successful execution …'

