# gh-project-field-delete
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-project-field-delete.1.gz
complete -c gh-project-field-delete -l format -d 'Output format: {json}'
complete -c gh-project-field-delete -l id -d 'ID of the field to delete'
complete -c gh-project-field-delete -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-field-delete -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" EXIT CODES 0…'

