# gh-project-field-list
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-project-field-list.1.gz
complete -c gh-project-field-list -l format -d 'Output format: {json}'
complete -c gh-project-field-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-field-list -s L -l limit -d 'Maximum number of fields to fetch'
complete -c gh-project-field-list -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-field-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" EXIT CODES 0…'

