# gh-project-list
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-project-list.1.gz
complete -c gh-project-list -l closed -d 'Include closed projects'
complete -c gh-project-list -l format -d 'Output format: {json}'
complete -c gh-project-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-list -s L -l limit -d 'Maximum number of projects to fetch'
complete -c gh-project-list -l owner -d 'Login of the owner'
complete -c gh-project-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-list -s w -l web -d 'Open projects list in the browser ALIASES gh project ls EXIT CODES 0: Success…'

