# gh-repo-autolink-view
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-repo-autolink-view.1.gz
complete -c gh-repo-autolink-view -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-repo-autolink-view -l json -d 'Output JSON with the specified fields'
complete -c gh-repo-autolink-view -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" OPTIONS INHE…'
complete -c gh-repo-autolink-view -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format JSON FIELDS id, …'

