# gh-ruleset
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-ruleset.1.gz
complete -c gh-ruleset -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh rs EX…'

