# gh-repo-clone
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-repo-clone.1.gz
complete -c gh-repo-clone -s u -l upstream-remote-name -d 'Upstream remote name when cloning a fork EXIT CODES 0: Successful execution 1…'

