# gh-run-rerun
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-run-rerun.1.gz
complete -c gh-run-rerun -s d -l debug -d 'Rerun with debug logging'
complete -c gh-run-rerun -l failed -d 'Rerun only failed jobs, including dependencies'
complete -c gh-run-rerun -s j -l job -d 'Rerun a specific job ID from a run, including dependencies OPTIONS INHERITED …'
complete -c gh-run-rerun -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

