# gh-run-watch
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-run-watch.1.gz
complete -c gh-run-watch -l exit-status -d 'Exit with non-zero status if run fails'
complete -c gh-run-watch -s i -l interval -d 'Refresh interval in seconds OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-run-watch -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

