# gh-ruleset-check
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-ruleset-check.1.gz
complete -c gh-ruleset-check -l default -d 'Check rules on default branch'
complete -c gh-ruleset-check -s w -l web -d 'Open the branch rules page in a web browser OPTIONS INHERITED FROM PARENT COM…'
complete -c gh-ruleset-check -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

