# gh-repo-license-view
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-repo-license-view.1.gz
complete -c gh-repo-license-view -s w -l web -d 'Open https://choosealicense'

