# gh-repo-view
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-repo-view.1.gz
complete -c gh-repo-view -s b -l branch -d 'View a specific branch of the repository'
complete -c gh-repo-view -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-repo-view -l json -d 'Output JSON with the specified fields'
complete -c gh-repo-view -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-repo-view -s w -l web -d 'Open a repository in the browser JSON FIELDS archivedAt, assignableUsers, cod…'

