# gh-repo-autolink-create
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-repo-autolink-create.1.gz
complete -c gh-repo-autolink-create -s n -l numeric -d 'Mark autolink as numeric OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-repo-autolink-create -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh repo …'

