# gh-ruleset-view
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-ruleset-view.1.gz
complete -c gh-ruleset-view -s o -l org -d 'Organization name if the provided ID is an organization-level ruleset'
complete -c gh-ruleset-view -s p -l parents -d 'Whether to include rulesets configured at higher levels that also apply'
complete -c gh-ruleset-view -s w -l web -d 'Open the ruleset in the browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-ruleset-view -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

