# gh-repo-set-default
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-repo-set-default.1.gz
complete -c gh-repo-set-default -s u -l unset -d 'Unset the current default repository'
complete -c gh-repo-set-default -s v -l view -d 'View the current default repository EXIT CODES 0: Successful execution 1: Err…'

