# gh-repo-autolink-list
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-repo-autolink-list.1.gz
complete -c gh-repo-autolink-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-repo-autolink-list -l json -d 'Output JSON with the specified fields'
complete -c gh-repo-autolink-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-repo-autolink-list -s w -l web -d 'List autolink references in the web browser OPTIONS INHERITED FROM PARENT COM…'
complete -c gh-repo-autolink-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh repo …'

