# gh-repo-fork
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-repo-fork.1.gz
complete -c gh-repo-fork -l clone -d 'Clone the fork'
complete -c gh-repo-fork -l default-branch-only -d 'Only include the default branch in the fork'
complete -c gh-repo-fork -l fork-name -d 'Rename the forked repository'
complete -c gh-repo-fork -l org -d 'Create the fork in an organization'
complete -c gh-repo-fork -l remote -d 'Add a git remote for the fork'
complete -c gh-repo-fork -l remote-name -d 'Specify the name for the new remote EXIT CODES 0: Successful execution 1: Err…'

