# gh-ssh-key-add
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-ssh-key-add.1.gz
complete -c gh-ssh-key-add -s t -l title -d 'Title for the new key'
complete -c gh-ssh-key-add -l type -d 'Type of the ssh key: {authentication|signing} EXIT CODES 0: Successful execut…'

