# gh-status
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-status.1.gz
complete -c gh-status -s e -l exclude -d 'Comma separated list of repos to exclude in owner/name format'
complete -c gh-status -s o -l org -d 'Report status within an organization EXIT CODES 0: Successful execution 1: Er…'

