# gh-variable-get
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-variable-get.1.gz
complete -c gh-variable-get -s e -l env -d 'Get a variable for an environment'
complete -c gh-variable-get -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-variable-get -l json -d 'Output JSON with the specified fields'
complete -c gh-variable-get -s o -l org -d 'Get a variable for an organization'
complete -c gh-variable-get -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" OPTIONS INHE…'
complete -c gh-variable-get -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format JSON FIELDS crea…'

