# gh-variable-list
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-variable-list.1.gz
complete -c gh-variable-list -s e -l env -d 'List variables for an environment'
complete -c gh-variable-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-variable-list -l json -d 'Output JSON with the specified fields'
complete -c gh-variable-list -s o -l org -d 'List variables for an organization'
complete -c gh-variable-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" OPTIONS INHE…'
complete -c gh-variable-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh varia…'

