# gh-variable-delete
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-variable-delete.1.gz
complete -c gh-variable-delete -s e -l env -d 'Delete a variable for an environment'
complete -c gh-variable-delete -s o -l org -d 'Delete a variable for an organization OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-variable-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh varia…'

