# gh-workflow-list
# Autogenerated from man page /nix/store/aapnxgvkl1xx1s13c93k8d18f3vlg9r0-gh-2.72.0/share/man/man1/gh-workflow-list.1.gz
complete -c gh-workflow-list -s a -l all -d 'Include disabled workflows'
complete -c gh-workflow-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-workflow-list -l json -d 'Output JSON with the specified fields'
complete -c gh-workflow-list -s L -l limit -d 'Maximum number of workflows to fetch'
complete -c gh-workflow-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" OPTIONS INHE…'
complete -c gh-workflow-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh workf…'

