# gitattributes
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man5/gitattributes.5.gz
complete -c gitattributes -o crlf -o text -d 'crlf=input      eol=lf End-of-line conversion While Git normally leaves file …'
complete -c gitattributes -s p -d 'Marking files as binary Git usually guesses correctly whether a blob contains…'

