# gitcredentials
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitcredentials.7.gz
complete -c gitcredentials -l option -d 'will execute git credential-foo'

