# gitcore-tutorial
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitcore-tutorial.7.gz
complete -c gitcore-tutorial -l - -d '+++ b/hello @@ -1 +1,2 @@  Hello World +Its a new day for git i. e'
complete -c gitcore-tutorial -s a -d 'git-tutorial new-git-tutorial'

