# gitcli
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitcli.7.gz
complete -c gitcli -l end-of-options -d 'for this (it also works for commands that do not distinguish between revision…'
complete -c gitcli -s a
complete -c gitcli -s b -d 'to git foo'
complete -c gitcli -o ab -d 'oc o 2. 3'
complete -c gitcli -o oArg -d 'instead of git foo'
complete -c gitcli -s o -d 'Arg for short options, and git foo'
complete -c gitcli -l long-opt -d 'instead of git foo'
complete -c gitcli -l file -d '~/mine, not git foo'
complete -c gitcli -s 1 -d 'HEAD but write git log'
complete -c gitcli -l ';' -d 'HEAD in the work tree.  oc o 2. 3'
complete -c gitcli -l option -d 'to be abbreviated only to their unique prefix (e. g'
complete -c gitcli -l opt -d 'to invoke the'
complete -c gitcli -l optimize
complete -c gitcli -s h
complete -c gitcli -l help-all
complete -c gitcli -l cached -d 'option is used to ask a command that usually works on files in the working tr…'
complete -c gitcli -l index -d 'option is used to ask a command that usually works on files in the working tr…'
complete -c gitcli -l staged -d 'is exactly like'
complete -c gitcli -l worktree -d 'is the opposite, to ask a command to work on the working tree only, not the i…'

