# giteveryday
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/giteveryday.7.gz
complete -c giteveryday -s a -d 'later.  T} 4. 	T{ to see what changes you are committing.  T} 5'
complete -c giteveryday -o 10 -d '(to show up to 10 commits),'
complete -c giteveryday -l until -d 'T} 11'
complete -c giteveryday -s k
complete -c giteveryday -s m
complete -c giteveryday -l stdout -d 'v2. 6. 14. private2. 6. 14 | git am'
complete -c giteveryday -s 3

