# gitformat-bundle
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man5/gitformat-bundle.5.gz
complete -c gitformat-bundle -l filter -d 'option in git-rev-list(1).  The resulting pack-file must be marked as a '

