# gitfaq
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitfaq.7.gz
complete -c gitfaq -l nofork
complete -c gitfaq -s t -d ed25519
complete -c gitfaq -s f -d '~/. ssh/id_committer.  You can then register the public key (in this case, ~/'
complete -c gitfaq -s a
complete -c gitfaq -l delete-after -d '(ideally with an encrypted connection such as with ssh) on the root of reposi…'
complete -c gitfaq -l amend
complete -c gitfaq -l no-edit -d 'option to git commit in addition, or just save and quit when your editor opens'
complete -c gitfaq -l cached -d '<file/pattern> and add a pattern to . gitignore that matches the <file>'
complete -c gitfaq -s q -d 'and socat will require a timeout with something like'
complete -c gitfaq -l no-verify -d 'without being noticed (among various other ways)'
complete -c gitfaq -l renormalize -d 'to have this take effect'

