# gitglossary
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitglossary.7.gz
complete -c gitglossary -l set-upstream-to -d 'that sets what remote-tracking branch the current branch integrates with) obv…'
complete -c gitglossary -s r -d overlay
complete -c gitglossary -l pickaxe-all -d 'option, it can be used to view the full changeset that introduced or removed,…'
complete -c gitglossary -l depth -d 'shallow repository'

