# gitprotocol-v2
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man5/gitprotocol-v2.5.gz
complete -c gitprotocol-v2 -l list -d 'would accept (with the'
complete -c gitprotocol-v2 -l file -d 'option).  The key-value pairs in this list are in the bundle'

