# gitrevisions
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitrevisions.7.gz
complete -c gitrevisions -l no-checkout -d AUTO_MERGE
complete -c gitrevisions -l since -d and
complete -c gitrevisions -l until -d '<refname>@{<n>}, e. g.  master@{1}'
complete -c gitrevisions -l -A---B---o---o---C---D -d 'because A and B are reachable from C, the revision range specified by these t…'

