# gitremote-helpers
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitremote-helpers.7.gz
complete -c gitremote-helpers -l export-marks -d 'in git-fast-export(1).  import-marks <file>'
complete -c gitremote-helpers -l import-marks -d 'in git-fast-export(1).  signed-tags'
complete -c gitremote-helpers -l signed-tags -d 'to git-fast-export(1).  In the absence of this capability, Git will use'

