# gitrepository-layout
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man5/gitrepository-layout.5.gz
complete -c gitrepository-layout -l depth -d 'option to git-clone(1) and git-fetch(1)'

