# gitsubmodules
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitsubmodules.7.gz
complete -c gitsubmodules -l recurse-submodules -d 'which specifies whether to recurse into submodules'
complete -c gitsubmodules -l ignore-submodules -d 'in the superproject'

