# gitworkflows
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man7/gitworkflows.7.gz
complete -c gitworkflows -l ff-only -d 'master If the merge fails because it is not a fast-forward, then it is possib…'
complete -c gitworkflows -s C -d 'next master oc o 2. 3'
complete -c gitworkflows -s M -d 'upstream. topic to turn them into preformatted patch files oc o 2. 3'
complete -c gitworkflows -l to -d '<patches> See the git-format-patch(1) and git-send-email(1) manpages for furt…'

