# gitweb
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man1/gitweb.1.gz
complete -c gitweb -l export-all -d 'option is used) allows pulling only for those repositories that have git-daem…'

