# gitweb.conf
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man5/gitweb.conf.5.gz
complete -c 'gitweb.conf' -l export-all -d '$export_auth_hook'
complete -c 'gitweb.conf' -l syntax -d '<syntax> to "highlight"'
complete -c 'gitweb.conf' -o 'S<string>' -d 'option, which refers to pickaxe entry in gitdiffcore(7) for more details)'
complete -c 'gitweb.conf' -s l -d 'does; see description of'
complete -c 'gitweb.conf' -l author
complete -c 'gitweb.conf' -l committer -d and
complete -c 'gitweb.conf' -l grep -d 'options in git-log(1) manpage.  Enabled by default'

