# graphml2gv
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/graphml2gv.1.gz
complete -c graphml2gv -s v -d 'Turns on verbose mode'
complete -c graphml2gv -s '?' -d 'Prints usage information and exits'
complete -c graphml2gv -s g -d 'The string gname is used as the name of the generated graph'
complete -c graphml2gv -s o -d 'Prints output to the file outfile.  If not given, graphml2gv uses stdout'

