# gsftopk
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/gsftopk.1
complete -c gsftopk -l debug -d 'Set the  Kpathsea debug flags according to the integer R n '
complete -c gsftopk -l dosnames -d 'Use a name of the form B font . pk instead of B font .  dpi pk'
complete -c gsftopk -s h -l help -d 'Print a brief help synopsis and exit'
complete -c gsftopk -s i -l interpreter -d 'Use  path as the Ghostscript interpreter'
complete -c gsftopk -l mapfile -d 'Use  file to look for the map information for R font '
complete -c gsftopk -l mapline -d 'Use  line instead of looking for an entry in a map file'
complete -c gsftopk -s q -l quiet -d 'Operate quietly; i. e. , without writing any messages to the standard output'
complete -c gsftopk -s t -l test -d 'Test run:  return zero status if the font can be found in the map file(s), an…'
complete -c gsftopk -s v -l version -d 'Print the version number and exit'

