# gstack
# Autogenerated from man page /nix/store/v2gw1fvvp3fpsvdj04s363zb36hs411k-gdb-16.2/share/man/man1/gstack.1.gz
complete -c gstack -l help -d 'X Item "--help"'
complete -c gstack -s h -d 'X Item "-h" . PD List all options, with brief explanations'
complete -c gstack -l version -d 'X Item "--version"'
complete -c gstack -s v -d 'Print version information and then exit.  ENVIRONMENT'

