# gv2gml
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/gv2gml.1.gz
complete -c gv2gml -s v -d 'Turns on verbose mode'
complete -c gv2gml -s y -d 'Uses attributes according to yWorks'
complete -c gv2gml -s '?' -d 'Prints usage information and exits'
complete -c gv2gml -s g -d 'The string gname is used as the name of the generated graph'
complete -c gv2gml -s o -d 'Prints output to the file outfile.  If not given, gml2gv uses stdout'

