# gvmap.sh
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/gvmap.sh.1.gz
complete -c 'gvmap.sh' -s a -d 'The integer k specifies the average number of artificial points added along  …'
complete -c 'gvmap.sh' -s K -d 'specifies which program should be use for the initial layout'
complete -c 'gvmap.sh' -s T -d 'specifies the final output format'
complete -c 'gvmap.sh' -s N -d 'specifies the setting of a default node attribute during the rendering phase'
complete -c 'gvmap.sh' -s G -d 'specifies the setting of a graph attribute during the rendering phase'
complete -c 'gvmap.sh' -s E -d 'specifies the setting of a default edge attribute during the rendering phase'
complete -c 'gvmap.sh' -s n -d 'specifies the setting of a default node attribute during the layout phase'
complete -c 'gvmap.sh' -s g -d 'specifies the setting of a graph attribute during the layout phase'
complete -c 'gvmap.sh' -s e -d 'specifies the setting of a default edge attribute during the layout phase'
complete -c 'gvmap.sh' -s A -d 'specifies a flag to be passed to gvmap.  For example, gvmap'
complete -c 'gvmap.sh' -s v -d 'Set verbose mode'
complete -c 'gvmap.sh' -s V -d 'Print version information and exit'
complete -c 'gvmap.sh' -s '?' -d 'Print usage information and exit'

