# hbf2gf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/hbf2gf.1
complete -c hbf2gf -s q -d 'makes hbf2gf quiet.  hbf2gf'
complete -c hbf2gf -s p -d 'is set, no'
complete -c hbf2gf -s g -d 'is set, no'
complete -c hbf2gf -s n -d 'if set, the extension is `c'
complete -c hbf2gf -s t -d '[ -q ] %subfont-name This mode is intended for use with scripts like %mktexpk…'
complete -c hbf2gf -l version -d 'returns the current version of hbf2gf and the used file search library (e. g'
complete -c hbf2gf -l help -d 'parameter.  CONFIGURATION FILE Here a sample configuration file (c'

