# hishrink
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/hishrink.1
complete -c hishrink -s a -d 'Use only the localized names for auxiliary files as explained in the  FILES s…'
complete -c hishrink -s c -d 'Enable the use of compression for the HINT file'
complete -c hishrink -s d -d 'Sets HINT file debugging flags according to the  R bitmask '
complete -c hishrink -s g -d 'Do not use the localized names for auxiliary files as explained in the  FILES…'
complete -c hishrink -l help -d 'Print help message and exit'
complete -c hishrink -s l -d 'Redirect standard error to a log file'
complete -c hishrink -s o -d 'Use  name for the output file instead of deriving it from the name of the inp…'
complete -c hishrink -l version -d 'Print version information and exit'

