# histretch
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/histretch.1
complete -c histretch -s a -d 'Write auxiliar files to disk using the localized path names as explained in t…'
complete -c histretch -s d -d 'Sets HINT file debugging flags according to the  R bitmask '
complete -c histretch -s f -d 'Force the replacement of existing auxiliary files'
complete -c histretch -s g -d 'Write auxiliar files to disk using the path names as stored in the HINT file'
complete -c histretch -l help -d 'Print help message and exit'
complete -c histretch -s l -d 'Redirect standard error to a log file'
complete -c histretch -s o -d 'Use  name for the output file instead of deriving it from the name of the inp…'
complete -c histretch -s u -d 'Enable the use of UTF8 character codes'
complete -c histretch -l version -d 'Print version information and exit'
complete -c histretch -s x -d option

