# hlint
# Autogenerated from man page /nix/store/hi9b6hdp4yg1h29fy6gvhbcajvifxmxk-hlint-3.8/share/man/man1/hlint.1.gz
complete -c hlint -s '?' -l help -d 'Display help message'
complete -c hlint -s v -l version -d 'Display version information'
complete -c hlint -s r -l report -d 'Generate a report in HTML'
complete -c hlint -s h -l hint -d 'Hint/ignore file to use'
complete -c hlint -s c -l color -l colour -d 'Color the output (requires ANSI terminal)'
complete -c hlint -s i -l ignore -d 'Ignore a particular hint'
complete -c hlint -s s -l show -d 'Show all ignored ideas'
complete -c hlint -s t -l test -d 'Run in test mode EXAMPLE "To check all Haskell files in \'src\' and generate a …'

