# home-configuration.nix
# Autogenerated from man page /nix/store/5sclc9y585xamxaj7j3vpc88ivvkc39n-home-configuration-reference-manpage/share/man/man5/home-configuration.nix.5
complete -c 'home-configuration.nix' -l quiet -d 'Runs the given command on live run and sends its standard output to /dev/null…'
complete -c 'home-configuration.nix' -l silence -d 'Runs the given command on live run and sends its standard and error output to…'
complete -c 'home-configuration.nix' -l sort
complete -c 'home-configuration.nix' -l effective
complete -c 'home-configuration.nix' -l date-format -d 'Declared by:'

