# hyperxmp-add-bytecount
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/hyperxmp-add-bytecount.1
complete -c hyperxmp-add-bytecount -o help -d 'Write usage summary and exit'
complete -c hyperxmp-add-bytecount -o version -d 'Output version information and exit'

