# ifne
# Autogenerated from man page /nix/store/8231k60pm54p9inml853jlyxr22g94z0-moreutils-0.70/share/man/man1/ifne.1.gz
complete -c ifne -s n -d 'Reverse operation.  Run the command if the standard input is empty'

