# iotop
# Autogenerated from man page /nix/store/n4yyma8d5pr2njgdq4f2v7rx2fy8cnrr-iotop-0.6/share/man/man8/iotop.8.gz
complete -c iotop -l version -d 'Show the version number and exit'
complete -c iotop -s h -l help -d 'Show usage information and exit'
complete -c iotop -s o -l only -d 'Only show processes or threads actually doing I/O, instead of showing all pro…'
complete -c iotop -s b -l batch -d 'Turn on non-interactive mode.  Useful for logging I/O usage over time'
complete -c iotop -s n -l iter -d 'Set the number of iterations before quitting (never quit by default)'
complete -c iotop -s d -l delay -d 'Set the delay between iterations in seconds (1 second by default)'
complete -c iotop -s p -l pid -d 'A list of processes/threads to monitor (all by default)'
complete -c iotop -s u -l user -d 'A list of users to monitor (all by default)'
complete -c iotop -s P -l processes -d 'Only show processes.  Normally iotop shows all threads'
complete -c iotop -s a -l accumulated -d 'Show accumulated I/O instead of bandwidth'
complete -c iotop -s k -l kilobytes -d 'Use kilobytes instead of a human friendly unit'
complete -c iotop -s t -l time -d 'Add a timestamp on each line (implies --batch)'
complete -c iotop -s q -l quiet -d 'suppress some lines of header (implies --batch)'
complete -c iotop -o qq -d 'column names are never printed,'
complete -c iotop -o qqq -d 'the I/O summary is never printed'

