# jcmd
# Autogenerated from man page /nix/store/5yii18di89wpxcffk3cihpzfdrzw54gl-openjdk-21.0.7+6/share/man/man1/jcmd.1
complete -c jcmd -o all -d 'Compiler. codecache Prints code cache layout and bounds'
complete -c jcmd -o parallel -d 'heap inspection'
complete -c jcmd -o gz -d 'gzipped format using the given compression level'
complete -c jcmd -o overwrite -d 'overwritten if it exists (BOOLEAN, false)'
complete -c jcmd -s e -d 'false) [bu] 2'
complete -c jcmd -s l -d '(BOOLEAN, false) VM'
complete -c jcmd -s i -d '(BOOLEAN, false) [bu] 2'
complete -c jcmd -s s -d 'subclasses in addition to its superclasses'
complete -c jcmd -o verbose -d 'table (BOOLEAN, false) VM. symboltable [options] Dumps the symbol table'
complete -c jcmd -o date -d '(BOOLEAN, false) VM. version Prints JVM version information.  Impact: Low'

