# jj-absorb
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-absorb.1.gz
complete -c jj-absorb -s f -l from -d 'Source revision to absorb from'
complete -c jj-absorb -s t -l into -d 'Destination revisions to absorb into  Only ancestors of the source revision w…'
complete -c jj-absorb -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-absorb -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-absorb -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-absorb -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-absorb -l debug -d 'Enable debug logging'
complete -c jj-absorb -l color -d 'When to colorize output . br  '
complete -c jj-absorb -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-absorb -l no-pager -d 'Disable the pager'
complete -c jj-absorb -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-absorb -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-absorb -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

