# jj-bookmark-move
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-bookmark-move.1.gz
complete -c jj-bookmark-move -s f -l from -d 'Move bookmarks from the given revisions'
complete -c jj-bookmark-move -s t -l to -d 'Move bookmarks to this revision'
complete -c jj-bookmark-move -s B -l allow-backwards -d 'Allow moving bookmarks backwards or sideways'
complete -c jj-bookmark-move -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-bookmark-move -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-bookmark-move -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-bookmark-move -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-bookmark-move -l debug -d 'Enable debug logging'
complete -c jj-bookmark-move -l color -d 'When to colorize output . br  '
complete -c jj-bookmark-move -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-bookmark-move -l no-pager -d 'Disable the pager'
complete -c jj-bookmark-move -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-bookmark-move -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-bookmark-move -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

