# jj-config-list
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-config-list.1.gz
complete -c jj-config-list -l include-defaults -d 'Whether to explicitly include built-in default values in the list'
complete -c jj-config-list -l include-overridden -d 'Allow printing overridden values'
complete -c jj-config-list -l user -d 'Target the user-level config'
complete -c jj-config-list -l repo -d 'Target the repo-level config'
complete -c jj-config-list -s T -l template -d 'Render each variable using the given template  The following keywords are ava…'
complete -c jj-config-list -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-config-list -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-config-list -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-config-list -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-config-list -l debug -d 'Enable debug logging'
complete -c jj-config-list -l color -d 'When to colorize output . br  '
complete -c jj-config-list -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-config-list -l no-pager -d 'Disable the pager'
complete -c jj-config-list -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-config-list -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-config-list -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

