# jj-commit
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-commit.1.gz
complete -c jj-commit -s i -l interactive -d 'Interactively choose which changes to include in the first commit'
complete -c jj-commit -l tool -d 'Specify diff editor to be used (implies --interactive)'
complete -c jj-commit -s m -l message -d 'The change description to use (don\\*(Aqt open editor)'
complete -c jj-commit -l reset-author -d 'Reset the author to the configured user  This resets the author name, email, …'
complete -c jj-commit -l author -d 'Set author to the provided string  This changes author name and email while r…'
complete -c jj-commit -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-commit -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-commit -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-commit -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-commit -l debug -d 'Enable debug logging'
complete -c jj-commit -l color -d 'When to colorize output . br  '
complete -c jj-commit -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-commit -l no-pager -d 'Disable the pager'
complete -c jj-commit -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-commit -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-commit -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

