# jj-duplicate
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-duplicate.1.gz
complete -c jj-duplicate -s d -l destination -d 'The revision(s) to duplicate onto (can be repeated to create a merge commit)'
complete -c jj-duplicate -s A -l insert-after -d 'The revision(s) to insert after (can be repeated to create a merge commit)'
complete -c jj-duplicate -s B -l insert-before -d 'The revision(s) to insert before (can be repeated to create a merge commit)'
complete -c jj-duplicate -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-duplicate -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-duplicate -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-duplicate -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-duplicate -l debug -d 'Enable debug logging'
complete -c jj-duplicate -l color -d 'When to colorize output . br  '
complete -c jj-duplicate -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-duplicate -l no-pager -d 'Disable the pager'
complete -c jj-duplicate -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-duplicate -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-duplicate -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

