# jj-diffedit
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-diffedit.1.gz
complete -c jj-diffedit -s r -l revision -d 'The revision to touch up  Defaults to @ if neither --to nor --from are specif…'
complete -c jj-diffedit -s f -l from -d 'Show changes from this revision  Defaults to @ if --to is specified'
complete -c jj-diffedit -s t -l to -d 'Edit changes in this revision  Defaults to @ if --from is specified'
complete -c jj-diffedit -l tool -d 'Specify diff editor to be used'
complete -c jj-diffedit -l restore-descendants -d 'Preserve the content (not the diff) when rebasing descendants  When rebasing …'
complete -c jj-diffedit -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-diffedit -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-diffedit -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-diffedit -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-diffedit -l debug -d 'Enable debug logging'
complete -c jj-diffedit -l color -d 'When to colorize output . br  '
complete -c jj-diffedit -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-diffedit -l no-pager -d 'Disable the pager'
complete -c jj-diffedit -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-diffedit -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-diffedit -s h -l help -d 'Print help (see a summary with \\-h)'

