# jj-file-annotate
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-file-annotate.1.gz
complete -c jj-file-annotate -s r -l revision -d 'an optional revision to start at'
complete -c jj-file-annotate -s T -l template -d 'Render each line using the given template  All 0-argument methods of the [`An…'
complete -c jj-file-annotate -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-file-annotate -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-file-annotate -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-file-annotate -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-file-annotate -l debug -d 'Enable debug logging'
complete -c jj-file-annotate -l color -d 'When to colorize output . br  '
complete -c jj-file-annotate -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-file-annotate -l no-pager -d 'Disable the pager'
complete -c jj-file-annotate -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-file-annotate -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-file-annotate -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

