# jj-fix
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-fix.1.gz
complete -c jj-fix -s s -l source -d 'Fix files in the specified revision(s) and their descendants'
complete -c jj-fix -l include-unchanged-files -d 'Fix unchanged files in addition to changed ones'
complete -c jj-fix -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-fix -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-fix -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-fix -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-fix -l debug -d 'Enable debug logging'
complete -c jj-fix -l color -d 'When to colorize output . br  '
complete -c jj-fix -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-fix -l no-pager -d 'Disable the pager'
complete -c jj-fix -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-fix -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-fix -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

