# jj-file-show
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-file-show.1.gz
complete -c jj-file-show -s r -l revision -d 'The revision to get the file contents from'
complete -c jj-file-show -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-file-show -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-file-show -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-file-show -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-file-show -l debug -d 'Enable debug logging'
complete -c jj-file-show -l color -d 'When to colorize output . br  '
complete -c jj-file-show -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-file-show -l no-pager -d 'Disable the pager'
complete -c jj-file-show -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-file-show -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-file-show -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

