# jj-git-init
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-git-init.1.gz
complete -c jj-git-init -l colocate -d 'Specifies that the `jj` repo should also be a valid `git` repo, allowing the …'
complete -c jj-git-init -l git-repo -d 'Specifies a path to an **existing** git repository to be used as the backing …'
complete -c jj-git-init -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-git-init -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-git-init -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-git-init -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-git-init -l debug -d 'Enable debug logging'
complete -c jj-git-init -l color -d 'When to colorize output . br  '
complete -c jj-git-init -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-git-init -l no-pager -d 'Disable the pager'
complete -c jj-git-init -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-git-init -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-git-init -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

