# jj-git-fetch
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-git-fetch.1.gz
complete -c jj-git-fetch -s b -l branch -d 'Fetch only some of the branches  By default, the specified name matches exact…'
complete -c jj-git-fetch -l remote -d 'The remote to fetch from (only named remotes are supported, can be repeated) …'
complete -c jj-git-fetch -l all-remotes -d 'Fetch from all remotes'
complete -c jj-git-fetch -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-git-fetch -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-git-fetch -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-git-fetch -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-git-fetch -l debug -d 'Enable debug logging'
complete -c jj-git-fetch -l color -d 'When to colorize output . br  '
complete -c jj-git-fetch -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-git-fetch -l no-pager -d 'Disable the pager'
complete -c jj-git-fetch -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-git-fetch -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-git-fetch -s h -l help -d 'Print help (see a summary with \\-h)'

