# jj-git-clone
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-git-clone.1.gz
complete -c jj-git-clone -l remote -d 'Name of the newly created remote'
complete -c jj-git-clone -l colocate -d 'Whether or not to colocate the Jujutsu repo with the git repo'
complete -c jj-git-clone -l depth -d 'Create a shallow clone of the given depth'
complete -c jj-git-clone -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-git-clone -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-git-clone -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-git-clone -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-git-clone -l debug -d 'Enable debug logging'
complete -c jj-git-clone -l color -d 'When to colorize output . br  '
complete -c jj-git-clone -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-git-clone -l no-pager -d 'Disable the pager'
complete -c jj-git-clone -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-git-clone -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-git-clone -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

