# jj-next
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-next.1.gz
complete -c jj-next -s e -l edit -d 'Instead of creating a new working-copy commit on top of the target commit (li…'
complete -c jj-next -s n -l no-edit -d 'The inverse of `--edit`  Takes precedence over config in `ui. movement'
complete -c jj-next -l conflict -d 'Jump to the next conflicted descendant'
complete -c jj-next -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-next -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-next -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-next -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-next -l debug -d 'Enable debug logging'
complete -c jj-next -l color -d 'When to colorize output . br  '
complete -c jj-next -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-next -l no-pager -d 'Disable the pager'
complete -c jj-next -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-next -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-next -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

