# jj-new
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-new.1.gz
complete -c jj-new -s m -l message -d 'The change description to use'
complete -c jj-new -l no-edit -d 'Do not edit the newly created change'
complete -c jj-new -s A -l insert-after -d 'Insert the new change after the given commit(s)'
complete -c jj-new -s B -l insert-before -d 'Insert the new change before the given commit(s)'
complete -c jj-new -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-new -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-new -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-new -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-new -l debug -d 'Enable debug logging'
complete -c jj-new -l color -d 'When to colorize output . br  '
complete -c jj-new -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-new -l no-pager -d 'Disable the pager'
complete -c jj-new -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-new -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-new -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

