# jj-operation-restore
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-operation-restore.1.gz
complete -c jj-operation-restore -l what -d 'What portions of the local state to restore (can be repeated)  This option is…'
complete -c jj-operation-restore -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-operation-restore -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-operation-restore -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-operation-restore -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-operation-restore -l debug -d 'Enable debug logging'
complete -c jj-operation-restore -l color -d 'When to colorize output . br  '
complete -c jj-operation-restore -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-operation-restore -l no-pager -d 'Disable the pager'
complete -c jj-operation-restore -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-operation-restore -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-operation-restore -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

