# jj-prev
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-prev.1.gz
complete -c jj-prev -s e -l edit -d 'Edit the parent directly, instead of moving the working-copy commit  Takes pr…'
complete -c jj-prev -s n -l no-edit -d 'The inverse of `--edit`  Takes precedence over config in `ui. movement'
complete -c jj-prev -l conflict -d 'Jump to the previous conflicted ancestor'
complete -c jj-prev -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-prev -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-prev -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-prev -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-prev -l debug -d 'Enable debug logging'
complete -c jj-prev -l color -d 'When to colorize output . br  '
complete -c jj-prev -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-prev -l no-pager -d 'Disable the pager'
complete -c jj-prev -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-prev -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-prev -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

