# jj-revert
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-revert.1.gz
complete -c jj-revert -s r -l revisions -d 'The revision(s) to apply the reverse of'
complete -c jj-revert -s d -l destination -d 'The revision(s) to apply the reverse changes on top of'
complete -c jj-revert -s A -l insert-after -d 'The revision(s) to insert the reverse changes after (can be repeated to creat…'
complete -c jj-revert -s B -l insert-before -d 'The revision(s) to insert the reverse changes before (can be repeated to crea…'
complete -c jj-revert -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-revert -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-revert -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-revert -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-revert -l debug -d 'Enable debug logging'
complete -c jj-revert -l color -d 'When to colorize output . br  '
complete -c jj-revert -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-revert -l no-pager -d 'Disable the pager'
complete -c jj-revert -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-revert -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-revert -s h -l help -d 'Print help (see a summary with \\-h)'

