# jj-resolve
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-resolve.1.gz
complete -c jj-resolve -s l -l list -d 'Instead of resolving conflicts, list all the conflicts'
complete -c jj-resolve -l tool -d 'Specify 3-way merge tool to be used  The built-in merge tools `:ours` and `:t…'
complete -c jj-resolve -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-resolve -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-resolve -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-resolve -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-resolve -l debug -d 'Enable debug logging'
complete -c jj-resolve -l color -d 'When to colorize output . br  '
complete -c jj-resolve -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-resolve -l no-pager -d 'Disable the pager'
complete -c jj-resolve -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-resolve -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-resolve -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'
complete -c jj-resolve -s r -l revision

