# jj-simplify-parents
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-simplify-parents.1.gz
complete -c jj-simplify-parents -s s -l source -d 'Simplify specified revision(s) together with their trees of descendants (can …'
complete -c jj-simplify-parents -s r -l revisions -d 'Simplify specified revision(s) (can be repeated)  If both `--source` and `--r…'
complete -c jj-simplify-parents -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-simplify-parents -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-simplify-parents -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-simplify-parents -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-simplify-parents -l debug -d 'Enable debug logging'
complete -c jj-simplify-parents -l color -d 'When to colorize output . br  '
complete -c jj-simplify-parents -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-simplify-parents -l no-pager -d 'Disable the pager'
complete -c jj-simplify-parents -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-simplify-parents -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-simplify-parents -s h -l help -d 'Print help (see a summary with \\-h)'

