# jj-sign
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-sign.1.gz
complete -c jj-sign -s r -l revisions -d 'What revision(s) to sign  If no revisions are specified, this defaults to the…'
complete -c jj-sign -l key -d 'The key used for signing'
complete -c jj-sign -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-sign -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-sign -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-sign -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-sign -l debug -d 'Enable debug logging'
complete -c jj-sign -l color -d 'When to colorize output . br  '
complete -c jj-sign -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-sign -l no-pager -d 'Disable the pager'
complete -c jj-sign -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-sign -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-sign -s h -l help -d 'Print help (see a summary with \\-h)'

