# jj-split
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-split.1.gz
complete -c jj-split -s i -l interactive -d 'Interactively choose which parts to split  This is the default if no filesets…'
complete -c jj-split -l tool -d 'Specify diff editor to be used (implies --interactive)'
complete -c jj-split -s r -l revision -d 'The revision to split'
complete -c jj-split -s p -l parallel -d 'Split the revision into two parallel revisions instead of a parent and child'
complete -c jj-split -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-split -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-split -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-split -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-split -l debug -d 'Enable debug logging'
complete -c jj-split -l color -d 'When to colorize output . br  '
complete -c jj-split -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-split -l no-pager -d 'Disable the pager'
complete -c jj-split -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-split -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-split -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

