# jj-workspace-add
# Autogenerated from man page /nix/store/w3dqqdxnncrrv19l5qqa8f6fgndx83ss-jujutsu-0.28.2/share/man/man1/jj-workspace-add.1.gz
complete -c jj-workspace-add -l name -d 'A name for the workspace  To override the default, which is the basename of t…'
complete -c jj-workspace-add -s r -l revision -d 'A list of parent revisions for the working-copy commit of the newly created w…'
complete -c jj-workspace-add -l sparse-patterns -d 'How to handle sparse patterns when creating a new workspace . br  '
complete -c jj-workspace-add -s R -l repository -d 'Path to repository to operate on  By default, Jujutsu searches for the closes…'
complete -c jj-workspace-add -l ignore-working-copy -d 'Don\\*(Aqt snapshot the working copy, and don\\*(Aqt update it  By default, Juj…'
complete -c jj-workspace-add -l ignore-immutable -d 'Allow rewriting immutable commits  By default, Jujutsu prevents rewriting com…'
complete -c jj-workspace-add -l at-operation -d 'Operation to load the repo at  Operation to load the repo at'
complete -c jj-workspace-add -l debug -d 'Enable debug logging'
complete -c jj-workspace-add -l color -d 'When to colorize output . br  '
complete -c jj-workspace-add -l quiet -d 'Silence non-primary command output  For example, `jj file list` will still li…'
complete -c jj-workspace-add -l no-pager -d 'Disable the pager'
complete -c jj-workspace-add -l config -d 'Additional configuration options (can be repeated)  The name should be specif…'
complete -c jj-workspace-add -l config-file -d 'Additional configuration files (can be repeated)'
complete -c jj-workspace-add -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

