# jlink
# Autogenerated from man page /nix/store/5yii18di89wpxcffk3cihpzfdrzw54gl-openjdk-21.0.7+6/share/man/man1/jlink.1
complete -c jlink -l add-modules -d 'Adds the named modules, mod, to the default set of root modules'
complete -c jlink -l bind-services -d 'Link service provider modules and their dependencies'
complete -c jlink -s c -l compress -d 'Enable compression of resources:'
complete -c jlink -l disable-plugin -d 'Disables the specified plug-in'
complete -c jlink -l endian -d 'Specifies the byte order of the generated image'
complete -c jlink -s h -l help -d 'Prints the help message'
complete -c jlink -l ignore-signing-information -d 'Suppresses a fatal error when signed modular JARs are linked in the runtime i…'
complete -c jlink -l launcher -l launcher -d 'Specifies the launcher command name for the module or the command name for th…'
complete -c jlink -l limit-modules -d 'Limits the universe of observable modules to those in the transitive closure …'
complete -c jlink -l list-plugins -d 'Lists available plug-ins, which you can access through command-line options; …'
complete -c jlink -s p -l module-path -d 'Specifies the module path'
complete -c jlink -l no-header-files -d 'Excludes header files'
complete -c jlink -l no-man-pages -d 'Excludes man pages'
complete -c jlink -l output -d 'Specifies the location of the generated runtime image'
complete -c jlink -l save-opts -d 'Saves jlink options in the specified file'
complete -c jlink -l suggest-providers -d 'Suggest providers that implement the given service types from the module path'
complete -c jlink -l version -d 'Prints version information'
complete -c jlink -l include-locales
complete -c jlink -l order-resources
complete -c jlink -l strip-debug
complete -c jlink -l generate-cds-archive

