# jrunscript
# Autogenerated from man page /nix/store/5yii18di89wpxcffk3cihpzfdrzw54gl-openjdk-21.0.7+6/share/man/man1/jrunscript.1
complete -c jrunscript -o '\\f' -d 'Enters interactive mode to read and evaluate a script from standard input'
complete -c jrunscript -o cp -o classpath -d 'Indicates where any class files are that the script needs to access'
complete -c jrunscript -o Dname -d 'Sets a Java system property'
complete -c jrunscript -o Jflag -d 'Passes flag directly to the Java Virtual Machine where the jrunscript command…'
complete -c jrunscript -s l -d 'Uses the specified scripting language.  By default, JavaScript is used'
complete -c jrunscript -s e -d 'Evaluates the specified script'
complete -c jrunscript -o encoding -d 'Specifies the character encoding used to read script files'
complete -c jrunscript -s f -d 'Evaluates the specified script file (batch mode)'
complete -c jrunscript -o help -s '?' -d 'Displays a help message and exits'
complete -c jrunscript -s q -d 'Lists all script engines available and exits.  ARGUMENTS'

