# jstack
# Autogenerated from man page /nix/store/5yii18di89wpxcffk3cihpzfdrzw54gl-openjdk-21.0.7+6/share/man/man1/jstack.1
complete -c jstack -s l -d 'The long listing option prints additional information about locks'
complete -c jstack -s h -o help -d 'Prints a help message'

