# jwebserver
# Autogenerated from man page /nix/store/5yii18di89wpxcffk3cihpzfdrzw54gl-openjdk-21.0.7+6/share/man/man1/jwebserver.1
complete -c jwebserver -s h -s '?' -l help -d 'Prints the help message and exits'
complete -c jwebserver -s b -l bind-address -d 'Specifies the address to bind to.  Default: 127. 0. 0. 1 or ::1 (loopback)'
complete -c jwebserver -s d -l directory -d 'Specifies the directory to serve.  Default: current directory'
complete -c jwebserver -s o -l output -d 'Specifies the output format.  none | info | verbose.  Default: info'
complete -c jwebserver -s p -l port -d 'Specifies the port to listen on.  Default: 8000'
complete -c jwebserver -o version -l version -d 'Prints the version information and exits'

