# kpsetool
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/kpsetool.1
complete -c kpsetool -s m -d 'set Metafont mode'
complete -c kpsetool -s n -d 'pretend to be progname to kpathsea'
complete -c kpsetool -s p -d 'act like kpsepath(1)'
complete -c kpsetool -s v -d 'act like kpsexpand(1)'

