# latexrevise
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/latexrevise.1
complete -c latexrevise -s a -l accept -d 'Run in \\s-1ACCEPT\\s0 mode (delete all blocks marked by \\f(CW\\*(C`DIFdelbegin\\…'
complete -c latexrevise -s d -l decline -d 'Run in \\s-1DECLINE\\s0 mode (delete all blocks marked by \\f(CW\\*(C`DIFaddbegin…'
complete -c latexrevise -s s -l simplify -d 'Run in \\s-1SIMPLIFY\\s0 mode (Keep all \\f(CW\\*(C`DIFaddbegin\\*(C\', \\f(CW\\*(C`D…'
complete -c latexrevise -s c -l comment -d 'Remove \\f(CW\\*(C`cmd{. }\\*(C\' sequences'
complete -c latexrevise -s e -l comment-environment -d 'Remove explicit annotation environments from the text, i. e.  remove . Sp '
complete -c latexrevise -s m -l markup -d 'Remove the markup command \\f(CW\\*(C`cmd\\*(C\' but leave its argument, i. e'
complete -c latexrevise -s n -l markup-environment -d 'Similarly, remove \\f(CW\\*(C`begin{envir}\\*(C\' and \\f(CW\\*(C`end{envir}\\*(C\' c…'
complete -c latexrevise -s r -l replace -d 'For constructions \\f(CW\\*(C`cmd{. }{'
complete -c latexrevise -s V -l verbose -d 'Verbose output'

