# latexdiff-vc
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/latexdiff-vc.1
complete -c latexdiff-vc -l rcs -l svn -l cvs -l git -l hg -d 'Set the version control system used'
complete -c latexdiff-vc -s r -s r -l revision -l revision -d 'Choose revision (under \\s-1RCS, CVS, SVN, GIT\\s0 or \\s-1HG\\s0)'
complete -c latexdiff-vc -s d -l dir -s d -l dir -d 'Rather than appending the string \\f(CW\\*(C`diff\\*(C\' and optionally the versi…'
complete -c latexdiff-vc -l flatten -l flatten -d 'If combined with \\f(CW\\*(C`--git\\*(C\', \\f(CW\\*(C`--svn\\*(C\' or \\f(CW\\*(C`--hg…'
complete -c latexdiff-vc -l only-changes -d 'Post-process the output such that only pages with changes on them are display…'
complete -c latexdiff-vc -l force -d 'Overwrite existing diff files without asking for confirmation'
complete -c latexdiff-vc -l run -d 'run latex command on diff file after generation of diff file'
complete -c latexdiff-vc -l dvi -d 'run latex and dvixxx commands after generation of diff file'
complete -c latexdiff-vc -s c -l config -s c -d 'Set configuration variables for latexdiff and latexdiff-vc'
complete -c latexdiff-vc -o draftmode -o interaction -d el
complete -c latexdiff-vc -l fast -l so -d 'Use \\f(CW\\*(C`latexdiff-fast\\*(C\' or \\f(CW\\*(C`latexdiff-so\\*(C\', respectivel…'
complete -c latexdiff-vc -l ps -l postscript -d 'Generate postscript output from difference file'
complete -c latexdiff-vc -l pdf -d 'Generate pdf output from difference file using \\f(CW\\*(C`pdflatex\\*(C\''
complete -c latexdiff-vc -l show-config -d 'Show values of configuration variables'
complete -c latexdiff-vc -l help -s h -d 'Show help text'

