# latex2man
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/latex2man.1
complete -c latex2man -o ttransfile -d 'Translation for user defined LaTeX macros'
complete -c latex2man -o cCSSfile -d 'If you use the -H you can also specify a file that contains CSS  style sheets'
complete -c latex2man -s M -d 'Produce output suitable for the man(1) command (default)'
complete -c latex2man -s H -d 'Instead of producing output suitable for the man(1) command, HTML code is pro…'
complete -c latex2man -s T -d 'Instead of producing output suitable for the man(1) command, TexInfo code is …'
complete -c latex2man -s L -d 'The LaTeX source is written to the outfile'
complete -c latex2man -o Cname -d 'Output the conditional text for name'
complete -c latex2man -o achar -d 'Is used only in conjunction with -T. br Background: '
complete -c latex2man -s h -d 'Show a help text'
complete -c latex2man -s a -d 'supresses the indentation of a line'
complete -c latex2man -s V -d ' Show version information'
complete -c latex2man -o 'C\'abc' -d 'and have a look to the generated output'
complete -c latex2man -o CHTML -d ' the lines 1a, 2b, 3b, and 4b; '
complete -c latex2man -o CTEXI -d ' the lines 1b, 2a, 3b, and 4b; '
complete -c latex2man -o CMAN -d ' the lines 1b, 2b, 3a, and 4b; '
complete -c latex2man -o CLATEX -d ' the lines 1b, 2b, 3b, and 4a; '

