# ltx2crossrefxml
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ltx2crossrefxml.1
complete -c ltx2crossrefxml -s c -d 'X Item "-c config_file" Configuration file'
complete -c ltx2crossrefxml -s o -d 'X Item "-o output_file" Output file'
complete -c ltx2crossrefxml -o rpi-is-xml

