# ltx2unitxt
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ltx2unitxt.1
complete -c ltx2unitxt -s c -l config -d 'read (Perl) config FILE for a hook, as explained above'
complete -c ltx2unitxt -s e -l entities -d 'output entities &#xNNNN; instead of literal characters'
complete -c ltx2unitxt -s g -l german -d 'handle some features of the german package'
complete -c ltx2unitxt -s h -l html -d 'output simplistic HTML instead of plain text'
complete -c ltx2unitxt -s o -l output -d 'output to FILE instead of stdout'
complete -c ltx2unitxt -s v -l verbose -d 'be verbose'
complete -c ltx2unitxt -s V -l version -d 'output version information and exit'
complete -c ltx2unitxt -s '?' -l help -d 'display this help and exit'

