# luafindfont
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/luafindfont.1
complete -c luafindfont -s h -l help -d 'obvious .  :-)'
complete -c luafindfont -s V -l version -d 'obvious .  :-)'
complete -c luafindfont -s o -l otfinfo -d 'Use the program otfinfo for the font with the given number'
complete -c luafindfont -s i -l info -d 'List the given fontstyles (regular, bold, italic, bolditalic) for the font wi…'
complete -c luafindfont -s I -l Info -d 'Siliar to i but uses the program mtxrun to get ll informations including feat…'
complete -c luafindfont -s l -l listonlynames -d 'The output is a sorted long list of the symbilc names of the available fonts'
complete -c luafindfont -s L -l listonlyfiles -d 'The same with filenames (without the path!)'
complete -c luafindfont -s v -l verbose -d 'Give more informations, by now only -v works'
complete -c luafindfont -s x -l xetex -d 'test, if font is found by xetex via kpsewhich 0->no; 1->yes'
complete -c luafindfont -s m -l max_string -d 'The maximum of the stringlength of the full path of fonts'
complete -c luafindfont -s n -l no-symbolic-names -l nosymbolicnames -d 'The fontlist contains only fontfile and fontpath'

