# mag
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mag.1
complete -c mag -s 2 -d 'The UNIX shells allow command substitution.  One can write:'

