# makeglossaries-lite
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/makeglossaries-lite.1
complete -c makeglossaries-lite -s q -d 'X Item "-q" Quiet mode.  Reduces chatter to standard output'
complete -c makeglossaries-lite -s n -d 'X Item "-n" Print the commands that would normally be executed but don\\*(Aqt …'
complete -c makeglossaries-lite -s o -d 'X Item "-o file" Use file as the output file'
complete -c makeglossaries-lite -s s -d 'X Item "-s file" Use file as the style file'
complete -c makeglossaries-lite -s t -d 'X Item "-t file" Use file as the transcript file'
complete -c makeglossaries-lite -s l -d 'X Item "-l" Letter ordering'
complete -c makeglossaries-lite -s L -d 'X Item "-L language" This option only has an effect if xindy is called'
complete -c makeglossaries-lite -s c -d 'X Item "-c" Compress intermediate blanks (makeindex only)'
complete -c makeglossaries-lite -s g -d 'X Item "-g" Employ German word ordering (makeindex only)'
complete -c makeglossaries-lite -s p -d 'X Item "-p num" Sets the starting page number to be num (makeindex only)'
complete -c makeglossaries-lite -s r -d 'X Item "-r" Disable implicit page range formation (makeindex only)'
complete -c makeglossaries-lite -s m -d 'X Item "-m file" Specify the full path name for makeindex to file in the  eve…'
complete -c makeglossaries-lite -s x -d 'X Item "-x file" Specify the full path name for xindy to file in the  event t…'
complete -c makeglossaries-lite -l version -d 'X Item "--version" Prints version number and exits'
complete -c makeglossaries-lite -l help

