# makeglossaries
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/makeglossaries.1
complete -c makeglossaries -s e -d 'X Item "-e" Don\\*(Aqt attempt to repair multiple encaps or illegal page numbe…'
complete -c makeglossaries -s c -d 'X Item "-c" Compress intermediate blanks (makeindex only)'
complete -c makeglossaries -s d -d 'X Item "-d aux dir" Specify the directory the . aux, '
complete -c makeglossaries -s g -d 'X Item "-g" Employ German word ordering (makeindex only)'
complete -c makeglossaries -s k -d 'X Item "-k" Don\\*(Aqt try forking with piped redirection'
complete -c makeglossaries -s l -d 'X Item "-l" Letter ordering'
complete -c makeglossaries -s L -d 'X Item "-L language" This option only has an effect if xindy is called'
complete -c makeglossaries -s m -d 'X Item "-m file" Specify the full path name for makeindex to file in the  eve…'
complete -c makeglossaries -s n -d 'X Item "-n" Print the commands that would normally be executed but don\\*(Aqt …'
complete -c makeglossaries -s o -d 'X Item "-o file" Use file as the output file'
complete -c makeglossaries -s p -d 'X Item "-p num" Sets the starting page number to be num (makeindex only)'
complete -c makeglossaries -s q -d 'X Item "-q" Quiet mode.  Reduces chatter to standard output'
complete -c makeglossaries -s Q -d 'X Item "-Q" Silences warning about being unable to fork'
complete -c makeglossaries -s r -d 'X Item "-r"'
complete -c makeglossaries -s s -d 'X Item "-s file" . PD Use file as the style file'
complete -c makeglossaries -s t -d 'X Item "-t file" Use file as the transcript file'
complete -c makeglossaries -s x -d 'X Item "-x file" Specify the full path name for xindy to file in the  event t…'
complete -c makeglossaries -l version -d 'X Item "--version" Prints version number and exits'
complete -c makeglossaries -l help

