# manpath
# Autogenerated from man page /nix/store/6y6ijw6avikf17cyks2k07vc9q1wq31v-man-db-2.13.0/share/man/man5/manpath.5.gz
complete -c manpath -l systems -d 'option is used or the $ SYSTEM environment variable is set, then that should …'

