# mathspic
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mathspic.1
complete -c mathspic -s b -d 'enables beep if mathsPIC detects an error'
complete -c mathspic -s c -d 'disables the writing of comments to output file'
complete -c mathspic -s h -d 'displays the help file'
complete -c mathspic -s o -d 'defines the output file name MACRO COMMANDS macro definition commands are pre…'

