# mdconvert
# Autogenerated from man page /nix/store/4scfd0kjwy5vjzk2xl5kmsmc3qmwsfn0-isync-1.5.1/share/man/man1/mdconvert.1.gz
complete -c mdconvert -s a -l alt -d 'Convert to the alternative (Berkeley DB based) UID storage scheme'
complete -c mdconvert -s n -l native -d 'Convert to the native (file name based) UID storage scheme'
complete -c mdconvert -s h -l help -d 'Displays a summary of command line options'
complete -c mdconvert -s v -l version -d 'Displays version information'

