# memoize-clean
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/memoize-clean.1
complete -c memoize-clean -l 'prefix\\f' -d 'Add a memo/extern prefix for cleaning'
complete -c memoize-clean -l 'all\\f' -d 'Remove all memos and externs, rather than only the stale ones'
complete -c memoize-clean -l 'yes\\f' -d 'Do not ask for confirmation'
complete -c memoize-clean -l 'quiet\\f' -d 'Don\\[cq]t describe what\\[cq]s happening'
complete -c memoize-clean -l 'help\\f' -d 'Show help'
complete -c memoize-clean -l prefix -d 'mmz files'
complete -c memoize-clean -s p -d 'Add a memo/extern prefix for cleaning'
complete -c memoize-clean -s a -l all -d 'Remove all memos and externs, rather than only the stale ones'
complete -c memoize-clean -s y -l yes -d 'Do not ask for confirmation'
complete -c memoize-clean -s q -l quiet -d 'Don[cq]t describe what[cq]s happening'
complete -c memoize-clean -s h -l help -d 'Show help'
complete -c memoize-clean -s V -l version -d 'Show the Memoize version number and exit.  SEE ALSO c'

