# mft
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mft.1
complete -c mft -o change -d 'Apply the change file  change_file_name to R mf_file_name . PP'
complete -c mft -o metapost -d 'Assume  mf_file_name is a \\*(MP source file (this is the default if  mf_file_…'
complete -c mft -o style -d 'Use the style file style_file_name instead of plain. mft (or mplain'

