# mkjobtexmf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mkjobtexmf.1
complete -c mkjobtexmf -l jobname -d 'It is the name of the job.  `<jobname>'
complete -c mkjobtexmf -l texname -d 'The name of the TeX input file, if it differs from <jobname>. tex'
complete -c mkjobtexmf -l texopt -d 'Additional option for the TeX compiler, examples are \\f(CW\\*(C`--ini\\*(C\' or …'
complete -c mkjobtexmf -l destdir -d 'Specifies the name of the destination directory where the result is collected'
complete -c mkjobtexmf -l output -d 'Also add output files'
complete -c mkjobtexmf -l strace -d 'Use method with program strace, see \\*(L"\\s-1DESCRIPTION\\s0\\*(R"'
complete -c mkjobtexmf -l copy -d 'Files are copied instead of creating symbolic links'
complete -c mkjobtexmf -l flat -d 'Files are linked or copied without path elements'
complete -c mkjobtexmf -l exclude-ext -d 'Files with extension <ext> are excluded'
complete -c mkjobtexmf -l cmd-tex -d 'Command for the TeX compiler.  Default is pdflatex'
complete -c mkjobtexmf -l cmd-kpsewhich -d 'Command for kpsewhich'
complete -c mkjobtexmf -l cmd-texhash -d 'Command for updating the file name database of the generated texmf tree'
complete -c mkjobtexmf -l cmd-strace -d 'Command for strace'
complete -c mkjobtexmf -l verbose -d 'Verbose messages'
complete -c mkjobtexmf -l help -d 'Display help screen'

