# mktexpk
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mktexpk.1
complete -c mktexpk -l bdpi -d 'Set the base device resolution'
complete -c mktexpk -l dpi -d 'Generate the font at resolution R num '
complete -c mktexpk -l help -d 'Print help message and exit'
complete -c mktexpk -l mag -d 'The \\*(MF magnification that corresponds to the combination of  bdpi and  dpi…'
complete -c mktexpk -l mfmode -d 'The \\*(MF mode to use'
complete -c mktexpk -l destdir -d 'A directory name.  If the directory is absolute, it is used as-is'
complete -c mktexpk -l version -d 'Print version information and exit'

