# mktextfm
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mktextfm.1
complete -c mktextfm -l destdir -d 'A directory name.  If the directory is absolute, it is used as-is'
complete -c mktextfm -l help -d 'Print help message and exit successfully'
complete -c mktextfm -l version -d 'Print version information and exit successfully'

