# mktexmf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mktexmf.1
complete -c mktexmf -l help -d 'Print help message and exit'
complete -c mktexmf -l version -d 'Print version information and exit'

