# mlr
# Autogenerated from man page /nix/store/5hx1il357hg3234q1kdl1wbfz0xlvrs0-miller-6.13.0-man/share/man/man1/mlr.1.gz
complete -c mlr -l pass-comments -d '                         within the input'
complete -c mlr -l pass-comments-with -d '                         Immediately print commented lines within input, with…'
complete -c mlr -l skip-comments -d '                         input'
complete -c mlr -l skip-comments-with -d '                         Ignore commented lines within input, with specified …'
complete -c mlr -l bz2in -d '                         default if file ends in `. bz2`'
complete -c mlr -l gzin -d '                         default if file ends in `. gz`'
complete -c mlr -l prepipe -d '                         You can, of course, already do without this for     …'
complete -c mlr -l prepipe-bz2 -d '                         `. mlrrc`'
complete -c mlr -l prepipe-gunzip -d '                         `. mlrrc`'
complete -c mlr -l prepipe-zcat -d '                         `. mlrrc`'
complete -c mlr -l prepipe-zstdcat -d '                         in `. mlrrc`'
complete -c mlr -l prepipex -d '                         Like `--prepipe` with one exception: doesn\'t insert …'
complete -c mlr -l zin -d '                         default if file ends in `. z`'
complete -c mlr -l zstdin -d '                         default if file ends in `. zstd`'
complete -c mlr -l allow-ragged-csv-input -l ragged -l allow-ragged-tsv-input -d '                         If a data line has fewer fields than the header line…'
complete -c mlr -l csv-trim-leading-space -d '                         like \'"foo", "bar\' which is non-RFC-4180 compliant, …'
complete -c mlr -l headerless-csv-output -l ho -l headerless-tsv-output -d '                         Print only CSV/TSV data lines; do not print CSV/TSV …'
complete -c mlr -l implicit-csv-header -l headerless-csv-input -l hi -l implicit-tsv-header -d '                         Use 1,2,3,'
complete -c mlr -l lazy-quotes -d '                         non-doubled quotes appearing in quoted fields'
complete -c mlr -l no-auto-unsparsify -d '                         one row to another, emit a blank line and a new     …'
complete -c mlr -l no-implicit-csv-header -l no-implicit-tsv-header -d '                         Opposite of `--implicit-csv-header`'
complete -c mlr -l quote-all
complete -c mlr -s N -d '                         --headerless-csv-output`'
complete -c mlr -l asv -l asvlite
complete -c mlr -l csv -s c
complete -c mlr -l csvlite
complete -c mlr -l dkvp
complete -c mlr -l gen-field-name -l igen
complete -c mlr -l gen-start
complete -c mlr -l gen-step
complete -c mlr -l gen-stop
complete -c mlr -l iasv -l iasvlite
complete -c mlr -l icsv
complete -c mlr -l icsvlite
complete -c mlr -l idkvp
complete -c mlr -l ijson
complete -c mlr -l ijsonl
complete -c mlr -l imd -l imarkdown
complete -c mlr -l inidx
complete -c mlr -l io -d '                         example: `--io csv` is the same as `--csv`'
complete -c mlr -l ipprint
complete -c mlr -l itsv
complete -c mlr -l itsvlite
complete -c mlr -l iusv -l iusvlite
complete -c mlr -l ixtab
complete -c mlr -l json -s j
complete -c mlr -l jsonl
complete -c mlr -l nidx
complete -c mlr -l oasv -l oasvlite
complete -c mlr -l ocsv
complete -c mlr -l ocsvlite
complete -c mlr -l odkvp
complete -c mlr -l ojson
complete -c mlr -l ojsonl
complete -c mlr -l omd -l omarkdown
complete -c mlr -l onidx
complete -c mlr -l opprint
complete -c mlr -l otsv
complete -c mlr -l otsvlite
complete -c mlr -l ousv -l ousvlite
complete -c mlr -l oxtab
complete -c mlr -l pprint
complete -c mlr -l tsv -s t
complete -c mlr -l tsvlite
complete -c mlr -l usv -l usvlite
complete -c mlr -l xtab
complete -c mlr -l xvright
complete -c mlr -s i -d '                         is the same as `--icsv`'
complete -c mlr -s o -d '                         csv` is the same as `--ocsv`'
complete -c mlr -l flatsep -l jflatsep -d '                         Separator for flattening multi-level JSON keys, e. g'
complete -c mlr -l no-auto-flatten -d '                         auto-flatten behavior'
complete -c mlr -l no-auto-unflatten -d '                         default auto-unflatten behavior'
complete -c mlr -s p -l fs -l 'repifs`'
complete -c mlr -s T -d 'JSON-ONLY FLAGS These are flags which are applicable to JSON output format'
complete -c mlr -l jlistwrap -l jl -d '                         default for JSON output format'
complete -c mlr -l jvquoteall -d '                         object -- to string'
complete -c mlr -l jvstack -d '                         (multi-line output)'
complete -c mlr -l no-jlistwrap -d '                         the default for JSON Lines output format'
complete -c mlr -l no-jvstack -d '                         This is the default for JSON Lines output format'
complete -c mlr -l jknquoteint -d '                         preserved throughout the processing stream'
complete -c mlr -l jquoteall -d '                         preserved throughout the processing stream'
complete -c mlr -l json-fatal-arrays-on-input -d '                         Miller now supports arrays as of version 6'
complete -c mlr -l json-map-arrays-on-input -d '                         Miller now supports arrays as of version 6'
complete -c mlr -l json-skip-arrays-on-input -d '                         Miller now supports arrays as of version 6'
complete -c mlr -l jsonx
complete -c mlr -l mmap -d '                         files'
complete -c mlr -l no-mmap -d '                         files'
complete -c mlr -l ojsonx
complete -c mlr -l quote-minimal -d '                         through the processing flow now'
complete -c mlr -l quote-none -d '                         through the processing flow now'
complete -c mlr -l quote-numeric -d '                         through the processing flow now'
complete -c mlr -l quote-original -d '                         through the processing flow now'
complete -c mlr -l vflatsep -d '                         subsumed into JSON formatting'
complete -c mlr -l fflush -d '                         output record'
complete -c mlr -l files -d '                         per line, names of input files'
complete -c mlr -l from -d '                         rather than after.  May be used more than once'
complete -c mlr -l hash-records -d '                         need to be modified'
complete -c mlr -l infer-int-as-float -s A -d '                         Cast all integers in data files to floats'
complete -c mlr -l infer-none -s S -d '                         int/float; leave them as strings'
complete -c mlr -l infer-octal -s O -d '                         default is string'
complete -c mlr -l load -d '                         the command line'
complete -c mlr -l mfrom -d '                         the verb(s), rather than after'
complete -c mlr -l mload -d '                         e. g.  `--mload *. mlr --`'
complete -c mlr -l no-dedupe-field-names -d '                         and another also named `x`, the second will be      …'
complete -c mlr -l no-fflush -d '                         record'
complete -c mlr -l no-hash-records
complete -c mlr -l norc
complete -c mlr -l nr-progress-mod -d '                         count to os. Stderr every m input records'
complete -c mlr -l ofmt -d '                         sprintf-style codes (https://pkg. go'
complete -c mlr -l ofmte -l ofmte
complete -c mlr -l ofmtf -l ofmtf
complete -c mlr -l ofmtg -l ofmtg
complete -c mlr -l records-per-batch -d '                         records in a batch size'
complete -c mlr -l s-no-comment-strip -d '                         Take command-line flags from file name, like -s, but…'
complete -c mlr -l seed -d '                         `put`/`filter` `urand`, `urandint`, and `urand32`'
complete -c mlr -l tz -d '                         variable (if any)'
complete -c mlr -s I -d '                         command line, output is written to a temp file in th…'
complete -c mlr -s n -d '                         Useful for `mlr put` with `begin`/`end` statements  …'
complete -c mlr -s s -d '                         information please see                          http…'
complete -c mlr -s x -d '                         stop the process'
complete -c mlr -l always-color -s C -d '                         normally would not'
complete -c mlr -l fail-color -d '                         `--list-color-names`) for failing cases in `mlr     …'
complete -c mlr -l help-color -d '                         `--list-color-names`) for highlights in `mlr help`  …'
complete -c mlr -l key-color -d '                         `--list-color-names`) for record keys'
complete -c mlr -l list-color-codes -d '                         such as 170 for example'
complete -c mlr -l list-color-names -d '                         `orchid` for example'
complete -c mlr -l no-color -s M
complete -c mlr -l pass-color -d '                         `--list-color-names`) for passing cases in `mlr     …'
complete -c mlr -l value-color -d '                         `--list-color-names`) for record values'
complete -c mlr -l barred -l barred-output -d '                         Prints a border around PPRINT output'
complete -c mlr -l barred-input -d '                         barred input'
complete -c mlr -l right -d 'PROFILING FLAGS These are flags for profiling Miller performance'
complete -c mlr -l cpuprofile -d '                         Create a CPU-profile file for performance analysis'
complete -c mlr -l time -d '                         the end of the execution of the program'
complete -c mlr -l traceprofile -d '                         Instructions will be printed to stderr'
complete -c mlr -l ifs
complete -c mlr -l ifs-regex
complete -c mlr -l ips
complete -c mlr -l ips-regex
complete -c mlr -l irs
complete -c mlr -l ofs
complete -c mlr -l ops
complete -c mlr -l ors
complete -c mlr -l ps
complete -c mlr -l repifs -d '                         spaces'
complete -c mlr -l rs -d 'AUXILIARY COMMANDS Available entries:   mlr aux-list   mlr hex   mlr lecat   …'
complete -c mlr -s v -d '   full transparency on the precedence and associativity rules of    Miller\'s…'
complete -c mlr -s d
complete -c mlr -s D
complete -c mlr -s w
complete -c mlr -s q
complete -c mlr -s h -l help
complete -c mlr -s f
complete -c mlr -l lo
complete -c mlr -l auto -d '                  Holds all records in memory before producing any output'
complete -c mlr -s b -d 'Nominally the fill, out-of-bounds, and blank characters will be strings of le…'
complete -c mlr -s k
complete -c mlr -s u
complete -c mlr -s l
complete -c mlr -s g
complete -c mlr -l filename
complete -c mlr -l filenum
complete -c mlr -l keys-only
complete -c mlr -l values-only -d 'It is an error to specify -k as well as -v -- to clean keys and values, leave…'
complete -c mlr -s e -d '   case: define functions/subroutines in a file you specify with -f, then cal…'
complete -c mlr -s F -d '   by the record-readers before filter/put is executed'
complete -c mlr -s W
complete -c mlr -s E
complete -c mlr -s X -o v/-d/-D -d '   only want to look at parser information'
complete -c mlr -s a
complete -c mlr -l nbins
complete -c mlr -s r -d '            statistics.  Requires -o'
complete -c mlr -o f/-r
complete -c mlr -s 1 -s 9
complete -c mlr -l millis
complete -c mlr -l micros
complete -c mlr -l nanos
complete -c mlr -l start
complete -c mlr -l step
complete -c mlr -l stop
complete -c mlr -o cr
complete -c mlr -o nf
complete -c mlr -o nr
complete -c mlr -o tr -o rt
complete -c mlr -s m
complete -c mlr -l prefix
complete -c mlr -l suffix
complete -c mlr -l fr -d '               (compute statistics on values in all field names matching regex'
complete -c mlr -l fx -d '               (compute statistics on values in all field names not matching …'
complete -c mlr -l gr -d '               (group by values in field names matching regex)'
complete -c mlr -l gx -d '               (group by values in field names not matching regex)'
complete -c mlr -l grfx
complete -c mlr -l fit -d '               the input data to compute new fit fields'
complete -c mlr -l all
complete -c mlr -l transpose
complete -c mlr -l fill-with
complete -c mlr -l min

