# mmafm
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mmafm.1
complete -c mmafm -l output -s o -d 'Send output to  file instead of standard output.  \''
complete -c mmafm -l weight -s w -d 'Set the weight axis to  R N .  \''
complete -c mmafm -l width -s W -d 'Set the width axis to  R N .  \''
complete -c mmafm -l optical-size -s O -d 'Set the optical size axis to  R N .  \''
complete -c mmafm -l style -d 'Set the style axis to  R N '
complete -c mmafm -l 1 -l 2 -l 3 -l 4 -d 'Set the first (second, third, fourth) axis to R N .  \''
complete -c mmafm -l precision -s p -d 'Round output numbers so they have at most  N digits after the decimal point'

