# mmpfb
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mmpfb.1
complete -c mmpfb -l output -s o -d '\' Send output to  file instead of standard output.  \''
complete -c mmpfb -l pfb -s b -d '\' Output a PFB font.  This is the default.  \''
complete -c mmpfb -l pfa -s a -d '\' Output a PFA font.  \''
complete -c mmpfb -l amcp-info -d '\' Do not create a font; instead, output an AMCP file for use by . M mmafm 1 '
complete -c mmpfb -l weight -s w -d '\' Set the weight axis to  R N .  \''
complete -c mmpfb -l width -s W -d '\' Set the width axis to  R N .  \''
complete -c mmpfb -l optical-size -s O -d '\' Set the optical size axis to  R N .  \''
complete -c mmpfb -l style -d '\' Set the style axis to  R N '
complete -c mmpfb -l 1 -l 2 -l 3 -l 4 -d '\' Set the first (second, third, fourth) axis to R N .  \''
complete -c mmpfb -l precision -s p -d '\' Set the output precision to R N '
complete -c mmpfb -l subrs -d '\' Limit the output font to at most R N subroutines'
complete -c mmpfb -l no-minimize
complete -c mmpfb -l minimize -d 'option (now the default) fixes this problem'

