# mptopdf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mptopdf.1
complete -c mptopdf -l metafun -d 'use the metafun format to process the file (default is mpost)'
complete -c mptopdf -l texexec -d 'use texexec (context) to process text snippets'
complete -c mptopdf -l latex -d 'use latex to process text snippets AUTHOR More information about ConTeXt and …'

