# mtx-modules
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-modules.1
complete -c mtx-modules -l convert -d 'convert source files (tex, mkii, mkiv, mp, etc. ) to \'ted\' files'
complete -c mtx-modules -l process -d 'process source files (tex, mkii, mkiv, mp, etc. ) to \'pdf\' files'
complete -c mtx-modules -l prep -d 'use original name with suffix \'prep\' appended'
complete -c mtx-modules -l direct -d 'use old method instead of extra AUTHOR More information about ConTeXt and the…'

