# mtx-youless
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-youless.1
complete -c mtx-youless -l collect -d 'collect data from device'
complete -c mtx-youless -l nobackup -d 'don\'t backup old datafile'
complete -c mtx-youless -l nofile -d 'don\'t write data to file (for checking)'
complete -c mtx-youless -l electricity -d 'collected eletricity data (p)'
complete -c mtx-youless -l gas -d 'collected gas data'
complete -c mtx-youless -l pulse -d 'collected eletricity data (s)'
complete -c mtx-youless -l host -d 'ip address of device'
complete -c mtx-youless -l auto -d 'fetch (refresh) all data every hour AUTHOR More information about ConTeXt and…'

