# mtx-fcd
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-fcd.1
complete -c mtx-fcd -l clear -d 'clear the cache'
complete -c mtx-fcd -l scan -d 'clear the cache and add given path(s)'
complete -c mtx-fcd -l add -d 'add given path(s)'
complete -c mtx-fcd -l find -d 'find given path (can be substring)'
complete -c mtx-fcd -l stub -d 'print platform stub file'
complete -c mtx-fcd -l list -d 'show roots of cached dirs'
complete -c mtx-fcd -l history
complete -c mtx-fcd -l nohistory
complete -c mtx-fcd -l help -d 'show this help AUTHOR More information about ConTeXt and the tools that come …'

