# mtx-chars
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-chars.1
complete -c mtx-chars -l xtx -d 'generate xetx-*. tex (used by xetex)'
complete -c mtx-chars -l pdf -d 'generate pdfr-def. tex (used by pdftex)'
complete -c mtx-chars -l entities -d 'generate entities table AUTHOR More information about ConTeXt and the tools t…'

