# mtx-unzip
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-unzip.1
complete -c mtx-unzip -l list -d 'list files in archive'
complete -c mtx-unzip -l extract -d 'extract files [--silent --steps] AUTHOR More information about ConTeXt and th…'

