# mtx-fonts
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-fonts.1
complete -c mtx-fonts -l convert -d 'save open type font in raw table'
complete -c mtx-fonts -l unpack -d 'save a tma file in a more readable format'
complete -c mtx-fonts -l reload -d 'generate new font database (use --force when in doubt)'
complete -c mtx-fonts -l list -d '--name: list installed fonts, filter by name [--pattern]'
complete -c mtx-fonts -l pattern -d 'filter files using pattern'
complete -c mtx-fonts -l filter -d 'key-value pairs'
complete -c mtx-fonts -l all -d 'show all found instances (combined with other flags)'
complete -c mtx-fonts -l info -d 'give more details'
complete -c mtx-fonts -l trackers -d 'enable trackers'
complete -c mtx-fonts -l statistics -d 'some info about the database'
complete -c mtx-fonts -l names -d 'use name instead of unicodes'
complete -c mtx-fonts -l simple:generate
complete -c mtx-fonts -l name
complete -c mtx-fonts -l spec
complete -c mtx-fonts -l file
complete -c mtx-fonts -l cache -d 'use specific cache (otl or otf) AUTHOR More information about ConTeXt and the…'

