# mtx-spell
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-spell.1
complete -c mtx-spell -l expand -d 'expand hunspell dics and aff files'
complete -c mtx-spell -l dictionary -d 'word file (. dics)'
complete -c mtx-spell -l specification -d 'affix specification file (. aff)'
complete -c mtx-spell -l result -d 'destination file AUTHOR More information about ConTeXt and the tools that com…'

