# mtx-server
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-server.1
complete -c mtx-server -l start -d 'start server'
complete -c mtx-server -l port -d 'port to listen to'
complete -c mtx-server -l root -d 'server root'
complete -c mtx-server -l scripts -d 'scripts sub path'
complete -c mtx-server -l index -d 'index file'
complete -c mtx-server -l auto -d 'start on own path AUTHOR More information about ConTeXt and the tools that co…'

