# mtx-package
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-package.1
complete -c mtx-package -l merge -d 'merge \'loadmodule\' into merge file AUTHOR More information about ConTeXt and …'

