# mtx-patterns
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-patterns.1
complete -c mtx-patterns -l convert -d 'generate context language files (mnemonic driven, if not given then all)'
complete -c mtx-patterns -l check -d 'check pattern file (or those used by context when no file given)'
complete -c mtx-patterns -l path -d 'source path where hyph-foo. tex files are stored'
complete -c mtx-patterns -l destination -d 'destination path'
complete -c mtx-patterns -l specification -d 'additional patterns: e. g. : =cy,hyph-cy,welsh'
complete -c mtx-patterns -l compress -d 'compress data'
complete -c mtx-patterns -l words -d 'update words in given file'
complete -c mtx-patterns -l hyphenate -d 'show hypephenated words AUTHOR More information about ConTeXt and the tools t…'

