# mtx-pdf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-pdf.1
complete -c mtx-pdf -l info -d 'show some info about the given file'
complete -c mtx-pdf -l metadata -d 'show metadata xml blob'
complete -c mtx-pdf -l formdata -d 'show formdata'
complete -c mtx-pdf -l pretty -d 'replace newlines in metadata'
complete -c mtx-pdf -l fonts -d 'show used fonts (--detail)'
complete -c mtx-pdf -l object -d 'show object'
complete -c mtx-pdf -l links -d 'show links'
complete -c mtx-pdf -l sign -d 'sign document (assumes signature template)'
complete -c mtx-pdf -l verify -d 'verify document'
complete -c mtx-pdf -l detail -d 'print detail to the console AUTHOR More information about ConTeXt and the too…'

