# mtx-cache
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-cache.1
complete -c mtx-cache -l make -d 'generate databases and formats'
complete -c mtx-cache -l erase -d 'completely remove cache'
complete -c mtx-cache -l list -d 'show cache'
complete -c mtx-cache -l fonts -d 'only wipe fonts AUTHOR More information about ConTeXt and the tools that come…'

