# mtx-bibtex
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-bibtex.1
complete -c mtx-bibtex -l toxml -d 'convert bibtex database(s) to xml'
complete -c mtx-bibtex -l tolua -d 'convert bibtex database(s) to lua'
complete -c mtx-bibtex -l search -d 'seatch bibtex database(s) AUTHOR More information about ConTeXt and the tools…'

