# mtx-grep
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-grep.1
complete -c mtx-grep -l pattern -d 'search for pattern (optional)'
complete -c mtx-grep -l count -d 'count matches only'
complete -c mtx-grep -l nocomment -d 'skip lines that start with %% or #'
complete -c mtx-grep -l noattic -d 'skip files that hh considers irrelevant'
complete -c mtx-grep -l n -d 'show at most n matches'
complete -c mtx-grep -l first -d 'only show first match'
complete -c mtx-grep -l match -d 'return the match (if it is one)'
complete -c mtx-grep -l xml -d 'pattern is lpath expression AUTHOR More information about ConTeXt and the too…'

