# mtx-watch
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-watch.1
complete -c mtx-watch -l logpath -d 'optional path for log files'
complete -c mtx-watch -l watch -d 'watch given path [--delay]'
complete -c mtx-watch -l pipe -d 'use pipe instead of execute'
complete -c mtx-watch -l delay -d 'delay between sweeps'
complete -c mtx-watch -l automachine -d 'replace /machine/ in path /servername/'
complete -c mtx-watch -l collect -d 'condense log files'
complete -c mtx-watch -l cleanup -d 'remove files in given path [--force]'
complete -c mtx-watch -l showlog -d 'show log data AUTHOR More information about ConTeXt and the tools that come w…'

