# mtx-dvi
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-dvi.1
complete -c mtx-dvi -l list -d 'list dvi commands AUTHOR More information about ConTeXt and the tools that co…'

