# mtx-fixpdf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-fixpdf.1
complete -c mtx-fixpdf -l uncompress -d 'uncompress using qpdf'
complete -c mtx-fixpdf -l validate -d 'validate using verapdf'
complete -c mtx-fixpdf -l check -d 'check verification result'
complete -c mtx-fixpdf -l convert -d 'convert using context'
complete -c mtx-fixpdf -l compare -d 'compare result with original'
complete -c mtx-fixpdf -l compactor -d 'use given compactor'
complete -c mtx-fixpdf -l standard -d 'use given standard'
complete -c mtx-fixpdf -l pattern -d 'processs files according to pattern'
complete -c mtx-fixpdf -l silent -d 'suppress messages'
complete -c mtx-fixpdf -l once -d 'run only once'
complete -c mtx-fixpdf -l resolution -d 'use this resolution when comparing AUTHOR More information about ConTeXt and …'

