# mtx-kpse
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-kpse.1
complete -c mtx-kpse -l progname -d 'mandate, set the program name (e. g.  pdftex)'
complete -c mtx-kpse -l findfile -d 'report the fully qualified path of the given file'
complete -c mtx-kpse -l findfiles -d 'report a list of all full names of the given file'
complete -c mtx-kpse -l expandpath -d 'expand the given path variable'
complete -c mtx-kpse -l expandvar -d 'expand a variable'
complete -c mtx-kpse -l expandbraces -d 'expand a complex variable specification'
complete -c mtx-kpse -l varvalue -d 'show the value of a variable'
complete -c mtx-kpse -l readablefile -d 'report if a file is readable'
complete -c mtx-kpse -l filetypes -d 'list all supported formats OPTIONS: ADDITIONAL'
complete -c mtx-kpse -l format -d 'format type'
complete -c mtx-kpse -l path -d 'path variable'
complete -c mtx-kpse -l split -d 'split result in lines AUTHOR More information about ConTeXt and the tools tha…'

