# mtx-synctex
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-synctex.1
complete -c mtx-synctex -l edit -d 'open file at line: --line=.  --editor=.  sourcefile'
complete -c mtx-synctex -l list -d 'show all areas: synctexfile'
complete -c mtx-synctex -l goto -d 'open file at position: --page=.  --x=.  --y=.  [--tolerance=] --editor='
complete -c mtx-synctex -l report -d 'show (tex) file and line: [--direct] --page=.  --x=.  --y='
complete -c mtx-synctex -l find -d 'find (pdf) page and box: [--direct] --file=.  --line='

