# mtx-vscode
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-vscode.1
complete -c mtx-vscode -l generate -d 'generate extension in sync with current version'
complete -c mtx-vscode -l program -d 'use the given binary (e. g.  codium, default: code)'
complete -c mtx-vscode -l start -d 'start vscode with extension context'
complete -c mtx-vscode -l lsfile -d 'generate language server file (work in progress) AUTHOR More information abou…'

