# mtx-install-modules
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-install-modules.1
complete -c mtx-install-modules -l list -d 'list modules'
complete -c mtx-install-modules -l installed -d 'list installed modules'
complete -c mtx-install-modules -l install -d 'install modules'
complete -c mtx-install-modules -l uninstall -d 'uninstall modules'
complete -c mtx-install-modules -l module -d 'install (zip) file(s) AUTHOR More information about ConTeXt and the tools tha…'

