# mtx-convert
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-convert.1
complete -c mtx-convert -l convertall -d 'convert all graphics on path'
complete -c mtx-convert -l inputpath -d 'original graphics path'
complete -c mtx-convert -l outputpath -d 'converted graphics path'
complete -c mtx-convert -l watch -d 'watch folders'
complete -c mtx-convert -l force -d 'force conversion (even if older)'
complete -c mtx-convert -l delay -d 'time between sweeps AUTHOR More information about ConTeXt and the tools that …'

