# mtx-texworks
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-texworks.1
complete -c mtx-texworks -l start -d '[--verbose]   start texworks'
complete -c mtx-texworks -l test -d 'report what will happen AUTHOR More information about ConTeXt and the tools t…'

