# mtx-babel
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-babel.1
complete -c mtx-babel -l language -d 'conversion language (e. g.  greek)'
complete -c mtx-babel -l structure -d 'obey given structure (e. g.  \'document\', default: \'context\')'
complete -c mtx-babel -l convert -d 'convert babel codes into utf AUTHOR More information about ConTeXt and the to…'

