# mtx-scite
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-scite.1
complete -c mtx-scite -l words -d 'convert spell-*. txt into spell-*. lua'
complete -c mtx-scite -l tree -d 'converts a tree into an html tree (--source --target --numbers)'
complete -c mtx-scite -l file -d 'converts a file into an html file (--source --target --numbers --lexer) AUTHO…'

