# mtx-ctan
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-ctan.1
complete -c mtx-ctan -l packages -d 'list available packages [--field=key|name|caption]'
complete -c mtx-ctan -l topics -d 'list available topics [--field=key|name|details]'
complete -c mtx-ctan -l details -d 'show details about package'
complete -c mtx-ctan -l pattern -d 'use this pattern, otherwise first argument AUTHOR More information about ConT…'

