# mtx-colors
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-colors.1
complete -c mtx-colors -l table -d 'show icc table AUTHOR More information about ConTeXt and the tools that come …'

