# mtx-tools
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-tools.1
complete -c mtx-tools -l disarmutfbomb -d 'remove utf bomb if present'
complete -c mtx-tools -l force -d 'remove indeed'
complete -c mtx-tools -l dirtoxml -d 'glob directory into xml'
complete -c mtx-tools -l pattern -d 'glob pattern (default: *)'
complete -c mtx-tools -l url -d 'url attribute (no processing)'
complete -c mtx-tools -l root -d 'the root of the globbed path (default: . )'
complete -c mtx-tools -l output -d 'output filename (console by default)'
complete -c mtx-tools -l recurse -d 'recurse into subdirecories'
complete -c mtx-tools -l stripname -d 'take pathpart of given pattern'
complete -c mtx-tools -l longname -d 'set name attributes to full path name'
complete -c mtx-tools -l downcase -d 'lowercase names'
complete -c mtx-tools -l showstring -d 'show unicode characters in given string'
complete -c mtx-tools -l showfile -d 'show unicode characters in given file'

