# mtx-plain
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-plain.1
complete -c mtx-plain -l make -d 'create format file'
complete -c mtx-plain -l fonts -d 'create plain font database'
complete -c mtx-plain -l run -d 'process file'
complete -c mtx-plain -l format -d 'format name (default: luatex-plain)'
complete -c mtx-plain -l engine -d 'engine to use (default: luatex)'
complete -c mtx-plain -l jit -d 'use luajittex AUTHOR More information about ConTeXt and the tools that come w…'

