# mtx-unicode
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-unicode.1
complete -c mtx-unicode -l whatever -d 'do whatever AUTHOR More information about ConTeXt and the tools that come wit…'

