# mtx-check
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-check.1
complete -c mtx-check -l check -d 'check tex file for errors AUTHOR More information about ConTeXt and the tools…'

