# mtx-metapost
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-metapost.1
complete -c mtx-metapost -l rawmp -d 'raw metapost run'
complete -c mtx-metapost -l metafun -d 'use metafun instead of plain'
complete -c mtx-metapost -l latex -d 'force --tex=latex'
complete -c mtx-metapost -l texexec -d 'force texexec usage (mkii)'
complete -c mtx-metapost -l split -d 'split single result file into pages AUTHOR More information about ConTeXt and…'

