# mtx-epub
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-epub.1
complete -c mtx-epub -l make -d 'create epub zip file'
complete -c mtx-epub -l purge -d 'remove obsolete files'
complete -c mtx-epub -l rename -d 'rename images to sane names'
complete -c mtx-epub -l svgmath -d 'convert mathml to svg'
complete -c mtx-epub -l svgstyle -d 'use given tex style for svg generation (overloads style in specification)'
complete -c mtx-epub -l all -d 'assume: --purge --rename --svgmath (for fast testing) AUTHOR More information…'

