# mtx-evohome
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-evohome.1
complete -c mtx-evohome -l collect -d 'collect data from device'
complete -c mtx-evohome -l update -d 'update data from device'
complete -c mtx-evohome -l presets -d 'file with authenciation data'
complete -c mtx-evohome -l auto -d 'fetch temperature data every hour'
complete -c mtx-evohome -l port -d 'server port when running the service, default: 8068'
complete -c mtx-evohome -l host -d 'server host when running the service, default: localhost AUTHOR More informat…'

