# mtx-flac
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-flac.1
complete -c mtx-flac -l collect -d 'collect albums in xml file'
complete -c mtx-flac -l pattern -d 'use pattern for locating files AUTHOR More information about ConTeXt and the …'

