# mtx-install
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-install.1
complete -c mtx-install -l platform -d platform
complete -c mtx-install -l server -d 'repository url (rsync://contextgarden. net)'
complete -c mtx-install -l modules -d 'extra modules (can be list or \'all\')'
complete -c mtx-install -l fonts -d 'additional fonts (can be list or \'all\')'
complete -c mtx-install -l goodies -d 'extra binaries (like scite and texworks)'
complete -c mtx-install -l install -d 'install context'
complete -c mtx-install -l update -d 'update context'
complete -c mtx-install -l erase -d 'wipe the cache'
complete -c mtx-install -l identify -d 'create list of files'
complete -c mtx-install -l secure -d 'use curl for https AUTHOR More information about ConTeXt and the tools that c…'

