# mtx-rsync
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/mtx-rsync.1
complete -c mtx-rsync -l job -d 'use given file as specification'
complete -c mtx-rsync -l dryrun -d 'show what would happen'
complete -c mtx-rsync -l force -d 'force run AUTHOR More information about ConTeXt and the tools that come with …'

