# nop
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/nop.1.gz
complete -c nop -s p -d 'Produce no output - just check the input for valid DOT'
complete -c nop -s '?' -d 'Print usage information'

