# opl2ofm
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/opl2ofm.1
complete -c opl2ofm -o help -d 'display a brief summary of syntax and options '
complete -c opl2ofm -o verbose -d 'display progress reports'
complete -c opl2ofm -o version -d 'output version information and exit'

