# ot2kpx
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ot2kpx.1
complete -c ot2kpx -o help
complete -c ot2kpx -o version
complete -c ot2kpx -o afm -o kpx
complete -c ot2kpx -o lua

