# ovp2ovf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ovp2ovf.1
complete -c ovp2ovf -o help -d 'display a brief summary of syntax and options'
complete -c ovp2ovf -o verbose -d 'display progress reports'
complete -c ovp2ovf -o version -d 'output version information and exit'

