# pagelayoutapi
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/pagelayoutapi.1
complete -c pagelayoutapi -l help -d 'Prints a help message'

