# pandoc-server
# Autogenerated from man page /nix/store/l57904kywklrj51x20xcf6gdm84m2x9s-pandoc-cli-3.6/share/man/man1/pandoc-server.1.gz
complete -c pandoc-server -l port -d 'HTTP port on which to run the server.  Default: 3030'
complete -c pandoc-server -l timeout -d 'Timeout in seconds, after which a conversion is killed.  Default: 2'
complete -c pandoc-server -l help -d 'Print this help'
complete -c pandoc-server -l version -d 'Print version'

