# parted
# Autogenerated from man page /nix/store/3zs7n8svjjg8b5illvg5gais78pcp3fj-parted-3.6-man/share/man/man8/parted.8.gz
complete -c parted -s h -l help -d 'displays a help message'
complete -c parted -s l -l list -d 'lists partition layout on all block devices'
complete -c parted -s m -l machine -d 'displays machine parseable output'
complete -c parted -s j -l json -d 'displays JSON output'
complete -c parted -s s -l script -d 'never prompts for user intervention'
complete -c parted -s f -l fix -d 'automatically answer "fix" to exceptions in script mode'
complete -c parted -s v -l version -d 'displays the version'
complete -c parted -s a -l align -d 'Set alignment for newly created partitions, valid alignment types are: . RS'

