# pdfattach
# Autogenerated from man page /nix/store/lj6a48mgzqfdv42bjyizfifci1wmwzxq-poppler-utils-24.02.0/share/man/man1/pdfattach.1.gz
complete -c pdfattach -o replace -d 'Replace embedded file with same name (if it exists)'
complete -c pdfattach -s v -d 'Print copyright and version information'
complete -c pdfattach -s h -d 'Print usage information.  ( -help and'
complete -c pdfattach -l help -d 'are equivalent. ) EXIT CODES'

