# pdfatfi
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/pdfatfi.1
complete -c pdfatfi -l help -d 'Show help text'
complete -c pdfatfi -l version -d 'Print version number'

