# pdfjadetex
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/pdfjadetex.1
complete -c pdfjadetex -l fmt -d 'Use  format as the name of the format to be used, instead of the name by whic…'
complete -c pdfjadetex -l help -d 'Print help message and exit'
complete -c pdfjadetex -l ini -d 'Be  pdfinitex , for dumping formats; this is implicitly true if the program i…'
complete -c pdfjadetex -l interaction -d 'Sets the interaction mode'
complete -c pdfjadetex -l ipc -d 'Send DVI or PDF output to a socket as well as the usual output file'
complete -c pdfjadetex -l ipc-start -d 'As  --ipc , and starts the server at the other end as well'
complete -c pdfjadetex -l kpathsea-debug -d 'Sets path searching debugging flags according to the bitmask'
complete -c pdfjadetex -l maketex -d 'Enable . RI mktex fmt , where  fmt must be one of  tex or R tfm '
complete -c pdfjadetex -l no-maketex -d 'Disable . RI mktex fmt , where  fmt must be one of  tex or R tfm '
complete -c pdfjadetex -l output-comment -d 'Use  string for the DVI file comment instead of the date'
complete -c pdfjadetex -l progname -d 'Pretend to be program R name '
complete -c pdfjadetex -l shell-escape -d 'Enable the  write18command construct'
complete -c pdfjadetex -l version

