# pdfseparate
# Autogenerated from man page /nix/store/lj6a48mgzqfdv42bjyizfifci1wmwzxq-poppler-utils-24.02.0/share/man/man1/pdfseparate.1.gz
complete -c pdfseparate -s f -d 'Specifies the first page to extract'
complete -c pdfseparate -s l -d 'Specifies the last page to extract'
complete -c pdfseparate -s v -d 'Print copyright and version information'
complete -c pdfseparate -s h -d 'Print usage information.  ( -help and'
complete -c pdfseparate -l help -d 'are equivalent. ) EXAMPLE pdfseparate sample. pdf sample-%d. pdf'

