# pdfunite
# Autogenerated from man page /nix/store/lj6a48mgzqfdv42bjyizfifci1wmwzxq-poppler-utils-24.02.0/share/man/man1/pdfunite.1.gz
complete -c pdfunite -s v -d 'Print copyright and version information'
complete -c pdfunite -s h -d 'Print usage information.  ( -help and'
complete -c pdfunite -l help -d 'are equivalent. ) EXAMPLE pdfunite sample1. pdf sample2. pdf sample. pdf'

