# pedigree
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/pedigree.1
complete -c pedigree -s c -d 'The configuration file to read along with the system-wide and user\'s configur…'
complete -c pedigree -s d -d 'Debug mode on'
complete -c pedigree -s o -o output_file -d 'The ouput file instead of input_file. tex'
complete -c pedigree -s s -o start_id -d 'If this option is selected, the pedigree is constructed starting from the nod…'

