# pee
# Autogenerated from man page /nix/store/8231k60pm54p9inml853jlyxr22g94z0-moreutils-0.70/share/man/man1/pee.1.gz
complete -c pee -l ignore-sigpipe -l no-ignore-sigpipe -d 'Do (not) ignore SIGPIPE'
complete -c pee -l ignore-write-errors -l no-ignore-write-errors -d 'Do (not) ignore write errors'

