# peekfd
# Autogenerated from man page /nix/store/ci7s9flis9dn31lh1pjy4flz1vhllx9r-psmisc-23.7/share/man/man1/peekfd.1.gz
complete -c peekfd -s 8 -d 'Do no post-processing on the bytes being read or written'
complete -c peekfd -s n -d 'Do not display headers indicating the source of the bytes dumped'
complete -c peekfd -s c -d 'Also dump the requested file descriptor activity in any new child processes t…'
complete -c peekfd -s d -d 'Remove duplicate read/writes from the output'
complete -c peekfd -s v -d 'Display a version string'
complete -c peekfd -s h -d 'Display a help message.  FILES /proc/ * /fd'

