# pkfix-helper
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/pkfix-helper.1
complete -c pkfix-helper -s h -l help -d 'Display usage information and exit'
complete -c pkfix-helper -s v -l verbose -d 'Increase the amount of status information that pkfix-helper displays as it ru…'
complete -c pkfix-helper -s f -l force -d 'Force pkfix-helper to associate a specific font with a given font name appear…'
complete -c pkfix-helper -s p -l ps -d 'Create a PostScript file called filename'
complete -c pkfix-helper -s t -l tex -d 'Create a Plain TeX file called filename'
complete -c pkfix-helper -s k -l keep -d 'Do not substitute a vector font for bitmapped font fontspec (\\f(CW\\*(C`Fa\\*(C…'
complete -c pkfix-helper -s 1 -l no-repeats -d 'Prevent pkfix-helper from associating the same fontspec with more than one dv…'
complete -c pkfix-helper -s q -l quiet -d 'Instruct pkfix-helper to produce no output during its run except for error an…'
complete -c pkfix-helper -s C -l cache -d 'Speed up \\s-1TFM\\s0 file processing by caching character metrics into file fi…'
complete -c pkfix-helper -s i -l include -d 'Add fontspec to the list of font specifications against which pkfix-helper co…'
complete -c pkfix-helper -s x -l exclude -d 'Remove all font specifications matching regular expression regexp from pkfix-…'

