# pktogf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/pktogf.1
complete -c pktogf -s v -d 'switch is given, pktogf operates silently.   With'

