# pmxchords
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/pmxchords.1
complete -c pmxchords -s v -d 'output program name and version number, and quit'
complete -c pmxchords -s h -d 'output usage summary and quit'
complete -c pmxchords -s s -d 'stop after first step (of producing a temporary pmx file with transposed chor…'

