# pp
# Autogenerated from man page /nix/store/57wcs1z9ymi0qkjm21951sxs3ibijmkv-nss-3.101.2-man/share/man/man1/pp.1.gz
complete -c pp -s t -d 'specify the input, one of {private-key | public-key | certificate | certifica…'
complete -c pp -s a -d 'Input is in ascii encoded form (RFC1113)'
complete -c pp -s i -d 'Define an input file to use (default is stdin)'
complete -c pp -s o -d 'Define an output file to use (default is stdout)'
complete -c pp -s u -d 'Use UTF-8 (default is to show non-ascii as . )'
complete -c pp -s w -d 'Don\\*(Aqt wrap long output lines'

