# ppltotf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ppltotf.1
complete -c ppltotf -o kanji -d 'Sets the input Japanese Kanji code'

