# prepmx
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/prepmx.1
complete -c prepmx -s b -d 'disable unbeamVocal'
complete -c prepmx -s c -d 'disable doChords'
complete -c prepmx -s D -d 'enable debugMode'
complete -c prepmx -s f -d 'enable solfaNoteNames'
complete -c prepmx -s i -d 'enable ignoreErrors'
complete -c prepmx -s m -d 'disable doLyrics'
complete -c prepmx -s n -d 'enable instrumentNames'
complete -c prepmx -s t -d 'disable doUptext'
complete -c prepmx -s u -d 'disable uptextOnRests'
complete -c prepmx -s v -d 'enable beVerbose'
complete -c prepmx -s w -d 'enable pedanticWarnings'
complete -c prepmx -s H -d 'print enabled status of all options EXIT STATUS If no error was found, prepmx…'

