# prezip-bin
# Autogenerated from man page /nix/store/18f1x8cvrxpc67872lkxrgjf4c9hb5fc-aspell-0.60.8.1/share/man/man1/prezip-bin.1.gz
complete -c prezip-bin -s V -d 'Display prezip-bin version number to standard output'
complete -c prezip-bin -s d -d 'Read a compressed word list from standard input and decompress it to standard…'
complete -c prezip-bin -s z -d 'Read a binary word list from standard input and compress it to standard output'

