# prtstat
# Autogenerated from man page /nix/store/ci7s9flis9dn31lh1pjy4flz1vhllx9r-psmisc-23.7/share/man/man1/prtstat.1.gz
complete -c prtstat -s r -l raw -d 'Print the information in raw format'
complete -c prtstat -s V -l version -d 'Show the version information for prtstat .  FILES'

