# prune
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/prune.1.gz
complete -c prune -s n -d 'Specifies name of node to prune'
complete -c prune -s N -d 'Specifies attribute that will be set (or changed if it exists) for any pruned…'
complete -c prune -s v -d 'Verbose output'
complete -c prune -s h -s '?' -d 'Prints the usage and exits.  EXAMPLES An input graph test. gv of the form'

