# psbook
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/psbook.1
complete -c psbook -s s -d 'option selects the size of signature which will be used'
complete -c psbook -s q -d 'option suppresses this.  AUTHOR Written by Angus J.  C.  Duggan'

