# psjoin
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/psjoin.1
complete -c psjoin -s a
complete -c psjoin -s s
complete -c psjoin -s p
complete -c psjoin -s h

