# pslog
# Autogenerated from man page /nix/store/ci7s9flis9dn31lh1pjy4flz1vhllx9r-psmisc-23.7/share/man/man1/pslog.1.gz
complete -c pslog -s V -d 'Display version information.  SEE ALSO pgrep (1), ps (1), pwdx (1)'

