# psnup
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/psnup.1
complete -c psnup -s w -d 'option gives the paper width, and the'
complete -c psnup -s h -d 'option gives the paper height, specified in pt , mm , cm , or in .  The '
complete -c psnup -s p -d 'option can be used instead, to set the paper size; otherwise a default value …'
complete -c psnup -s W
complete -c psnup -s H -d and
complete -c psnup -s P -d 'options set the input paper size, if it is different from the output size'
complete -c psnup -s l -d 'option should be used for pages which are in landscape orientation (rotated 9…'
complete -c psnup -s r -d 'option should be used for pages which are in seascape orientation (rotated 90…'
complete -c psnup -s f -d 'option should be used for pages which have the width and height interchanged,…'
complete -c psnup -s c -d 'option changes the order to `column-major\', where successive pages are placed…'
complete -c psnup -s m -d option
complete -c psnup -s b -d 'option is used to specify an additional margin around each page on a sheet'
complete -c psnup -s d -d 'option draws a line around the border of each page, of the specified width'
complete -c psnup -s s -d 'option.  This is useful to merge pages which are already reduced'
complete -c psnup -s n -d 'can also be used, for compatibility with other n-up programs'
complete -c psnup -s q -d 'option suppresses this'

