# pspell-config
# Autogenerated from man page /nix/store/18f1x8cvrxpc67872lkxrgjf4c9hb5fc-aspell-0.60.8.1/share/man/man1/pspell-config.1.gz
complete -c pspell-config -l version -d 'outputs version information about the installed pspell'
complete -c pspell-config -l datadir -d 'displays the data directory'
complete -c pspell-config -l pkgdatadir -d 'displays the aspell package directory AUTHOR This manual page was written by …'

