# psresize
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/psresize.1
complete -c psresize -s w -d 'option gives the output paper width, and the'
complete -c psresize -s h -d 'option gives the output paper height, normally specified in cm or in to conve…'
complete -c psresize -s p -d 'option can be used instead, to set the paper size; otherwise a default value …'
complete -c psresize -s W -d 'option gives the input paper width, and the'
complete -c psresize -s H -d 'option gives the input paper height.  The '
complete -c psresize -s P -d 'option can be used instead, to set the paper size; otherwise a default value …'
complete -c psresize -s q -d 'option suppresses this'

