# psselect
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/psselect.1
complete -c psselect -s e -d 'option selects all of the even pages; it may be used in conjunction with the …'
complete -c psselect -s o -d 'option selects all of the odd pages; it may be used in conjunction with the o…'
complete -c psselect -s p -d 'option specifies the pages which are to be selected'
complete -c psselect -s r -d 'option causes psselect to output the selected pages in reverse order'
complete -c psselect -s q -d 'option suppresses this'

