# pstops
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/pstops.1
complete -c pstops -s w -d 'option gives the width which is used by the w dimension specifier, and the'
complete -c pstops -s h -d 'option gives the height which is used by the h dimension specifier'
complete -c pstops -s p -d 'option can be used as an alternative, to set the paper size.  See paper (1)'
complete -c pstops -s b -d 'option prevents any bind operators in the PostScript prolog from binding'
complete -c pstops -s q -d 'option suppresses this'

