# ptekf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ptekf.1
complete -c ptekf -s j -d 'Specify output encoding ISO-2022-JP'
complete -c ptekf -s s -d 'Specify output encoding Shift_JIS'
complete -c ptekf -s e -d 'Specify output encoding EUC-JP'
complete -c ptekf -s u -d 'Specify output encoding UTF-8'
complete -c ptekf -s J -d 'Specify input encoding ISO-2022-JP'
complete -c ptekf -s S -d 'Specify input encoding Shift_JIS'
complete -c ptekf -s E -d 'Specify input encoding EUC-JP'
complete -c ptekf -s U -d 'Specify input encoding UTF-8'
complete -c ptekf -s g -l guess -d 'Guess the input encoding (no conversion)'
complete -c ptekf -s G -d 'Guess the input encoding and output to stdout or files'
complete -c ptekf -s b -l buffer -d 'Output internal buffer without code conversion'
complete -c ptekf -s v -l version -d 'Print version number'
complete -c ptekf -s h -l help -d 'Print help message'

