# ptftopl
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ptftopl.1
complete -c ptftopl -o kanji -d 'Sets the output Japanese Kanji code'

