# purifyeps
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/purifyeps.1
complete -c purifyeps -l help -d 'Display \\*(L"Usage\\*(R" and \\*(L"Options\\*(R" from the purifyeps documentation'
complete -c purifyeps -s V -l version -d 'Display the purifyeps version number, copyright, and license'
complete -c purifyeps -l fontmap -d 'Specify the name of a file that tells purifyeps how to map from TeX font name…'
complete -c purifyeps -l make-man -l section -d 'Automatically create a Unix man page for purifyeps'

