# rad-id
# Autogenerated from man page /nix/store/0nb4b261ss8g76aacbxyj8w7nxzb30xb-radicle-node-1.1.0/share/man/man1/rad-id.1.gz
complete -c rad-id -l title
complete -c rad-id -l description
complete -c rad-id -l delegate
complete -c rad-id -l rescind
complete -c rad-id -l threshold
complete -c rad-id -l visibility
complete -c rad-id -l allow
complete -c rad-id -l payload
complete -c rad-id -l no-confirm
complete -c rad-id -l repo
complete -c rad-id -l quiet -s q
complete -c rad-id -l help

