# rad-patch
# Autogenerated from man page /nix/store/0nb4b261ss8g76aacbxyj8w7nxzb30xb-radicle-node-1.1.0/share/man/man1/rad-patch.1.gz
complete -c rad-patch -l patch -s p
complete -c rad-patch -l verbose -s v
complete -c rad-patch -l revision -s r
complete -c rad-patch -l message -s m
complete -c rad-patch -l all
complete -c rad-patch -l archived
complete -c rad-patch -l merged
complete -c rad-patch -l open
complete -c rad-patch -l draft
complete -c rad-patch -l authored
complete -c rad-patch -l author
complete -c rad-patch -l undo
complete -c rad-patch -l p
complete -c rad-patch -l hunk
complete -c rad-patch -l accept
complete -c rad-patch -l reject
complete -c rad-patch -l unified -s U
complete -c rad-patch -l delete -s d
complete -c rad-patch -l no-message
complete -c rad-patch -l name
complete -c rad-patch -l force -s f
complete -c rad-patch -l reply-to

