# rifle
# Autogenerated from man page /nix/store/kgsk7k82ndwwbxfydzc0l45w5zdrwqg7-ranger-1.9.4/share/man/man1/rifle.1.gz
complete -c rifle -s f -d 'Specify flags for opening the files'
complete -c rifle -s l -d 'List all possible ways to open the specified files'
complete -c rifle -s p -d 'Pick a method to open the files'
complete -c rifle -s w -d 'Open the files with the program \\s-1PROGRAM\\s0'
complete -c rifle -s c -d 'Read configuration from \\s-1CONFIG_FILE\\s0, instead of the default'

