# rmiregistry
# Autogenerated from man page /nix/store/5yii18di89wpxcffk3cihpzfdrzw54gl-openjdk-21.0.7+6/share/man/man1/rmiregistry.1
complete -c rmiregistry -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry -s J -s J -d 'Java interpreter'

