# rubikrotation
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/rubikrotation.1
complete -c rubikrotation -s h -d 'displays the help info and exits'
complete -c rubikrotation -s v -d 'displays the version info and exits'
complete -c rubikrotation -s i -d 'defines the input filename'
complete -c rubikrotation -s o -d 'defines the output filename'

