# scalar
# Autogenerated from man page /nix/store/fxcgpjpzqlk44b70f4smyad6y6jnw8cw-git-with-svn-2.49.0/share/man/man1/scalar.1.gz
complete -c scalar -s C
complete -c scalar -s c
complete -c scalar -l full-clone -d 'git sparse-checkout set to expand the set of directories you want to see, or …'
complete -c scalar -s b -l branch
complete -c scalar -l single-branch
complete -c scalar -l src
complete -c scalar -l no-src -d 'to place the cloned repository directly in the <enlistment> directory'
complete -c scalar -l tags
complete -c scalar -l no-tags -d 'to avoid fetching tags in scalar clone and to configure the repository to avo…'

