# serialver
# Autogenerated from man page /nix/store/5yii18di89wpxcffk3cihpzfdrzw54gl-openjdk-21.0.7+6/share/man/man1/serialver.1
complete -c serialver -o classpath -d 'Sets the search path for application classes and resources'
complete -c serialver -o Joption -d 'Passes the specified option to the Java Virtual Machine, where option is one …'
complete -c serialver -o 'J-Djava.security.manager' -d 'When necessary, a security policy can be specified with the following option:'
complete -c serialver -o 'J-Djava.security.policy'

