# skopeo-list-tags
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo-list-tags.1.gz
complete -c skopeo-list-tags -l authfile -d 'Path of the authentication file'
complete -c skopeo-list-tags -l creds
complete -c skopeo-list-tags -l cert-dir -d 'Use certificates at path (*. crt, *. cert, *. key) to connect to the registry'
complete -c skopeo-list-tags -l help -s h -d 'Print usage statement'
complete -c skopeo-list-tags -l no-creds -d 'Access the registry anonymously'
complete -c skopeo-list-tags -l registry-token -d 'Bearer token for accessing the registry'
complete -c skopeo-list-tags -l retry-times -d 'The number of times to retry'
complete -c skopeo-list-tags -l retry-delay -d 'Fixed delay between retries'
complete -c skopeo-list-tags -l tls-verify -d 'Require HTTPS and verify certificates when talking to the container registry …'
complete -c skopeo-list-tags -l username -d 'The username to access the registry'
complete -c skopeo-list-tags -l password -d 'The password to access the registry'

