# skopeo-standalone-sign
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo-standalone-sign.1.gz
complete -c skopeo-standalone-sign -l help -s h -d 'Print usage statement'
complete -c skopeo-standalone-sign -l output -s o -d 'Write signature to output file'
complete -c skopeo-standalone-sign -l passphrase-file -d 'The passphare to use when signing with the key ID from --sign-by'

