# skopeo-delete
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo-delete.1.gz
complete -c skopeo-delete -l authfile -d 'Path of the authentication file'
complete -c skopeo-delete -l creds -d 'Credentials for accessing the registry'
complete -c skopeo-delete -l cert-dir -d 'Use certificates at path (*. crt, *. cert, *. key) to connect to the registry'
complete -c skopeo-delete -l daemon-host -d 'Use docker daemon host at host (docker-daemon: transport only)'
complete -c skopeo-delete -l help -s h -d 'Print usage statement'
complete -c skopeo-delete -l no-creds -d 'Access the registry anonymously'
complete -c skopeo-delete -l registry-token -d 'Bearer token for accessing the registry'
complete -c skopeo-delete -l retry-times -d 'The number of times to retry'
complete -c skopeo-delete -l retry-delay -d 'Fixed delay between retries'
complete -c skopeo-delete -l shared-blob-dir -d 'Directory to use to share blobs across OCI repositories'
complete -c skopeo-delete -l tls-verify -d 'Require HTTPS and verify certificates when talking to the container registry …'
complete -c skopeo-delete -l username -d 'The username to access the registry'
complete -c skopeo-delete -l password -d 'The password to access the registry'

