# skopeo-logout
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo-logout.1.gz
complete -c skopeo-logout -l authfile -d 'Path of the authentication file'
complete -c skopeo-logout -l compat-auth-file -d 'Instead of updating the default credentials file, update the one at path, and…'
complete -c skopeo-logout -l all -s a -d 'Remove the cached credentials for all registries in the auth file'
complete -c skopeo-logout -l help -s h -d 'Print usage statement'
complete -c skopeo-logout -l tls-verify -d 'Require HTTPS and verify certificates when talking to the container registry …'

