# skopeo-generate-sigstore-key
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo-generate-sigstore-key.1.gz
complete -c skopeo-generate-sigstore-key -l help -s h -d 'Print usage statement'
complete -c skopeo-generate-sigstore-key -l output-prefix -d 'Mandatory.  Path prefix for the output keys (prefix. private and prefix. pub)'
complete -c skopeo-generate-sigstore-key -l passphrase-file -d 'The passphare to use to encrypt the private key'

