# skopeo
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo.1.gz
complete -c skopeo -l command-timeout -d 'Timeout for the command execution'
complete -c skopeo -l debug -d 'enable debug output'
complete -c skopeo -l help -s h -d 'Show help'
complete -c skopeo -l insecure-policy -d 'Adopt an insecure, permissive policy that allows anything'
complete -c skopeo -l override-arch -d 'Use arch instead of the architecture of the machine for choosing images'
complete -c skopeo -l override-os -d 'Use OS instead of the running OS for choosing images'
complete -c skopeo -l override-variant -d 'Use variant instead of the running architecture variant for choosing images'
complete -c skopeo -l policy -d 'Path to a policy'
complete -c skopeo -l 'registries.d' -d 'Use registry configuration files in dir (e. g'
complete -c skopeo -l tmpdir -d 'Directory used to store temporary files.  Defaults to /var/tmp'
complete -c skopeo -l version -s v -d 'Print the version number'

