# skopeo-standalone-verify
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo-standalone-verify.1.gz
complete -c skopeo-standalone-verify -l help -s h -d 'Print usage statement'
complete -c skopeo-standalone-verify -l public-key-file -d 'File containing the public keys to use when verifying signatures'

