# skopeo-manifest-digest
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo-manifest-digest.1.gz
complete -c skopeo-manifest-digest -l help -s h -d 'Print usage statement'

