# skopeo-sync
# Autogenerated from man page /nix/store/n402xgh2226qxa81nrjcpc5pxm4zc80c-skopeo-1.18.0-man/share/man/man1/skopeo-sync.1.gz
complete -c skopeo-sync -l all -s a -d 'If one of the images in src refers to a list of images, instead of copying ju…'
complete -c skopeo-sync -l authfile -d 'Path of the authentication file'
complete -c skopeo-sync -l src-authfile -d 'Path of the authentication file for the source registry'
complete -c skopeo-sync -l dest-authfile -d 'Path of the authentication file for the destination registry'
complete -c skopeo-sync -l dry-run -d 'Run the sync without actually copying data to the destination'
complete -c skopeo-sync -l src -s s
complete -c skopeo-sync -l dest -s d
complete -c skopeo-sync -l format -s f
complete -c skopeo-sync -l help -s h -d 'Print usage statement'
complete -c skopeo-sync -l scoped
complete -c skopeo-sync -l append-suffix
complete -c skopeo-sync -l digestfile -d 'After copying the images from source, write the digest of the resulting image…'
complete -c skopeo-sync -l preserve-digests -d 'Preserve the digests during copying.  Fail if the digest cannot be preserved'
complete -c skopeo-sync -l remove-signatures
complete -c skopeo-sync -l sign-by -d 'Add a âsimple signingâ signature using that key ID for an image name corr…'
complete -c skopeo-sync -l sign-by-sigstore -d 'Add a sigstore signature based on the options in the specified containers sig…'
complete -c skopeo-sync -l sign-by-sigstore-private-key -d 'Add a sigstore signature using a private key at path for an image name corres…'
complete -c skopeo-sync -l sign-passphrase-file -d 'The passphare to use when signing with --sign-by or --sign-by-sigstore-privat…'
complete -c skopeo-sync -l src-creds
complete -c skopeo-sync -l dest-creds
complete -c skopeo-sync -l src-cert-dir
complete -c skopeo-sync -l src-no-creds
complete -c skopeo-sync -l src-tls-verify
complete -c skopeo-sync -l dest-cert-dir
complete -c skopeo-sync -l dest-no-creds
complete -c skopeo-sync -l dest-tls-verify
complete -c skopeo-sync -l src-registry-token
complete -c skopeo-sync -l dest-registry-token
complete -c skopeo-sync -l retry-times -d 'The number of times to retry'
complete -c skopeo-sync -l retry-delay -d 'Fixed delay between retries'
complete -c skopeo-sync -l keep-going -d 'If any errors occur during copying of images, those errors are logged and the…'
complete -c skopeo-sync -l src-username -d 'The username to access the source registry'
complete -c skopeo-sync -l src-password -d 'The password to access the source registry'
complete -c skopeo-sync -l dest-username -d 'The username to access the destination registry'
complete -c skopeo-sync -l dest-password -d 'The password to access the destination registry'

