# spix
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/spix.1
complete -c spix -s n -l dry-run -d 'Print the commands that would be executed, but do not execute them'
complete -c spix -s h -l help -d 'Print help, and exit'
complete -c spix -l version -d 'Print version, and exit.  EXAMPLES Let foo. tex be the following file'

