# splitindex
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/splitindex.1
complete -c splitindex -s h -l help -d 'show this help and terminate'
complete -c splitindex -s m -l makeindex -d 'call PROGNAME instead of default `makeindex\''
complete -c splitindex -s i -l identify -d 'use regular EXPRESSION to match entries (see also option --resultis and --suf…'
complete -c splitindex -s r -l resultis -d 'create line to be written from PATTERN after matching lines (see also option …'
complete -c splitindex -s s -l suffixis -d 'create suffix to be used from PATTERN after matching lines (see also option -…'
complete -c splitindex -s v -l verbose -d 'be more verbose (can be used multiple to increase verbosity)'
complete -c splitindex -l version -d 'show version and terminate COPYRIGHT Copyright © 2002 Markus Kohm <kohm@gmx'

