# sponge
# Autogenerated from man page /nix/store/8231k60pm54p9inml853jlyxr22g94z0-moreutils-0.70/share/man/man1/sponge.1.gz
complete -c sponge -s a -d 'Replace the file with a new file that contains the file\\*(Aqs original conten…'

