# srcredact
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/srcredact.1
complete -c srcredact -s c -d 'Use the given pattern for comment lines to search for guards instead of the d…'
complete -c srcredact -s d -d 'Debug mode on'
complete -c srcredact -s e -d 'Extract the contents for the current audience into the file file'
complete -c srcredact -s h -d 'Print help information and exit'
complete -c srcredact -s l -d 'List all audiences set in the file (one per line) and exit'
complete -c srcredact -s u -d 'Take a edited file intended for the audience (the second non-option argument)…'
complete -c srcredact -s v -d 'Print version information and exit'

