# stdiscosrv
# Autogenerated from man page /nix/store/riz37x47h6c98m9bwzrm81bp7cm5ip4v-syncthing-1.29.5/share/man/man1/stdiscosrv.1.gz
complete -c stdiscosrv -l debug -d 'Enable debug output'
complete -c stdiscosrv -l http -d 'Listen on HTTP (behind an HTTPS proxy)'
complete -c stdiscosrv -l version -d 'Print the current version number and exit'
complete -c stdiscosrv -l compression -d 'Enable GZIP compression of HTTP responses'
complete -c stdiscosrv -l cert -d 'Certificate file (default â. /cert. pemâ).  Unused in âhttp mode'
complete -c stdiscosrv -l key -d 'Key file (default â. /key. pemâ).  Unused in âhttp mode'
complete -c stdiscosrv -l listen -d 'Listen address (default â:8443â)'
complete -c stdiscosrv -l metrics-listen -d 'Prometheus compatible metrics endpoint listen address (default disabled)'
complete -c stdiscosrv -l db-dir -d 'Database directory, where data is stored (default â. â)'
complete -c stdiscosrv -l db-flush-interval -d 'Interval at which the in-memory database is flushed to disk (default â5mâ)'

