# strelaysrv
# Autogenerated from man page /nix/store/riz37x47h6c98m9bwzrm81bp7cm5ip4v-syncthing-1.29.5/share/man/man1/strelaysrv.1.gz
complete -c strelaysrv -o debug -d 'Enable debug output'
complete -c strelaysrv -o ext-address -d 'An optional address to advertising as being available on'
complete -c strelaysrv -o global-rate -d 'Global rate limit, in bytes/s'
complete -c strelaysrv -o keys -d 'Directory where cert. pem and key. pem is stored (default â. â)'
complete -c strelaysrv -o listen -d 'Protocol listen address (default â:22067â)'
complete -c strelaysrv -o message-timeout -d 'Maximum amount of time we wait for relevant messages to arrive (default 1m0s)'
complete -c strelaysrv -o nat -d 'Use UPnP/NAT-PMP to acquire external port mapping'
complete -c strelaysrv -o nat-lease -d 'NAT lease length in minutes (default 60)'
complete -c strelaysrv -o nat-renewal -d 'NAT renewal frequency in minutes (default 30)'
complete -c strelaysrv -o nat-timeout -d 'NAT discovery timeout in seconds (default 10)'
complete -c strelaysrv -o network-timeout -d 'Timeout for network operations between the client and the relay'
complete -c strelaysrv -o per-session-rate -d 'Per session rate limit, in bytes/s'
complete -c strelaysrv -o ping-interval -d 'How often pings are sent (default 1m0s)'
complete -c strelaysrv -o pools -d 'Comma separated list of relay pool addresses to join (default â\\X\'tty: link…'
complete -c strelaysrv -o pprof -d 'Enable the built in profiling on the status server'
complete -c strelaysrv -o protocol -d 'Protocol used for listening'
complete -c strelaysrv -o provided-by -d 'An optional description about who provides the relay'
complete -c strelaysrv -o status-srv -d 'Listen address for status service (blank to disable) (default â:22070â)'
complete -c strelaysrv -o token -d 'Token to restrict access to the relay (optional).  Disables joining any pools'
complete -c strelaysrv -o version -d 'Show version'
complete -c strelaysrv -s A -s p -l dport -s j -l to-port

