# t1ascii
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/t1ascii.1
complete -c t1ascii -l line-length -s l -d 'Set the maximum length of encrypted lines in the output to  num'
complete -c t1ascii -l warnings -s w -d 'Warn when the input font contains lines longer than 255 characters'

