# t1asm
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/t1asm.1
complete -c t1asm -l pfa -s a -d 'Output in PFA (ASCII) format'
complete -c t1asm -l pfb -s b -d 'Output in PFB (binary) format.  This is the default'
complete -c t1asm -l block-length -s l -d 'PFB only: Set the maximum output block length to  num'
complete -c t1asm -l line-length -d 'PFA only: Set the maximum length of encrypted lines in the output to num'

