# t1binary
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/t1binary.1
complete -c t1binary -l block-length -s l -d 'Set the maximum length of sections in PFB output to length'

