# t1dotlessj
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/t1dotlessj.1
complete -c t1dotlessj -l output -s o -d 'Send output to  file instead of standard output.  \' . Sp'
complete -c t1dotlessj -l pfb -s b -d 'Output a PFB font.   This is the default.  \' . Sp'
complete -c t1dotlessj -l pfa -s a -d 'Output a PFA font.  \' . Sp'
complete -c t1dotlessj -l name -s n -d 'Set the output font\'s PostScript name to R name '
complete -c t1dotlessj -s q -l quiet -d 'Do not generate any error messages.  \' . Sp'
complete -c t1dotlessj -s h -l help -d 'Print usage information and exit.  \' . Sp'
complete -c t1dotlessj -s v -l version -d 'Print the version number and some short non-warranty information and exit'

