# t1rawafm
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/t1rawafm.1
complete -c t1rawafm -l output -s o -d 'Send output to  file instead of standard output.  \' . Sp'
complete -c t1rawafm -s h -l help -d 'Print usage information and exit.  \' . Sp'
complete -c t1rawafm -l version -d 'Print the version number and some short non-warranty information and exit'

