# t1reencode
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/t1reencode.1
complete -c t1reencode -l encoding -s e -d 'Read the encoding from R file , which must contain an encoding in '
complete -c t1reencode -l encoding-text -s E -d 'Use the encoding in the  text argument, which must be formatted as a '
complete -c t1reencode -l name -s n -d 'Set the output font\'s PostScript name to R name '
complete -c t1reencode -l full-name -s N -d 'Set the output font\'s FullName to R name '
complete -c t1reencode -l output -s o -d 'Send output to  file instead of standard output.  \' . Sp'
complete -c t1reencode -l pfb -s b -d 'Output a PFB font.   This is the default.  \' . Sp'
complete -c t1reencode -l pfa -s a -d 'Output a PFA font.  \' . Sp'
complete -c t1reencode -s h -l help -d 'Print usage information and exit.  \' . Sp'
complete -c t1reencode -l version -d 'Print the version number and some short non-warranty information and exit'
complete -c t1reencode -s f -d 'option).   The new font will be called WarnockPro-RegularOsF'

