# t1testpage
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/t1testpage.1
complete -c t1testpage -s g -l glyph -d 'Print only glyphs matching R glyphs '
complete -c t1testpage -s s -l smoke -d 'Print smoke proofs, one glyph per page.   This option is preliminary.  \' . Sp'
complete -c t1testpage -s o -l output -d 'Write the output proof to  file instead of the standard output.  \' . Sp'
complete -c t1testpage -s h -l help -d 'Print usage information and exit.  \' . Sp'
complete -c t1testpage -s v -l version -d 'Print the version number and some short non-warranty information and exit'

