# texconfig
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texconfig.1
complete -c texconfig -s P -d 'option is given'
complete -c texconfig -s O -d 'option in dvips(1)'

