# texdiff
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texdiff.1
complete -c texdiff -l nofloats -s n -d 'If given, skips contents of figure environments, but does show insertions and…'

