# texdirflatten
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texdirflatten.1
complete -c texdirflatten -l file -s f -d 'Specifies input (La)TeX file'
complete -c texdirflatten -l onetex -s 1 -d 'If specified, produces a single TeX file by expanding all input and include c…'
complete -c texdirflatten -l output -s o -d 'Directory to collect all files'
complete -c texdirflatten -l imgexts -d 'Prepends to the prioritized list of image extensions to search when trying to…'
complete -c texdirflatten -l debug -d 'Enables copious amounts of debugging output - useful if something is going wr…'
complete -c texdirflatten -l version -s V -d 'Displays the current version number and the usage and exits'

