# texdoctk
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texdoctk.1
complete -c texdoctk -s v -d 'verbose: enable some viewer messages which are otherwise sent to stderr, as w…'

