# texexec
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texexec.1
complete -c texexec -l make -d 'make formats'
complete -c texexec -l check -d 'check versions'
complete -c texexec -l process -d 'process file'
complete -c texexec -l mptex -d 'process mp file'
complete -c texexec -l mpxtex -d 'process mpx file'
complete -c texexec -l mpgraphic -d 'process mp file to stand-alone graphics'
complete -c texexec -l mpstatic -d 'process mp/ctx file to stand-alone graphics'
complete -c texexec -l listing -d 'list of file content'
complete -c texexec -l figures -d 'generate overview of figures'
complete -c texexec -l modules -d 'generate module documentation'
complete -c texexec -l pdfarrange -d 'impose pages (booklets)'
complete -c texexec -l pdfselect -d 'select pages from file(s)'
complete -c texexec -l pdfcopy -d 'copy pages from file(s)'
complete -c texexec -l pdftrim -d 'trim pages from file(s)'
complete -c texexec -l pdfcombine -d 'combine multiple pages'
complete -c texexec -l pdfsplit -d 'split file in pages AUTHOR More information about ConTeXt and the tools that …'

