# texfindpkg
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texfindpkg.1
complete -c texfindpkg -s c -d 'Query or install packages by command name'
complete -c texfindpkg -s e -d 'Query or install packages by environment name'
complete -c texfindpkg -s f -d 'Query or install packages by file name'
complete -c texfindpkg -s p -d 'Query or install packages by package name'

