# texfot
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texfot.1
complete -c texfot -l accept -d el
complete -c texfot -l debug -d el
complete -c texfot -l no-debug -d el
complete -c texfot -l ignore -d el
complete -c texfot -l interactive -d el
complete -c texfot -l no-interactive -d el
complete -c texfot -l quiet -d el
complete -c texfot -l no-quiet -d el
complete -c texfot -l stderr -d el
complete -c texfot -l no-stderr -d el
complete -c texfot -l tee -d el
complete -c texfot -l version -d el
complete -c texfot -l help -d el
complete -c texfot -l 'debug\\fR' -d 'tex\\fR'

