# texindy
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texindy.1
complete -c texindy -l version -s V -d el
complete -c texindy -l help -s h -s '?' -d el
complete -c texindy -l quiet -s q -d el
complete -c texindy -l verbose -s v -d el
complete -c texindy -l debug -s d -d el
complete -c texindy -l out-file -s o -d el
complete -c texindy -l log-file -s t -d el
complete -c texindy -l language -s L -d el
complete -c texindy -l codepage -s C -d el
complete -c texindy -l module -s M -d el
complete -c texindy -l input-markup -s I -d el

