# texlinks
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/texlinks.1
complete -c texlinks -l cnffile -s f -d 'use file as configuration file (default: fmtutil. cnf)'
complete -c texlinks -l help -s h -d 'show some help text'
complete -c texlinks -l multiplatform -s m -d 'operate in all platform-specific directories (default: operate only in the di…'
complete -c texlinks -l silent -s s -d 'silently skip over existing scripts/binaries instead of printing a warning'
complete -c texlinks -l unlink -s u -d 'Unlink previously created symlinks'

