# textestvis
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/textestvis.1
complete -c textestvis -s c -d 'Clears cache'
complete -c textestvis -s s -d 'Enables shell escape'
complete -c textestvis -s d -d 'Sets density in ppi (default 72)'
complete -c textestvis -s e -d 'Sets latex engine (default xelatex)'
complete -c textestvis -l help -d 'Prints a help message'

