# tftopl
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/tftopl.1
complete -c tftopl -o charcode-format -d 'The argument  format specifies how character codes are output in the PL file'
complete -c tftopl -o verbose -d 'Without this option, tftopl operates silently'

