# thumbpdf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/thumbpdf.1
complete -c thumbpdf -l help -d 'print usage'
complete -c thumbpdf -l resolution -d 'resolution for GhostScript step (default: 9)'
complete -c thumbpdf -l compress -d 'pdfcompresslevel for thumbpdf. pdf (0-9; default: 9)'

