# tig
# Autogenerated from man page /nix/store/fs7rs3yfpnkmjfinskd7pg46jsk4gc9m-tig-2.5.12/share/man/man1/tig.1.gz
complete -c tig -s v -l version -d 'Show version and exit'
complete -c tig -s h -l help -d 'Show help message and exit'
complete -c tig -s C -d 'Run as if Tig was started in <path> instead of the current working directory'
complete -c tig -l branches
complete -c tig -l remotes
complete -c tig -l tags -d 'parameters.  stash'
complete -c tig -l stdin -d 'option is given, stdin is assumed to be a list of commit IDs and will be forw…'
complete -c tig -l pretty -d 'is given, stdin is assumed to be a "pretty=raw" formatted output similar to t…'

