# tikztosvg
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/tikztosvg.1
complete -c tikztosvg -s o -l output
complete -c tikztosvg -s p -l package
complete -c tikztosvg -s l -l library
complete -c tikztosvg -s q -l quiet
complete -c tikztosvg -l lualatex
complete -c tikztosvg -l xelatex
complete -c tikztosvg -l pdflatex
complete -c tikztosvg -s h -l help
complete -c tikztosvg -s v -l version

