# tio
# Autogenerated from man page /nix/store/62ym3z7f6jlday3fr599bv4cyqm72may-tio-3.9/share/man/man1/tio.1.gz
complete -c tio -s b -l baudrate
complete -c tio -s d -l databits
complete -c tio -s f -l flow
complete -c tio -s s -l stopbits
complete -c tio -s p -l parity
complete -c tio -s o -l output-delay
complete -c tio -s O -l output-line-delay
complete -c tio -s a -l auto-connect
complete -c tio -s n -l no-reconnect
complete -c tio -s e -l local-echo
complete -c tio -s t -l timestamp
complete -c tio -s l -l list
complete -c tio -s L -l log
complete -c tio -s m -l map
complete -c tio -s c -l color
complete -c tio -s S -l socket
complete -c tio -l alert
complete -c tio -l mute
complete -c tio -l script
complete -c tio -l script-file
complete -c tio -l script-run
complete -c tio -l exec
complete -c tio -s v -l version
complete -c tio -s h -l help

