# tlcockpit
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/tlcockpit.1
complete -c tlcockpit -s d -d 'be verbose'
complete -c tlcockpit -o dd -d 'be even more verbose'
complete -c tlcockpit -s q -d 'be quiet'
complete -c tlcockpit -o qq -d 'be even more quiet'

