# tlmgr
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/tlmgr.1
complete -c tlmgr -l repository -d 'X Item "--repository url|path" Specify the package repository from which pack…'
complete -c tlmgr -l gui -d 'X Item "--gui [action]" Two notable GUI front-ends for \\f(CW\\*(C`tlmgr\\*(C\', …'
complete -c tlmgr -l gui-lang -d 'X Item "--gui-lang llcode" By default, the GUI tries to deduce your language …'
complete -c tlmgr -l command-logfile -d 'X Item "--command-logfile file" \\f(CW\\*(C`tlmgr\\*(C\' logs the output of all p…'
complete -c tlmgr -l debug-translation -d 'X Item "--debug-translation" In GUI mode, this switch tells \\f(CW\\*(C`tlmgr\\*…'
complete -c tlmgr -l machine-readable -d 'X Item "--machine-readable" Instead of the normal output intended for human c…'
complete -c tlmgr -l no-execute-actions -d 'X Item "--no-execute-actions" Suppress the execution of the execute actions a…'
complete -c tlmgr -l package-logfile -d 'X Item "--package-logfile file" \\f(CW\\*(C`tlmgr\\*(C\' logs all package actions…'
complete -c tlmgr -l pause -d 'X Item "--pause" This option makes \\f(CW\\*(C`tlmgr\\*(C\' wait for user input b…'
complete -c tlmgr -l persistent-downloads -d 'X Item "--persistent-downloads"'
complete -c tlmgr -l no-persistent-downloads -d 'X Item "--no-persistent-downloads" '
complete -c tlmgr -l pin-file -d 'X Item "--pin-file" Change the pinning file location from \\f(CW\\*(C`TEXMFLOCA…'
complete -c tlmgr -l usermode -d 'X Item "--usermode" Activates user mode for this run of \\f(CW\\*(C`tlmgr\\*(C\';…'
complete -c tlmgr -l usertree -d 'X Item "--usertree dir" Uses dir for the tree in user mode; see "USER MODE" b…'
complete -c tlmgr -l verify-repo
complete -c tlmgr -l backupdir
complete -c tlmgr -l all
complete -c tlmgr -l clean
complete -c tlmgr -l dry-run
complete -c tlmgr -l use-svn
complete -c tlmgr -l local
complete -c tlmgr -l remote
complete -c tlmgr -l json
complete -c tlmgr -l dest
complete -c tlmgr -l localcfg
complete -c tlmgr -l rebuild-sys
complete -c tlmgr -l list
complete -c tlmgr -l only-files
complete -c tlmgr -l only-installed
complete -c tlmgr -l only-remote
complete -c tlmgr -l file
complete -c tlmgr -l force
complete -c tlmgr -l no-depends
complete -c tlmgr -l no-depends-at-all
complete -c tlmgr -l reinstall
complete -c tlmgr -l with-doc
complete -c tlmgr -l with-src -d 'While not recommended, the install-tl\\fR program provides an option to omit i…'
complete -c tlmgr -l windowsmode
complete -c tlmgr -l fileassocmode
complete -c tlmgr -l backup
complete -c tlmgr -l global
complete -c tlmgr -l word
complete -c tlmgr -l self
complete -c tlmgr -l exclude
complete -c tlmgr -l no-auto-remove
complete -c tlmgr -l no-auto-install
complete -c tlmgr -l reinstall-forcibly-removed
complete -c tlmgr -l 'force\\fR' -d 'during an earlier update'
complete -c tlmgr -o var-value -d 'directory names. )'
complete -c tlmgr -l 'all\\fR' -d 'of a package, and use of symbolic links in system directories (not on Windows)'

