# tred
# Autogenerated from man page /nix/store/6pj6ap9v2frj5qd2p001ni52003fmz8d-graphviz-12.2.1/share/man/man1/tred.1.gz
complete -c tred -s o -d 'Redirect output to the given file.  By default, output goes to stdout'
complete -c tred -s v -d 'Verbose output to stderr'
complete -c tred -s r -d 'Print information of removed edges to stderr'
complete -c tred -s '?' -d 'Print usage information.  OPERANDS The following operand is supported:'

