# tsig-keygen
# Autogenerated from man page /nix/store/lkxalk7qzq2r1k8cry3wpi354kbxn9sn-bind-9.20.7-man/share/man/man8/tsig-keygen.8.gz
complete -c tsig-keygen -s a -d 'This option specifies the algorithm to use for the TSIG key'
complete -c tsig-keygen -s h -d 'This option prints a short summary of options and arguments'

