# ttf2afm
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ttf2afm.1
complete -c ttf2afm -s i -d 'force printing glyph names in form `index\'decnum'
complete -c ttf2afm -s u -d 'force printing glyph names in form `uni\'hexnum'
complete -c ttf2afm -s c -d 'write encoding tables to file name'
complete -c ttf2afm -s v -d 'print program version'
complete -c ttf2afm -s e -d 'encode AFM output using encoding vector from enc'
complete -c ttf2afm -s o -d 'output to file outfile instead of standard output'
complete -c ttf2afm -s m -d 'use Unicode mapping num in the font . PP  Platform numbers can be one of'

