# ttftotype42
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/ttftotype42.1
complete -c ttftotype42 -s o -l output -d 'Write output font to R file instead of the standard output.  \' . Sp'
complete -c ttftotype42 -s q -l quiet -d 'Do not generate any error messages.  \' . Sp'
complete -c ttftotype42 -s h -l help -d 'Print usage information and exit.  \' . Sp'
complete -c ttftotype42 -s v -l version -d 'Print the version number and some short non-warranty information and exit'

