# twill
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/twill.1
complete -c twill -s x -d 'says to omit the indexes, module name list, and table of contents pages'

