# typog-grep
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/typog-grep.1
complete -c typog-grep -s a -l all -l any -d 'X Item "-a, --all, --any" ID-discovery mode: Discover all \\f(CW\\*(C`typog-ins…'
complete -c typog-grep -l color -d 'X Item "--color, colour WHEN" Colorize specific log contents for the matching…'
complete -c typog-grep -s C -l config -d 'X Item "-C, --config KEY=VALUE[:KEY=VALUE[:'
complete -c typog-grep -l debug -d 'X Item "--debug" Turn on debug output on stderr'
complete -c typog-grep -s E -l encoding -d 'X Item "-E, --encoding ENCODING" Set the ENCODING of LOG-FILE for the transla…'
complete -c typog-grep -s h -l help -d 'X Item "-h, --help" Display brief help then exit'
complete -c typog-grep -s i -l id -d 'X Item "-i, --[no-]id" Print the actual ID-name that matched REGEXP'
complete -c typog-grep -s y -l ignore-case -d 'X Item "-y, --[no-]ignore-case" Match IDs while ignoring case distinctions in…'
complete -c typog-grep -s j -l job-name -d 'X Item "-j, --[no-]job-name" Print the \\f(CW\\*(C`jobname\\*(C\' that latex asso…'
complete -c typog-grep -s n -l line-number -d 'X Item "-n, --[no-]line-number" Print the line number where the \\f(CW\\*(C`typ…'
complete -c typog-grep -s N -l log-line-number -d 'X Item "-N, --[no-]log-line-number" Print the line number of the log-file whe…'
complete -c typog-grep -s p -l page-number -d 'X Item "-p, --[no-]page-number" Print page number where the contents of the \\…'
complete -c typog-grep -s P -l pager -d 'X Item "-P, --[no-]pager" Redirect output from stdout to the configured pager'
complete -c typog-grep -l show-config -d 'X Item "--show-config" Show the default configuration and exit'
complete -c typog-grep -l show-encodings -d 'X Item "--show-encodings" Show all known encodings and exit'
complete -c typog-grep -s V -l version -d 'X Item "-V, --version" Show version information and exit'
complete -c typog-grep -s w -l word-regexp

