# unzipsfx
# Autogenerated from man page /nix/store/3mjlp2cvkxfkirnb2ppqff5yca844jlm-unzip-6.0/share/man/man1/unzipsfx.1.gz
complete -c unzipsfx -s j -s V -d 'following operating-system specific options:  -X (restore VMS owner/protectio…'

