# update-desktop-database
# Autogenerated from man page /nix/store/ifwfpfz7859qpszrw94vg7v1cm7x3i57-desktop-file-utils-0.28/share/man/man1/update-desktop-database.1.gz
complete -c update-desktop-database -s q -l quiet -d 'Do not display any information about processing and updating progress'
complete -c update-desktop-database -l verbose -d 'OPTIONS The following options are supported:'
complete -c update-desktop-database -s v -d 'Display more information about processing and updating progress.  NOTES'

