# upmendex
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/upmendex.1
complete -c upmendex -s i -d 'Take input from stdin, even when index files are specified'
complete -c upmendex -s l -d 'Set \'sort by character order\'.  By default, \'sort by word order\' is used'
complete -c upmendex -s q -d 'Quiet mode; send no message to stderr, except error messages and warnings'
complete -c upmendex -s r -d 'Disable implicit page range formation'
complete -c upmendex -s c -d 'Compress sequence of intermediate blanks (space(s) and/or tab(s)) into a spac…'
complete -c upmendex -s g -d 'Make Japanese index head A-line (A, Ka, Sa, '
complete -c upmendex -s f -d 'Force to output characters even if the scripts are not supported by upmendex'
complete -c upmendex -s s -d 'Employ sty as the style file'
complete -c upmendex -s d -d 'Employ dic as the dictionary file'
complete -c upmendex -s o -d 'Employ ind as the output index file'
complete -c upmendex -s t -d 'Employ log as the transcript file'
complete -c upmendex -s p -d 'Set the starting page number of the output index list to be no'
complete -c upmendex -l help -d 'Show summary of options'

