# vftovp
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/vftovp.1
complete -c vftovp -o charcode-format -d 'The argument  format specifies how character codes are output in the VPL file'
complete -c vftovp -o verbose -d 'Without this option, vftovp operates silently'

