# vmtouch
# Autogenerated from man page /nix/store/cq6m6zxmw1xdq0zmj0ik1p0k9k6y3wy8-vmtouch-1.3.1/share/man/man8/vmtouch.8.gz
complete -c vmtouch -s t
complete -c vmtouch -s e
complete -c vmtouch -s l
complete -c vmtouch -s L
complete -c vmtouch -s d
complete -c vmtouch -s m
complete -c vmtouch -s p
complete -c vmtouch -s f
complete -c vmtouch -s F
complete -c vmtouch -s i
complete -c vmtouch -s I
complete -c vmtouch -s b
complete -c vmtouch -s 0
complete -c vmtouch -s P
complete -c vmtouch -s v
complete -c vmtouch -s q
complete -c vmtouch -s h

