# vptovf
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/vptovf.1
complete -c vptovf -o verbose -d 'option, vptovf operates silently'

