# weave
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/weave.1
complete -c weave -s p -d 'says to use alternative macros more suited for PDF output'
complete -c weave -s x -d 'says to omit the index, module name list, and table of contents pages'

