# word-list-compress
# Autogenerated from man page /nix/store/18f1x8cvrxpc67872lkxrgjf4c9hb5fc-aspell-0.60.8.1/share/man/man1/word-list-compress.1.gz
complete -c word-list-compress -s c -d 'compress the plain text word list read from standard input'
complete -c word-list-compress -s d -d 'decompress the compressed word list read from standard input'

