# xclip-copyfile
# Autogenerated from man page /nix/store/72z50hz68j2zggpdn90zm0jkpc44pdiv-xclip-0.13/share/man/man1/xclip-copyfile.1.gz
complete -c xclip-copyfile -s p -d 'preserve path formation xclip-pastefile pastes the files out of the clipboard…'

