# xdg-terminal
# Autogenerated from man page /nix/store/hmkf2nk9s7njnipch0fbxsn2vmvsa2py-xdg-utils-1.2.1/share/man/man1/xdg-terminal.1.gz
complete -c xdg-terminal -l help -d 'Show command synopsis'
complete -c xdg-terminal -l manual -d 'Show this manual page'
complete -c xdg-terminal -l version -d 'Show the xdg-utils version information'

