# xdg-desktop-icon
# Autogenerated from man page /nix/store/hmkf2nk9s7njnipch0fbxsn2vmvsa2py-xdg-utils-1.2.1/share/man/man1/xdg-desktop-icon.1.gz
complete -c xdg-desktop-icon -l novendor -d 'Normally, xdg-desktop-icon checks to ensure that a *'
complete -c xdg-desktop-icon -l help -d 'Show command synopsis'
complete -c xdg-desktop-icon -l manual -d 'Show this manual page'
complete -c xdg-desktop-icon -l version -d 'Show the xdg-utils version information'

