# xdg-mime
# Autogenerated from man page /nix/store/hmkf2nk9s7njnipch0fbxsn2vmvsa2py-xdg-utils-1.2.1/share/man/man1/xdg-mime.1.gz
complete -c xdg-mime -l mode -d 'mode can be user or system'
complete -c xdg-mime -l novendor -d 'Normally, xdg-mime checks to ensure that the mimetypes-file to be installed h…'
complete -c xdg-mime -l help -d 'Show command synopsis'
complete -c xdg-mime -l manual -d 'Show this manual page'
complete -c xdg-mime -l version -d 'Show the xdg-utils version information'

