# xdg-open
# Autogenerated from man page /nix/store/hmkf2nk9s7njnipch0fbxsn2vmvsa2py-xdg-utils-1.2.1/share/man/man1/xdg-open.1.gz
complete -c xdg-open -l help -d 'Show command synopsis'
complete -c xdg-open -l manual -d 'Show this manual page'
complete -c xdg-open -l version -d 'Show the xdg-utils version information'

