# xdotool
# Autogenerated from man page /nix/store/qx0jimd9644vssf167w36visyhqqk4k7-xdotool-3.20211022.1/share/man/man1/xdotool.1.gz
complete -c xdotool -l window
complete -c xdotool -l clearmodifiers
complete -c xdotool -l delay
complete -c xdotool -l screen
complete -c xdotool -l polar
complete -c xdotool -l sync
complete -c xdotool -l repeat
complete -c xdotool -l shell
complete -c xdotool -l quiesce
complete -c xdotool -l class
complete -c xdotool -l classname
complete -c xdotool -l role
complete -c xdotool -l maxdepth
complete -c xdotool -l name
complete -c xdotool -l onlyvisible
complete -c xdotool -l pid
complete -c xdotool -l desktop
complete -c xdotool -l limit
complete -c xdotool -l title
complete -c xdotool -l all
complete -c xdotool -l any
complete -c xdotool -l usehints
complete -c xdotool -l relative
complete -c xdotool -l icon-name
complete -c xdotool -l urgency
complete -c xdotool -l overrideredirect

