# xetex
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/xetex.1
complete -c xetex -o no-pdf -d 'Generate Xe\\*(TX\'s extended DVI (. xdv) output instead of pdf'
complete -c xetex -o output-driver -d 'Run  cmd instead of xdvipdfmx to translate xdv to pdf'
complete -c xetex -o papersize -d 'Set pdf media size to string '
complete -c xetex -o draftmode
complete -c xetex -o enc
complete -c xetex -o ipc
complete -c xetex -o ipc-start
complete -c xetex -o translate-file

