# xindy
# Autogenerated from man page /nix/store/xgwsszsf9jy3fdhrrc6095i4jh095jrc-texlive-combined-full-2024-final/share/man/man1/xindy.1
complete -c xindy -l version -s V -d el
complete -c xindy -l help -s h -s '?' -d el
complete -c xindy -l quiet -s q -d el
complete -c xindy -l verbose -s v -d el
complete -c xindy -l debug -s d -d el
complete -c xindy -l out-file -s o -d el
complete -c xindy -l log-file -s t -d el
complete -c xindy -l language -s L -d el
complete -c xindy -l codepage -s C -d el
complete -c xindy -l module -s M -d el
complete -c xindy -l input-markup -s I -d el
complete -c xindy -l interactive -d el
complete -c xindy -l mem-file -d el

