# ykchalresp
# Autogenerated from man page /nix/store/jr2mxlbnz35g03jx7bz90w3rrxfprm86-yubikey-personalization-1.20.0/share/man/man1/ykchalresp.1.gz
complete -c ykchalresp -o nkey -d 'send the challenge to the nth key found'
complete -c ykchalresp -s 1 -d 'send the challenge to slot 1.  This is the default'
complete -c ykchalresp -s 2 -d 'send the challenge to slot 2'
complete -c ykchalresp -s H -d 'send a 64 byte HMAC challenge.  This is the default'
complete -c ykchalresp -s Y -d 'send a 6 byte Yubico OTP challenge'
complete -c ykchalresp -s N -d 'non-blocking mode \\(em abort if the YubiKey is configured to require a key pr…'
complete -c ykchalresp -s x -d 'challenge is hex encoded'
complete -c ykchalresp -s v -d 'enable verbose mode'
complete -c ykchalresp -s 6 -d 'output the response in OATH format, 6 digits'
complete -c ykchalresp -s 8 -d 'output the response in OATH format, 8 digits'
complete -c ykchalresp -s t -d 'use current time as challenge instead of reading challenge from command line …'
complete -c ykchalresp -o iFILE -d 'take challenge from FILE instead of as an argument'
complete -c ykchalresp -s V -d 'print tool version and exit'

