# ykinfo
# Autogenerated from man page /nix/store/jr2mxlbnz35g03jx7bz90w3rrxfprm86-yubikey-personalization-1.20.0/share/man/man1/ykinfo.1.gz
complete -c ykinfo -s s -d 'get the serial number and output it'
complete -c ykinfo -s m -d 'get the serial number and output it as modhex'
complete -c ykinfo -o nkey -d 'read from the nth key found'
complete -c ykinfo -s H -d 'get the serial number and output it as hex'
complete -c ykinfo -s v -d 'get the version and output it'
complete -c ykinfo -s t -d 'get the touch level and output it'
complete -c ykinfo -s p -d 'get the programming sequence and output it'
complete -c ykinfo -s 1 -d 'get the status of slot 1, 1 for programmed and 0 for empty'
complete -c ykinfo -s 2 -d 'get the status of slot 2, 1 for programmed and 0 for empty'
complete -c ykinfo -s a -d 'get all the information above'
complete -c ykinfo -s c -d 'get YubiKey capability information'
complete -c ykinfo -s q -d 'modifier, only show the relevant data from the YubiKey, no extra information'
complete -c ykinfo -s V -d 'print tool version and exit'

