# ykpersonalize
# Autogenerated from man page /nix/store/jr2mxlbnz35g03jx7bz90w3rrxfprm86-yubikey-personalization-1.20.0/share/man/man1/ykpersonalize.1.gz
complete -c ykpersonalize -o Nkey -d 'use the nth YubiKey found'
complete -c ykpersonalize -s 1 -d 'change the first configuration'
complete -c ykpersonalize -s 2 -d 'change the second configuration'
complete -c ykpersonalize -s z -d 'delete configuration in selected slot'
complete -c ykpersonalize -o sfile -d 'save configuration to file instead of key (if file is -, send to stdout)'
complete -c ykpersonalize -o ifile -d 'read configuration from file (if file is -, read from stdin)'
complete -c ykpersonalize -o fformat -d 'format to be used with -s and -i.  Valid options are ycfg and legacy'
complete -c ykpersonalize -s a -d 'the AES secret key as a 32 (or 40 for OATH-HOTP/HMAC CHAL-RESP) char hex valu…'
complete -c ykpersonalize -s c -d 'a 12 char hex value (not modhex) to use as the access code for programming'
complete -c ykpersonalize -s y -d 'always commit without prompting'
complete -c ykpersonalize -s d -d 'dry-run, run without writing a YubiKey'
complete -c ykpersonalize -s v -d 'be more verbose'
complete -c ykpersonalize -s h -d 'display help'
complete -c ykpersonalize -s V -d 'display version'
complete -c ykpersonalize -s n -d 'program NFC NDEF URI'
complete -c ykpersonalize -s t -d 'program NFC NDEF text'
complete -c ykpersonalize -o S0605 -d 'set the scanmap to be used with the YubiKey'
complete -c ykpersonalize -o D0403 -d 'Set the deviceinfo to use with this YubiKey'
complete -c ykpersonalize -s u -d 'Update existing configuration, rather than overwriting'
complete -c ykpersonalize -s x -d 'Swap configuration slot 1 and 2 inside the YubiKey'
complete -c ykpersonalize -o oappend-cr -d 'is set by default'
complete -c ykpersonalize -o ostatic-ticket
complete -c ykpersonalize -o ostrong-pw1
complete -c ykpersonalize -o ostrong-pw2 -d and
complete -c ykpersonalize -o oman-update -d 'are set by default'
complete -c ykpersonalize -s s -d and
complete -c ykpersonalize -s i -d 'ycfg and legacy'
complete -c ykpersonalize -o oaccess
complete -c ykpersonalize -o ooption
complete -c ykpersonalize -s m
complete -c ykpersonalize -o oshort-ticket -d 'is used without'

