# zipnote
# Autogenerated from man page /nix/store/l2q0dnjiv2c1hz98xva7qjma14zfrivl-zip-3.0/share/man/man1/zipnote.1.gz
complete -c zipnote -s w -d 'Write comments to a zipfile from stdin (see below)'
complete -c zipnote -o bpath -d 'Use path for the temporary zip file'
complete -c zipnote -s h -d 'Show a short help'
complete -c zipnote -s v -d 'Show version information'
complete -c zipnote -s b -d 'Use path for the temporary zip file'
complete -c zipnote -s L -d 'Show software license'

