# zsoelim
# Autogenerated from man page /nix/store/6y6ijw6avikf17cyks2k07vc9q1wq31v-man-db-2.13.0/share/man/man1/zsoelim.1.gz
complete -c zsoelim -s C -l compatible -d 'This flag is available for compatibility with other  soelim programs'
complete -c zsoelim -s h -l help -d 'Print a help message and exit'
complete -c zsoelim -s V -l version -d 'Display version information'

